### ISSUE TITLE
Crash on startup [1.12.2]

### ISSUE THREAD

**Issue by DarkXFast** [FlansMods/FlansMod#1002]
- Forge: 1.12.2 - 14.23.5.2810
 - Flan's Mod: 5.5.2

My game crashed on startup. I'm using Forge version 1.12.2 - 14.23.5.2810 and Flan's Mod 5.5.2. Here is the link of the crash report
https://gist.github.com/DarkXFast/d8904e7a76517b276e086a77423e908a

**Comment by ChrisLane** [comment]
This was fixed a while ago but the fix is only in beta versions at the moment.

You can download the current beta files here:
https://github.com/FlansMods/FlansMod/releases/tag/v5.6-beta.3
