### ISSUE TITLE
graphical rendering crash with tinkers compendium

### ISSUE THREAD

**Issue by border999** [FlansMods/FlansMod#1003]
Steps to reproduce the crash:
1. add flans mod and tinkers' compendium
2.  attempt to get into a vehicle from Flan's (mine was the english fighter plane)
3. get rendering crash

**Versions (please complete the following information):**
 - Forge:  1.12.2 - 14.23.5.2810
 - Flan's Mod: 1.12.2-5.6

https://paste.dimdev.org/sipofiquma.mccrash

**Comment by ChrisLane** [comment]
Looks like this crash comes from Tinkers-Compendium.
