### ISSUE TITLE
[1.7.10] Weapon boxes with invisible icons

### ISSUE THREAD

**Issue by Tonas1997** [FlansMods/FlansMod#1006]
Weapon boxes (from both official and "3rd party" packs) show invisible icons for weapons and their crafting ingredients, as shown below. The items _are_ craftable - they are just not visible, turning the crafting of weapons into guesswork. There also appears to be some other GUI-related bugs, like the missing second page (also visible in the provided screenshot). Weapon modification and vehicle tables seem to work nominally.

Disabling Optifine and Inventory Tweaks had no effect on the bug.

![2019-02-17_01 22 22](https://user-images.githubusercontent.com/43859708/52907136-e871f400-3252-11e9-982b-42260b7db658.png)

EDIT: The last three items show their icons:

![2019-02-17_01 32 56](https://user-images.githubusercontent.com/43859708/52907197-10ae2280-3254-11e9-9c2a-f593e56f0fde.png)
![2019-02-17_01 32 59](https://user-images.githubusercontent.com/43859708/52907198-10ae2280-3254-11e9-95ce-bfa9604bd4a3.png)

 - Forge: 10.13.4.1614 - 1.7.10
 - Flan's Mod: 4.10.0

**Comment by ChrisLane** [comment]
Sorry, 1.7.10 isn't supported anymore.
Some people have been working on a 1.7.10 version though that you might find useful.
https://discordapp.com/invite/hN4qmrX for more info on that.
