### ISSUE TITLE
crash report for flans mod when opening minecraft 1.12.2

### ISSUE THREAD

**Issue by roko-711** [FlansMods/FlansMod#1008]
i wanted to download flans mod for 1.12.2, but wen it gets to phase 2 it crashes.
content packs: simple parts, world war 2 and modern warfare. Crash Report: Time: 3/2/19 12:10 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Flan's Mod: Apocalypse (flansmodapocalypse)
Caused by: java.lang.NullPointerException
	at com.flansmod.apocalypse.common.FlansModApocalypse.preInit(FlansModApocalypse.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.9.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1314145792 bytes (1253 MB) / 3825205248 bytes (3648 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2755 53 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version           | Source                                             | Signature                                |
	|:----- |:-------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2            | minecraft.jar                                      | None                                     |
	| UCH   | mcp                  | 9.42              | minecraft.jar                                      | None                                     |
	| UCH   | FML                  | 8.0.99.99         | forge-1.12.2-14.23.4.2755.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.4.2755      | forge-1.12.2-14.23.4.2755.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | creativecoredummy    | 1.0.0             | minecraft.jar                                      | None                                     |
	| UCH   | itemphysic           | 1.4.0             | minecraft.jar                                      | None                                     |
	| UCH   | micdoodlecore        |                   | minecraft.jar                                      | None                                     |
	| UCH   | srm-hooks            | 1.12.2-1.0.0      | minecraft.jar                                      | None                                     |
	| UCH   | securitycraft        | v1.8.11           | [1.12.2]+SecurityCraft+v1.8.11.jar                 | None                                     |
	| UCH   | biomesoplenty        | 7.0.1.2294        | BiomesOPlenty-1.12.2-7.0.1.2294-universal.jar      | None                                     |
	| UCH   | craftstudioapi       | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| UCH   | harvestcraft         | 1.12.2zb          | HarvestCraft-Mod-1.12.2.jar                        | None                                     |
	| UCH   | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| UCH   | twilightforest       | 3.9.851           | twilightforest-1.12.2-3.9.851-universal.jar        | None                                     |
	| UCH   | animania             | 1.6.2             | animania-1.12.2-1.6.2.jar                          | None                                     |
	| UCH   | jei                  | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar                          | None                                     |
	| UCH   | quark                | r1.5-145          | Quark-r1.5-145.jar                                 | None                                     |
	| UCH   | autoreglib           | 1.3-24            | AutoRegLib-1.3-24.jar                              | None                                     |
	| UCH   | bibliocraft          | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| UCH   | chisel               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| UCH   | chiselsandbits       | 14.30             | chiselsandbits-14.30.jar                           | None                                     |
	| UCH   | codechickenlib       | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | creativecore         | 1.9.9             | CreativeCore_v1.9.39_mc1.12.2.jar                  | None                                     |
	| UCH   | customnpcs           | 1.12              | CustomNPCs_1.12.2(30Jan19).jar                     | None                                     |
	| UCH   | ptrmodellib          | 1.0.3             | PTRLib-1.0.3.jar                                   | None                                     |
	| UCH   | props                | 2.6.2             | Decocraft-2.6.2_1.12.2.jar                         | None                                     |
	| UCH   | cdm                  | 0.4.1             | device-mod-0.4.1-1.12.2.jar                        | None                                     |
	| UCH   | emoticons            | 0.2.1             | emoticons-0.2.1-1.12.2.jar                         | None                                     |
	| UCH   | ic2                  | 2.8.111-ex112     | industrialcraft-2-2.8.111-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | mantle               | 1.12-1.3.3.42     | Mantle-1.12-1.3.3.42.jar                           | None                                     |
	| UCH   | tconstruct           | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar                   | None                                     |
	| UCH   | galacticraftcore     | 4.0.2.190         | GalacticraftCore-1.12.2-4.0.2.190.jar              | None                                     |
	| UCH   | galacticraftplanets  | 4.0.2.190         | Galacticraft-Planets-1.12.2-4.0.2.190.jar          | None                                     |
	| UCH   | mjrlegendslib        | 1.12.2-1.1.8      | MJRLegendsLib-1.12.2-1.1.8.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | extraplanets         | 1.12.2-0.4.8      | ExtraPlanets-1.12.2-0.4.8.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | flansmod             | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                        | None                                     |
	| UCEE  | flansmodapocalypse   | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                        | None                                     |
	| UC    | cfm                  | 6.2.0             | furniture-6.2.0-1.12.2.jar                         | None                                     |
	| UC    | journeymap           | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar                        | None                                     |
	| UC    | llibrary             | 1.7.7             | llibrary-1.7.7-1.12.2.jar                          | None                                     |
	| UC    | lunatriuscore        | 1.2.0.42          | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
	| UC    | placeableitems       | 3.3               | placeableitems-3.3.jar                             | None                                     |
	| UC    | redstonepaste        | 1.7.5             | redstonepaste-mc1.12-1.7.5.jar                     | None                                     |
	| UC    | additionalstructures | 2.2.0             | Rex's-Additional-Structures-1.12.x+-(v.2.2.0).jar  | None                                     |
	| UC    | schematica           | 1.8.0.169         | Schematica-1.12.2-1.8.0.169-universal.jar          | None                                     |
	| UC    | secretroomsmod       | 5.6.4             | secretroomsmod-1.12.2-5.6.4.jar                    | None                                     |
	| UC    | sekcphysics          | 0.1.0             | sekcphysics-0.1.0.jar                              | None                                     |
	| UC    | subcommonlib         | 1.2.0.1           | subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
	| UC    | telepads             | $version          | telepads-1.12.2-1.1.0.6.jar                        | None                                     |
	| UC    | torohealthmod        | 1.12.2-11         | torohealth-1.12.2-11.jar                           | None                                     |
	| UC    | treechopper          | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                       | None                                     |
	| UC    | worldedit            | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar  | None                                     |
	| UD    | emoticons_core       | 0.2.1             | minecraft.jar                                      | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.7-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
CreativePatchingLoader (CreativeCore_v1.9.39_mc1.12.2.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
ItemPatchingLoader (ItemPhysic_Full_1.4.19_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
  mchorse.emoticons.core.EmoCoreClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
LoadingPlugin (Quark-r1.5-145.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-8.24.17 310.90.9.05f01' Renderer: 'NVIDIA GeForce GT 120 OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

**Comment by WeareunitedMuricans** [comment]
Your Missing The Simple Parts Mod Here Is The Link https://drive.google.com/file/d/1HmQ9Q3v9C_dsiAaUYUrRFCvZ8Dp4xHUC/view

**Comment by roko-711** [comment]
i have simple parts

**Comment by roko-711** [comment]
it got through the loading screen but when i load a world it is  stuck on loading terrain.

**Comment by roko-711** [comment]
mod removed: placeable items, jei, mjrlegendslib, extraplanets, galacticraft, galacticraftcore, galacticrftplanets,and micdoodlecore. mods added: dynamic surroundings, and serene seasons.

**Comment by roko-711** [comment]
i removed dynamic surroundings, serene's seasons, and orelib. that fixed it!

**Comment by Z-D4WG** [comment]
I got same problem how do i fix it?
