### ISSUE TITLE
WW2 German helmet texture missing

### ISSUE THREAD

**Issue by Ezekhiel** [FlansMods/FlansMod#1009]
As you can see in the screenshot below, I have a problem with the texture of the german helmet : 

![texture bug](https://user-images.githubusercontent.com/48182327/53698226-0c4c4280-3dda-11e9-8485-ca509266f8b6.png)

Dit I miss the fix update for that or this is planned ?

**Comment by ChrisLane** [comment]
The fix for this will be in the next beta release.
