### ISSUE TITLE
With Armourers-Workshop will make some Render error.

### ISSUE THREAD

**Issue by MikuSnow** [FlansMods/FlansMod#1011]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Flan's mod
2. Install Armourers-Workshop
3. Join the game and press F5 or take some flans mod 's items in hand.
4.  Your game will be black.

**Screenshots**

![image](https://user-images.githubusercontent.com/7759441/53747551-79e19700-3ede-11e9-9e13-1363ee94b5c2.png)
![image](https://user-images.githubusercontent.com/7759441/53747561-7e0db480-3ede-11e9-8576-255c62b6ee44.png)

**Versions (please complete the following information):**
 - Forge: 14.23.5.2815
 - Flan's Mod:  1.12.2-5.5.2

**Comment by ChrisLane** [comment]
Where do I download that mod for 1.12.2? I can only find downloads and source code for 1.7.10

**Comment by MikuSnow** [comment]
> 
> 
> Where do I download that mod for 1.12.2? I can only find downloads and source code for 1.7.10

You can download here~
http://plushie.moe:8080/job/Armourers-Workshop-Dev/
Find source code here~
https://github.com/RiskyKen/Armourers-Workshop/tree/develop

**Comment by Liruxo** [comment]
This was fixed in 751024d. Any future release should not contain this bug
