### ISSUE TITLE
server crash after new bug fix release 

### ISSUE THREAD

**Issue by Dutchkills** [FlansMods/FlansMod#1017]
[crash-2019-03-10_21.13.05-server.txt](https://github.com/FlansMods/FlansMod/files/2949984/crash-2019-03-10_21.13.05-server.txt)

hi, i just updated flans mod in my server to the newest release posted about for hours ago, but now when i get to one place it crashes i don't know if there was a vehicle can't go there, other places are fine

Dutchkills

**Comment by ChrisLane** [comment]
[fix-1017.zip](https://github.com/FlansMods/FlansMod/files/2950032/fix-1017.zip)

The version in this zip should fix the issue, let me know.

**Comment by Dutchkills** [comment]
It works. if there is anything wrong with flans youre the one that can fix it.
I'm glad u responded so fast, nice job

Thanks Chrislane

Dutchkills

**Comment by Dutchkills** [comment]
Well i got one thing, i can't fire the gun i changed the controls but nothing happens

**Comment by ChrisLane** [comment]
@Dutchkills 
Firing guns works fine for me, please open a new issue with more information.
What gun? What Forge version? What controls? etc. etc.

**Comment by gamnott** [comment]
Hi I am having an issue using the guns in the vehicles they will not shoot such as the tanks even when i try putting ammunition in them. 
They will not shoot and some of the helicopters will not take off such as the little bird
I would appreciate if you could get back to me. Thank you

**Comment by gamnott** [comment]
Just kidding I found a fix sorry to bother you

**Comment by MrOrca** [comment]
Now i can't open the vehicle menu.

**Comment by Liruxo** [comment]
I am unable to reproduce your problems.
Please verify you are using the latest content packs and FlansMod jar. If the issue persists it is recommended to use a fresh Minecraft, Forge and FlansMod installation to rule out any outdated or faulty jars and/or configuration files
Please also verify you are following [these steps](https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod) to install FlansMod, if not note the differences to your process
