### ISSUE TITLE
Custom Content Pack - Gun reloads, fires but wont show up textured. magenta and black checkered cube.

### ISSUE THREAD

**Issue by JValor2417** [FlansMods/FlansMod#1018]
**Describe the bug**
Essentially everything with my custom gun works, aside from the model showing. I made the model i on the latest version of Toolbox. I exported textures, as (normal) flans model, all the steps i could find within 8 hours on the internet. I have no clue whether its the texture missing or the model maybe not rendering itself? I fully believe it's the texture not loading though, due to the fact my player aims and holds the "invisible" gun. I am on flans 5.3, MC (1.8)

**To Reproduce**
1. I'll put the pack here, 2 kinds. one with just the things I made and the "template files" (sounds, bullets, etc...) and another one with the MW 1.8 pack to show that other guns work when included.
2.  If you guys want to try and fix the model or try it out in SMP, toolbox, whatever may work I would appreciate it. 

**Expected behavior**
So in essence when you join single player, take the gun from creative and get the ammo and such; the gun will reload, it'll shoot and everything its supposed to with exception to a visible model (or one aside from the checkered cube) 

**Screenshots**
![2019-03-10_22 11 13](https://user-images.githubusercontent.com/48421210/54096274-8dc74600-4381-11e9-8e33-663cf5a5ccde.png)
![2019-03-10_22 11 14](https://user-images.githubusercontent.com/48421210/54096275-8dc74600-4381-11e9-8928-dbb377f72cd3.png)
![2019-03-10_22 11 11](https://user-images.githubusercontent.com/48421210/54096276-8dc74600-4381-11e9-9084-396427970711.png)

**Versions (please complete the following information):**
 - Forge: (1.8) 11.14.4.1563
 - Flan's Mod: 1.8-5.1

**Additional context**
*Note: the cube will sometimes show 3 Dimensional in inventory and when dropped or in hand, but also show as a panel the same way (in inventory and out)

**Comment by JValor2417** [comment]
[Custom Content Pack with Issue -James Kelly.zip](https://github.com/FlansMods/FlansMod/files/2950497/Custom.Content.Pack.with.Issue.-James.Kelly.zip)
[Custom Content Pack with Issue -James Kelly - reduced file.zip](https://github.com/FlansMods/FlansMod/files/2950498/Custom.Content.Pack.with.Issue.-James.Kelly.-.reduced.file.zip)



So there is the files i am currently trying to fix, thank you for any and all help guys!
there's also no logs with this post because there's no crash, that is as close as i can get with what i have.

**Comment by ChrisLane** [comment]
Sorry but Flan's mod for 1.8 is no longer supported.
