### ISSUE TITLE
Unable to dismount EntityPlane

### ISSUE THREAD

**Issue by Liruxo** [FlansMods/FlansMod#1020]
**Describe the bug**
Inability to leave the plane by pressing shift

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn in any type of plane or helicopter (e.g. F22 Raptor)
2. Mount the vehicle
3. Toggle the perspective (F5 in the default key layout)

**Expected behaviour**
The ability to leave the vehicle as usual by pressing shift

**Versions:**
 - Forge: 1.12.2-14.23.4.2759
 - Flan's Mod: 1.12.2-v5.6-beta.4

**Additional context**
The bug persists, even after changing the perspective again to first person

**Comment by ChrisLane** [comment]
Fixed in 51bca3b0c2f314b55d1d3874f7f70f94578a3e9b
