### ISSUE TITLE
Mechas are unable to fire the "GL6 Grenade Launcher"

### ISSUE THREAD

**Issue by Liruxo** [FlansMods/FlansMod#1023]
**Describe the bug**
Mechas are unable to fire the "GL6 Grenade Launcher"

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn in a mecha (e.g. Proto Titan)
2. Place the "GL6 Grenade Launcher" in the hand slot of the mecha
3. Deposit ammunition for the "GL6 Grenade Launcher" in the inventory slots
4. Try to fire it

**Expected behaviour**
The "GL6 Grenade Launcher" fires the grenade launcher ammunition from the inventory slots of the mecha

**Versions:**
 - Forge: 1.12.2-14.23.4.2759
 - Flan's Mod: 1.12.2-v5.6-beta.3

**Comment by ChrisLane** [comment]
Fixed in #1133
