### ISSUE TITLE
Parachute not working

### ISSUE THREAD

**Issue by Master-lego** [FlansMods/FlansMod#1026]
**Describe the bug**

Parachute is not working as intented. When falling and right-clicking, the parachute spawns briefly before despawning. Player is also moved upwards a bit? 

**To Reproduce**
Steps to reproduce the behaviour:
1. Hold a parachute item in your hand
2. Fall
3. Right-click to use the item
4. 

**Expected behaviour**

When right-clicking item, a Parachute should and player should ride it. When player hits ground the parachute should despawn.
**Screenshots**

**Versions (please complete the following information):**
 - Forge: 14.23.5.2768
 - Flan's Mod: 5.6 beta.4, bug has existed since 1.12.2 release

**Additional context**

**Comment by ChrisLane** [comment]
@Master-lego "Latest" can mean a lot of things right now, please update your issues to contain the version number.

**Comment by Master-lego** [comment]
Done! ☺
