### ISSUE TITLE
My crosshair turns into a black square when reloading

### ISSUE THREAD

**Issue by DeLobo** [FlansMods/FlansMod#1028]
![2019-03-25_21 12 34](https://user-images.githubusercontent.com/48927929/54951140-31e4eb80-4f43-11e9-8fe1-92ffc617c23f.png)

![2019-03-25_21 12 53](https://user-images.githubusercontent.com/48927929/54951204-580a8b80-4f43-11e9-9b1c-1af999bdb908.png)

![2019-03-25_21 12 50](https://user-images.githubusercontent.com/48927929/54951185-4923d900-4f43-11e9-8298-8acfb21cce39.png)
It only happens when Im not aiming and it happens with every weapon of the mod.
![2019-03-25_21 13 00](https://user-images.githubusercontent.com/48927929/54951232-66f13e00-4f43-11e9-9152-8baf35e4a3f2.png)
I do have some some mods (including optifine) and the conquest texture pack.
Do someone know why does this happens?

**Comment by ChrisLane** [comment]
Please stick to the issue template.
I need to know what version of Flan's Mod and Forge you are using.

Try removing Optifine and any other mods as well as the resource pack to eliminate external factors.
I will re-open the ticket once you've done this.

**Comment by DeLobo** [comment]
It seems that the conquest reforged mod was the responsible of the visual bug since it changes the default crosshair of minecraft.
