### ISSUE TITLE
Tanks and Parachutes 

### ISSUE THREAD

**Issue by ECophogamer524** [FlansMods/FlansMod#1030]
All typs of tanks when shooting a shell doesn`t Destroy blocks or effect mobs (Latest version 5.5.2) and Parachute Not working

**Comment by mertkayacs** [comment]
I cannot shoot any tank. How did you do it?

**Comment by ECophogamer524** [comment]
> I cannot shoot any tank. How did you do it?

simply open the menu of the car put shells and right-click simple
