### ISSUE TITLE
When ride a vehicle it feels so lagy

### ISSUE THREAD

**Issue by FlansDers** [FlansMods/FlansMod#1031]
Hi like the title says when i ride any vehicle its feels so lagy (cant do anything) like the mod has a motion blur or an antialasing active...if i press "e" the inventory works good while the vehicle drives alone but when i close the inventory feels like 1 frame per 2 seconds.
Any suggestions? Config or delete some stuff?
Thx cheers (Y)

**Comment by ChrisLane** [comment]
What version of Flan's Mod and Forge? Does this issue occur in single player with only Flan's Mod installed?
