### ISSUE TITLE
[1.12] Black Screen upon entering third-person or disabling hud

### ISSUE THREAD

**Issue by Aidenkrz** [FlansMods/FlansMod#1032]
**Describe the bug**
Any time I disable the hud or go into third-person my screen will turn black
**To Reproduce**
1. Start a game
2. Press f1 to disable the hud or f5 to go into third-person
3. Boom your screen is now black

**Expected behavior**
My hud would be disabled, or I would be in third-person depending on what I pressed.

**Versions:**
 - Forge: 14.23.5.2823
 - Flan's Mod: 5.6

**Additional context**
List of all my mods: https://pastebin.com/N09Sn23P
(I know that flans is what's causing this, but not if it's because of another mod is breaking flans)

**Comment by ChrisLane** [comment]
Please try to see if the same issue happens with only Flan's Mod installed.
