### ISSUE TITLE
Is bombs not dropping going to get fixed?

### ISSUE THREAD

**Issue by john-h-k** [FlansMods/FlansMod#1035]

**Comment by Liruxo** [comment]
I don't know if the issue section is the correct way to ask question like this, but i can ensure you that i and ChrisLane are working on a fix. The problem is just that this is a hobby project for me, as far as i know also for ChrisLane, so sometimes it is hard to find time.

**Comment by Liruxo** [comment]
Have you tried version v5.6-beta.3?
as far as i am concerned in this pre-release vehicle weapons should work
