### ISSUE TITLE
Server crash on shooting a plane?

### ISSUE THREAD

**Issue by SamboyCoding** [FlansMods/FlansMod#1036]
**To Reproduce**
Steps to reproduce the crash:
1. Shoot a biplane with a barett 50cal. 
2. Sometimes this appears to crash dedicated servers.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - Forge: 14.23.5.2824
 - Flan's Mod: 5.6 beta 5

**Additional context**
Crash report: https://paste.dimdev.org/uyahudejam.mccrash 

Seems to be caused by a packet being received (by a new player?) while the mod is handling server packets, whilst it iterates on the keyset of the map.

**Comment by Liruxo** [comment]
Can you reproduce this crash only with FlansMod?
If not, it would be really helpful if you pinpoint the mods needed for this crash to happen. I am not sure but this looks a lot like a compatibility issue and as such it is very hard to fix it unless you know which mod makes FlansMod trouble
(You are also running a whole bunch of core transformers, i.e. a whole bunch of potential conflicts)

**Comment by SamboyCoding** [comment]
I can't really reproduce it at all. It happened once, randomly, across about 100 hours of server uptime. It's just that this is a crash, in your mod, that you could write defensively around quite easily, so I thought you'd like to know.
