### ISSUE TITLE
Weapons for vehicles not working

### ISSUE THREAD

**Issue by SgtElliot** [FlansMods/FlansMod#1037]
When you try and shoot vehicle weapons they do not work (weapons such as driver guns and tank cannons, aa guns etc) but aircraft guns appear to work (sopwith, a10 etc)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Flans Mod 1.12.2 v5.6-beta.5
2. Go in-game and place a vehicle
3. Load vehicle with ammo
4. Try shooting weapons 

The vehicle is supposed to shoot
**Versions (please complete the following information):**
 - Forge: 1.12.2 - 14.23.5.2768
 - Flan's Mod: Flans Mod 1.12.2 v5.6-beta.5

**Comment by ChrisLane** [comment]
This happens due to some sort of synchronisation issue for vehicles. After testing, I've found that newly placed tanks, AA guns etc. fire weapons correctly, this behaviour breaks after logging out.

**Comment by awpexx** [comment]
I'm having the same problem. Although, some aircraft guns also do not work.

**Comment by SgtElliot** [comment]
I have tried fresh install and am still having this problem, strangely when i revert the mod and content packs to the beta-3 version all vehicle armaments work.

**Comment by y-fu-for-li-fu** [comment]
I'm having the same problem but even with the newly placed vehicles the guns still dont shoot or do anything

**Comment by y-fu-for-li-fu** [comment]
I have tested it with beta 3,4 and 5 and only beta 3 has working guns

**Comment by Liruxo** [comment]
This bug is fixed in the upcoming version

**Comment by syncromash** [comment]
> This bug is fixed in the upcoming version

when is it out?

**Comment by Liruxo** [comment]
This is now fixed in the publicly available FlansMod version v5.6-beta.6
You can download this Pre-Release at https://github.com/FlansMods/FlansMod/releases

**Comment by darkwolfblyat** [comment]
> When you try and shoot vehicle weapons they do not work (weapons such as driver guns and tank cannons, aa guns etc) but aircraft guns appear to work (sopwith, a10 etc)
> 
> **To Reproduce**
> Steps to reproduce the behaviour:
> 
> 1. Install Flans Mod 1.12.2 v5.6-beta.5
> 2. Go in-game and place a vehicle
> 3. Load vehicle with ammo
> 4. Try shooting weapons
> 
> The vehicle is supposed to shoot
> **Versions (please complete the following information):**
> 
> * Forge: 1.12.2 - 14.23.5.2768
> * Flan's Mod: Flans Mod 1.12.2 v5.6-beta.5

im using the tlauncher version and i cant use the main weapons on the planes or the drivers machine guns on the tanks

**Comment by Liruxo** [comment]
As far as i know the Technic Launcher only downloads Modpacks, so you would have to ask the maintainer of your Modpack to update it, or update the mod in your installation for yourself.

**Comment by Phantom088** [comment]
I can't seem to open vehicle menus for tanks, helicopters, are AA/artillery. Any idea how to fix this?
