### ISSUE TITLE
Plane Machine guns, are not working.

### ISSUE THREAD

**Issue by awpexx** [FlansMods/FlansMod#1039]
**Describe the bug**

If i spawn in, any sort of Aircraft, the machine guns, simply do not work. Everything else works, except the  driver machine guns. i Put in the right ammo, i was on creative mode, and, the machine guns do not work on the planes and helicopters.
**To Reproduce**
Steps to reproduce the behaviour:
1. Open Minecraft.
2. Go to Singleplayer.
3. Try to fire the plane machine guns all loaded up and ready.
4. See if it works.

**Expected behaviour**

I expected the guns to fire. Also, i do not understand what the "gun key" is. i set the gun key as my Right Mouse button.
**Screenshots**

**Versions (please complete the following information):**
 - Forge: forge-1.12.2-14.23.5.2836
 - Flan's Mod: Flan's Mod-1.12.2-5.5.2

**Additional context**

**Comment by ChrisLane** [comment]
You're on an old version of the mod.
Download the latest version from here: https://github.com/FlansMods/FlansMod/releases
