### ISSUE TITLE
cant hit any entities

### ISSUE THREAD

**Issue by pastamancr** [FlansMods/FlansMod#1040]
**Describe the bug**

when i hit a entity (like a chicken or zombie) i cant hurt no matter what tool i use
**To Reproduce**
Steps to reproduce the behaviour:
1. hit a chicken
2. cant hit chicken

 

**Expected behaviour**

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 
 - Flan's Mod: 

**Additional context**

**Comment by ChrisLane** [comment]
Please give version numbers and an example of a tool you're using to produce this bug.

**Comment by pastamancr** [comment]
minecraft forge 14.23.5.2836 1.12.2 mod version 5.5.2
i cant hit anything no matter what weapon or item, i tryed to use a sword and it doesnt work i tryed to use a axe and it doesnt work and i tried everything even using my fists i had some other mods,but after testing each mod i found out flans mod was the problem

**Comment by ChrisLane** [comment]
I've never experienced that before. You're on an old version of the mod, please try the latest version from here: https://github.com/FlansMods/FlansMod/releases

Let me know if the issue persists.
