### ISSUE TITLE
Game crashes everytime when i place a veeichle and all the suits and coats have no texture

### ISSUE THREAD

**Issue by ARDGKC** [FlansMods/FlansMod#1041]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/18/19 4:23 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:391)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:391)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: flansmod:vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 7334
	Entity Name: Pak-40
	Entity's Exact location: -121.50, 69.50, 267.50
	Entity's Block location: World: (-122,69,267), Chunk: (at 6,4,11 in -8,16; contains blocks -128,0,256 to -113,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/7335, l='i7tf97f7', x=-121.50, y=69.50, z=267.50], EntityWheel['entity.Wheel.name'/7336, l='i7tf97f7', x=-120.38, y=68.88, z=265.50], EntityWheel['entity.Wheel.name'/7337, l='i7tf97f7', x=-122.63, y=68.88, z=265.50], EntityWheel['entity.Wheel.name'/7338, l='i7tf97f7', x=-122.62, y=68.88, z=268.75], EntityWheel['entity.Wheel.name'/7339, l='i7tf97f7', x=-120.37, y=68.88, z=268.75]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: i7tf97f7
	All players: 1 total; [EntityPlayerMP['ArdgRl'/1328, l='i7tf97f7', x=-121.55, y=68.00, z=264.21]]
	Chunk stats: ServerChunkCache: 4225 Drop: 0
	Level seed: -3584025661600655399
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-120,64,256), Chunk: (at 8,4,0 in -8,16; contains blocks -128,0,256 to -113,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1506 game time, 1506 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 113171 (now: false), thunder time: 12627 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 832786992 bytes (794 MB) / 2080374784 bytes (1984 MB) up to 16106127360 bytes (15360 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx15G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 5, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2811 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version      | Source                                        | Signature                                |
	|:------ |:------------------ |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2811.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2811 | forge-1.12.2-14.23.5.2811.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | securitycraft      | v1.8.11      | [1.12.2]+SecurityCraft+v1.8.11.jar            | None                                     |
	| LCHIJA | clarity            | 1.1          | Clarity-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | flansmod           | 5.5.2        | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| LCHIJA | flansmodapocalypse | 1.0          | Flan's Mod-1.12.2-5.5.2.jar                   | None                                     |
	| LCHIJA | forgelin           | 1.8.2        | Forgelin-1.8.2.jar                            | None                                     |
	| LCHIJA | gottschcore        | 1.7.0        | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar | None                                     |
	| LCHIJA | ichunutil          | 7.1.4        | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| LCHIJA | jei                | 4.13.1.225   | jei_1.12.2-4.13.1.225.jar                     | None                                     |
	| LCHIJA | movinglightsource  | 1.0.15       | movinglightsource-1.12.2-1.0.15.jar           | None                                     |
	| LCHIJA | sanlib             | 1.2.0        | SanLib-1.12-1.2.0.jar                         | None                                     |
	| LCHIJA | sanplayermodel     | 1.0.0        | SanLib-1.12-1.2.0.jar                         | None                                     |
	| LCHIJA | xaerominimap       | 1.15.8       | Xaeros-Minimap-Mod-1.12.jar                   | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ArdgRl'/1328, l='i7tf97f7', x=-121.55, y=68.00, z=264.21]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ChrisLane** [comment]
You're on an old version of the mod.

Please try the latest version from here: https://github.com/FlansMods/FlansMod/releases
