### ISSUE TITLE
Car Render issue

### ISSUE THREAD

**Issue by Yrul** [FlansMods/FlansMod#1042]
Going in a vehicle freezes the camera, and makes everything invisible, however, the vehicle still plays sounds, and according to my minimap; occasionally moves.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Get in car

**Expected behaviour**
Place a vehicle, get in it, and the camera freezes

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 1.12.2
 - Flan's Mod: latest for 5.2.2
- Customnpcs
- Modern Weapons Flans mod Pack
- Ww2 Pack
**Additional context**
Only started recently, after connecting to the internet, as I have been offline for some months.
![image](https://user-images.githubusercontent.com/49767865/56393969-e6e98b80-6203-11e9-9b3b-619d88b9dce2.jpg)
![image](https://user-images.githubusercontent.com/49767865/56394007-fcf74c00-6203-11e9-9a1f-86a66dfaa3d5.jpg)
After boarding
![image](https://user-images.githubusercontent.com/49767865/56394048-18faed80-6204-11e9-8fa1-6d5efbd3feea.jpg)

**Comment by ChrisLane** [comment]
Please give a Flan's Mod version number and also tell us whether this bug happens with only Flan's Mod installed.

**Comment by Yrul** [comment]
The issue does not occur with just flans mod installed
Thank you for the reply. My full mod list is;
Customnpcs
DynamicSurroundings
LunatrisCore
Optifine1.12.2
SchematicaMod1.12.2
Torocrafts'DamageIndicatorMod
Xaero'sMinimap

**Comment by ChrisLane** [comment]
5.2.2 is an old version of Flan's Mod, please use the latest from here: https://github.com/FlansMods/FlansMod/releases

Also, since the issue does not occur with just Flan's Mod installed, please identify which mod is causing issues and then give the version and name of that mod.
