### ISSUE TITLE
Black Screen bug when mod is used together with Astral Sorcery

### ISSUE THREAD

**Issue by towergame** [FlansMods/FlansMod#1046]
**Describe the bug**
Everytime you press f1, f5 or pull out a gun the screen goes black.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Flan's Mod(the latest pre-release of 5.6) and Astral Sorcery
2. Log onto a server or load a world
3. Press F1 to hide hud or F5 to go into third person

**Expected behaviour**
F1 hides the hud and I can still see the world.
F5 puts me in third person and I can see myself

**Screenshots**
It's just a black screen with the hotbar on top(if not in F1 mode)

**Versions (please complete the following information):**
 - Forge: 14.23.5.2821
 - Flan's Mod: 5.6 beta 5

**Additional context**
From all the versions I have used(5.6 beta 5, 5.6 beta and 5.5.2) this is the only version which has this bug.

**Comment by ChrisLane** [comment]
Sounds very similar to #959

**Comment by ghost** [comment]
I also have encountered this issue, it renders Flans unusable as F5 mode in a plane simply blinds you.  And as far as I know versions prior to this don't let you shoot the main guns on the plane.
