### ISSUE TITLE
version 5.5.2  teams are not working

### ISSUE THREAD

**Issue by FloppyCDdrive** [FlansMods/FlansMod#1049]
Dear Devs,
I have recently tried to set up a teams game (tdm) but it didn't start and just said "Time ran out" in the scoreboard. I've followed the tutorial on the webbpage.
if you need more information feel free to write to me.
Forge version 1.12.2-14.23.2.2611

**Comment by Liruxo** [comment]
Which exact version of FlansMod are you using? The version 5.5.2 available at the flansmod website?
I am not familiar with the "Teams Stuff" so in a quick test i was not even able to get the round to start. If noone else can help you i might take a look at the code in the future.

**Comment by FloppyCDdrive** [comment]
Yes I was using the Official 5.5.2 version, same I couldn't get a round to start properly.

**Comment by ChrisLane** [comment]
Improved issue at #1182
