### ISSUE TITLE
Crash when starting server.

### ISSUE THREAD

**Issue by M3TTA** [FlansMods/FlansMod#1050]
**To Reproduce**
Steps to reproduce the crash:
1. install the mod
2. i have no idea whats causing this
[crash-2019-05-08_16.34.16-server.txt](https://github.com/FlansMods/FlansMod/files/3159653/crash-2019-05-08_16.34.16-server.txt)

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 14.23.5.2768  
 - Flan's Mod: 5.5.2  

**Additional context**

**Comment by Liruxo** [comment]
Pleas try using a newer version of FlansMod, available at https://github.com/FlansMods/FlansMod/releases
(At this point in time, i recommend v5.6-beta.3)
