### ISSUE TITLE
Items don't appear

### ISSUE THREAD

**Issue by VolunteerCarp** [FlansMods/FlansMod#1051]
Hi I was in creative getting items and then there was no items but bunch of crafting stuff. Any help? Thanks.

**Comment by Liruxo** [comment]
Please fill out the template. Your bug report/help request is missing a lot of crucial information, so i am only able to speculate that you are missing content packs. Additionally "no items but bunch of crafting stuff" is not a very specify description either. Please be as specify as possible and supply as much information as possible.

**Comment by VolunteerCarp** [comment]
So I wanted to get flans mod because of the tanks and stuff. I launched Minecraft and created a creative world. I than went to get the tanks and shit. But the icons where wool. I thought it was the regular icon for it. But than when I clicked on it. It was nothing but a few stuff. No tanks. No guns. No items. But some crafting items. I don’t know what to do. Idk if was because I deleted flan’s mod apocalypse or something else. If you can help, Then please help. Thanks.

VolunteerCarp

**Comment by Liruxo** [comment]
Your are missing content packs. Head over to https://github.com/FlansMods/FlansMod/releases click on "Assets" and download  the content packs you like. Then just put them into the "Flan" folder. The "Flan" folder is in the same directory as your "mods" folder.

**Comment by VolunteerCarp** [comment]
We
