### ISSUE TITLE
Crash  in server 

### ISSUE THREAD

**Issue by MaxifeuxG** [FlansMods/FlansMod#1055]
**To Reproduce**
Steps to reproduce the crash:
1. Explode a vehicle
or
2. ride with a vehicle

**Versions (please complete the following information):**
 - Forge: Forge version 14.23.5.2768
 - Flan's Mod: Flan's Mod-1.12.2-5.5.2

**Additional context**

[Crash log](https://gist.github.com/MaxifeuxG/12be33736630261ab0a8419d1b52afa8)

**Comment by Liruxo** [comment]
Version 5.5.2 is no longer officially supported, please download a newer version of FlansMod here:
https://github.com/FlansMods/FlansMod/releases.
(At this point in time i recommend v5.6-beta.3)

**Comment by MaxifeuxG** [comment]
Flan's Mod: Flan.s.Mod-1.12.2-5.6

I get the same bug

**Comment by ChrisLane** [comment]
@MaxifeuxG Could you please post the crash log from when you're using the latest 5.6 beta?

**Comment by MaxifeuxG** [comment]
It's exactly the same I think I have the 5.2 but I had the 5.6 just that I compile me even the mods and so he write 5.2 but it's the 5.6 the last beta
