### ISSUE TITLE
Teams next round

### ISSUE THREAD

**Issue by Chicken009** [FlansMods/FlansMod#1058]
I have set up two rounds with teams but whenever the first one ends and the votingscreen pops up the time just runs out and nothing happens, nothing in the console or anything.
When I do /teams start then and the time runs out the sam happens but you can only vote for the first map

 - Flan's Mod: 4.10

**Comment by Liruxo** [comment]
Version 4.10 is no longer officially supported, please download a newer version of FlansMod here:
https://github.com/FlansMods/FlansMod/releases.
(At this point in time i recommend v5.6-beta.3)
