### ISSUE TITLE
Gradle compiling issue

### ISSUE THREAD

**Issue by Liruxo** [FlansMods/FlansMod#1060]
**Describe the bug**
Building the current Flan's Mod only by cloning the repository is not possible

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone
2. execute ./gradlew build
3. observe the problem

**Expected behaviour**
gradle successfully builds

**Log**
[Link to gist](https://gist.github.com/Liruxo/1300b286f73f83ac9c2effe5aa2fb507)

**Versions (please complete the following information):**
 - Forge: 1.12.2-14.23.5.2768
 - Flan's Mod: Latest build of Github (as of 29.05.2019)

**Additional context**
This bug is caused by the the two commits https://github.com/FlansMods/FlansMod/commit/2c2bb2f8e99100c19ab86576c87a9206599017ef and https://github.com/FlansMods/FlansMod/commit/d39c90525fe5eb2c4c93903c96be0bcf1a6f2a73 of "Flan" who seems to use a different version/gradle configuration than in the repositiory

**Comment by ChrisLane** [comment]
@jamioflan

**Comment by ChrisLane** [comment]
Reverted @jamioflan's commit in dde965b7fbc64181146fd76e1a2c5a3f9ae18a7d.
Looks like he was using 1.11 method names for some reason.
