### ISSUE TITLE
Flans Mod crashes every time vehicle is loaded

### ISSUE THREAD

**Issue by mmol82** [FlansMods/FlansMod#1061]
**To Reproduce**
Steps to reproduce the crash:
1. Get a vehicle from the creative inventory
2. Place it down

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 1.12.2-14.23.5.2768
 - Flan's Mod: Flans Mod 5.5.2 for MC 1.12.2

**Additional context**

"Ticking Entity" error

**Comment by ChrisLane** [comment]
You're on an old version of the mod.
Please try a more recent version from here: https://github.com/FlansMods/FlansMod/releases

**Comment by mmol82** [comment]
If it’s outdated, then how come it’s the latest version on the website?
