### ISSUE TITLE
Flans mod crashes when i spawn in a vehicle

### ISSUE THREAD

**Issue by FauultySpell** [FlansMods/FlansMod#1062]
**To Reproduce**
Steps to reproduce the crash:
1. Spawn Vehicle 
2. https://pastebin.com/jxuu3nW8
3. 
4. 

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 10.13.4.1614 (Minecraft 1.7.10 Java 8)
 - Flan's Mod: Flans mod 4.10.0

**Additional context**

**Comment by mmol82** [comment]
My guess is that it is outdated, and no longer supported. However, I'm not an expert, so just get that.

**Comment by FauultySpell** [comment]
> My guess is that it is outdated, and no longer supported. However, I'm not an expert, so just get that.

All them mods and content packs are all in date they work in singleplayer not in my server

**Comment by mmol82** [comment]
> > My guess is that it is outdated, and no longer supported. However, I'm not an expert, so just get that.
> 
> All them mods and content packs are all in date they work in singleplayer not in my server

That's odd. I'm honestly not sure what's happened. Good luck, though.

**Comment by ChrisLane** [comment]
Sorry but Flan's Mod for 1.7.10 is no longer supported.
