### ISSUE TITLE
Including patch/beta stepping in the file name

### ISSUE THREAD

**Issue by Liruxo** [FlansMods/FlansMod#1064]
**Describe the solution you'd like**
As the title suggest i want the released files at https://github.com/FlansMods/FlansMod/releases to include the patch/beta stepping. The current files from version 5.6-beta.0 up to 5.6-beta.5 all have the same name, confusing the information of the actual patch/beta level of the currently used file(s). As most people describing bugs or issues will only include the file name version as FlansMod version (e.g. 1.12.2-5.6) reviewers are forced to guess which patch level/beta version they are actually using.

**Comment by TwiliDiamondOcelot** [comment]
A more simplefix would be by changing line 12 in build.gradle from "version = "5.5.2"" to "version = "5.6-beta.x"", as I noticed that the files you get from running "gradlew.bat build" on windows makes the version "5.5.2", which is not what the files are on the Releases page. Tested and it works; not sure why the Releases files are different though.

**Comment by Liruxo** [comment]
Can you please verify you have the latest updates pulled from Git, because as you can clearly see at https://github.com/FlansMods/FlansMod/blob/1.12.2/build.gradle the release  version uses the up-to-date 5.6 version description

**Comment by TwiliDiamondOcelot** [comment]
https://github.com/FlansMods/FlansMod/blob/v5.6-beta.5/build.gradle
From the source.zip file on the Releases page most recent

**Comment by TwiliDiamondOcelot** [comment]
direct download https://github.com/FlansMods/FlansMod/archive/v5.6-beta.5.zip
