### ISSUE TITLE
Crash 1.12.2 LAN server next button on WW2 Armour Box

### ISSUE THREAD

**Issue by mojoyup1528** [FlansMods/FlansMod#1065]
**To Reproduce**
Steps to reproduce the crash:
1. Create the WW2 Armour box and place into the world
2. Right click to access
3. Use the next button arrow below the armour and click through
4. Game crashes if on Lan server (have not tested other game setups)

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 14.23.4.2705 (the second to latest stable as of June 1st.)
 - Flan's Mod: WW2-Content Pack-1.12.2-5.5.2
[crash-2019-06-01_22.48.13-client.txt](https://github.com/FlansMods/FlansMod/files/3244397/crash-2019-06-01_22.48.13-client.txt)

Text of crash report if file doesn't load:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 6/1/19 10:48 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.flansmod.client.gui.GuiArmourBox.drawRecipe(GuiArmourBox.java:122)
	at com.flansmod.client.gui.GuiArmourBox.func_73863_a(GuiArmourBox.java:85)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.flansmod.client.gui.GuiArmourBox.drawRecipe(GuiArmourBox.java:122)
	at com.flansmod.client.gui.GuiArmourBox.func_73863_a(GuiArmourBox.java:85)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: com.flansmod.client.gui.GuiArmourBox
	Mouse location: Scaled: (486, 257). Absolute: (973, 502)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['mojoyup'/4245, l='MpServer', x=21.85, y=65.00, z=312.96]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (60,64,252), Chunk: (at 12,4,12 in 3,15; contains blocks 48,0,240 to 63,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1002514 game time, 354785 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 122 total; [EntityZombie['Zombie'/19204, l='MpServer', x=7.54, y=17.00, z=275.25], EntitySkeleton['Skeleton'/20485, l='MpServer', x=38.53, y=33.00, z=383.73], EntitySkeleton['Skeleton'/20486, l='MpServer', x=30.50, y=33.00, z=390.50], EntitySkeleton['Skeleton'/20487, l='MpServer', x=101.73, y=69.00, z=287.51], EntitySpider['Spider'/19724, l='MpServer', x=-3.50, y=78.00, z=321.50], EntityEnderman['Enderman'/20494, l='MpServer', x=-49.50, y=5.00, z=260.50], EntityEnderman['Enderman'/20495, l='MpServer', x=-53.50, y=5.00, z=259.50], Entityscorpion['Scorpion'/19989, l='MpServer', x=-2.25, y=63.00, z=367.82], EntityCreeper['Creeper'/19996, l='MpServer', x=59.50, y=11.00, z=244.50], EntityItem['item.item.scorpionstinger'/19230, l='MpServer', x=-18.83, y=67.00, z=373.66], EntityZombie['Zombie'/20254, l='MpServer', x=-36.50, y=32.00, z=363.50], EntityItem['item.item.egg'/19232, l='MpServer', x=20.70, y=63.50, z=298.40], EntityCreeper['Creeper'/20000, l='MpServer', x=54.50, y=11.00, z=242.50], EntityCreeper['Creeper'/20001, l='MpServer', x=53.50, y=11.00, z=240.50], EntityOtherPlayerMP['BooperDooper'/579, l='MpServer', x=22.31, y=65.00, z=312.33], EntityItem['item.item.egg'/20267, l='MpServer', x=20.92, y=63.00, z=297.57], EntitySpider['Spider'/20012, l='MpServer', x=-34.50, y=63.00, z=331.50], EntityBat['Bat'/20524, l='MpServer', x=-2.15, y=33.05, z=322.51], EntityBat['Bat'/20525, l='MpServer', x=36.75, y=26.00, z=287.25], EntityItem['item.item.scorpionstinger'/20269, l='MpServer', x=-39.75, y=63.00, z=332.64], EntityBat['Bat'/20526, l='MpServer', x=33.84, y=25.41, z=291.53], EntityWolf['Wolf'/46, l='MpServer', x=-54.69, y=73.00, z=296.92], EntityCreeper['Creeper'/20273, l='MpServer', x=-17.50, y=63.00, z=359.50], EntityCreeper['Creeper'/20274, l='MpServer', x=-15.50, y=63.00, z=364.50], EntityBat['Bat'/20537, l='MpServer', x=-29.92, y=35.12, z=352.67], EntityItem['item.item.scorpionstinger'/20029, l='MpServer', x=-0.85, y=63.00, z=368.87], Entityscorpion['Scorpion'/20285, l='MpServer', x=26.45, y=23.00, z=265.70], EntityWolf['Wolf'/62, l='MpServer', x=-38.30, y=77.00, z=305.45], EntityItem['item.item.egg'/12864, l='MpServer', x=19.25, y=63.00, z=299.33], EntitySpider['Spider'/20290, l='MpServer', x=-32.90, y=71.00, z=240.30], EntityBat['Bat'/20546, l='MpServer', x=-56.05, y=5.05, z=383.63], EntityWolf['Wolf'/581, l='MpServer', x=39.12, y=72.00, z=354.46], EntityWolf['Wolf'/72, l='MpServer', x=-18.43, y=65.36, z=237.46], EntityCow['Cow'/19534, l='MpServer', x=28.22, y=61.00, z=292.77], EntityCow['Cow'/19536, l='MpServer', x=28.41, y=61.00, z=292.11], EntityCow['Cow'/19538, l='MpServer', x=25.90, y=61.00, z=292.53], EntityBat['Bat'/17246, l='MpServer', x=19.32, y=41.10, z=291.74], EntityBat['Bat'/17247, l='MpServer', x=33.17, y=40.10, z=292.43], EntityItem['item.item.scorpionstinger'/18529, l='MpServer', x=-20.16, y=29.00, z=334.63], EntityEnderman['Enderman'/20322, l='MpServer', x=-22.50, y=14.00, z=339.50], EntityZombie['Zombie'/20071, l='MpServer', x=31.50, y=52.00, z=358.50], EntityCow['Cow'/19566, l='MpServer', x=26.64, y=61.00, z=292.11], EntityPlayerSP['mojoyup'/4245, l='MpServer', x=21.85, y=65.00, z=312.96], EntityCreeper['Creeper'/19058, l='MpServer', x=16.49, y=41.00, z=279.85], EntityItem['item.item.scorpionstinger'/19062, l='MpServer', x=74.08, y=72.00, z=303.32], EntityZombieVillager['Zombie Villager'/20093, l='MpServer', x=-28.50, y=43.00, z=355.50], EntityWolf['Wolf'/640, l='MpServer', x=-41.48, y=67.00, z=301.57], Entityscorpion['Scorpion'/19329, l='MpServer', x=74.50, y=46.00, z=274.50], EntityBat['Bat'/20366, l='MpServer', x=-21.29, y=38.10, z=333.57], EntityBat['Bat'/20367, l='MpServer', x=-0.48, y=35.58, z=339.11], EntityChicken['Chicken'/145, l='MpServer', x=18.20, y=63.00, z=299.80], EntityChicken['Chicken'/146, l='MpServer', x=19.42, y=63.50, z=298.00], EntityMecha['Proto Titan'/147, l='MpServer', x=27.39, y=63.00, z=301.12], EntitySeat['entity.Seat.name'/148, l='MpServer', x=27.39, y=64.50, z=301.12], Entityscorpion['Scorpion'/20116, l='MpServer', x=38.55, y=73.00, z=337.72], EntityChicken['Chicken'/149, l='MpServer', x=18.20, y=63.00, z=299.24], EntityChicken['Chicken'/150, l='MpServer', x=18.69, y=63.00, z=296.20], EntityCreeper['Creeper'/13462, l='MpServer', x=8.14, y=75.09, z=326.48], EntityChicken['Chicken'/151, l='MpServer', x=19.74, y=63.00, z=296.15], EntityChicken['Chicken'/152, l='MpServer', x=21.17, y=63.00, z=296.50], EntityChicken['Chicken'/153, l='MpServer', x=19.23, y=63.00, z=299.65], EntityChicken['Chicken'/154, l='MpServer', x=19.77, y=63.00, z=296.58], EntitySkeleton['Skeleton'/20122, l='MpServer', x=22.50, y=66.00, z=251.50], EntityChicken['Chicken'/155, l='MpServer', x=20.61, y=63.00, z=297.55], EntityChicken['Chicken'/157, l='MpServer', x=18.76, y=63.00, z=297.51], EntityChicken['Chicken'/158, l='MpServer', x=20.79, y=63.00, z=296.92], EntityChicken['Chicken'/159, l='MpServer', x=20.35, y=63.00, z=299.44], EntityZombie['Zombie'/20127, l='MpServer', x=-14.50, y=48.00, z=297.50], EntityChicken['Chicken'/160, l='MpServer', x=18.93, y=63.50, z=298.21], EntityChicken['Chicken'/162, l='MpServer', x=18.20, y=63.00, z=296.24], EntityChicken['Chicken'/163, l='MpServer', x=20.14, y=63.50, z=298.20], EntityChicken['Chicken'/165, l='MpServer', x=18.28, y=63.00, z=296.88], EntityChicken['Chicken'/168, l='MpServer', x=18.61, y=63.00, z=298.80], EntityChicken['Chicken'/172, l='MpServer', x=18.20, y=63.00, z=298.64], EntityCamera['unknown'/116652, l='MpServer', x=27.39, y=63.00, z=301.12], EntityBat['Bat'/19629, l='MpServer', x=49.40, y=31.03, z=276.98], EntityBat['Bat'/174, l='MpServer', x=18.55, y=43.10, z=308.75], EntityBat['Bat'/175, l='MpServer', x=31.98, y=51.10, z=305.25], EntityArmorStand['Armor Stand'/176, l='MpServer', x=19.50, y=65.00, z=309.50], EntityArmorStand['Armor Stand'/177, l='MpServer', x=21.50, y=65.00, z=309.50], EntityItemFrame['entity.ItemFrame.name'/178, l='MpServer', x=23.50, y=66.50, z=309.03], EntityBat['Bat'/19380, l='MpServer', x=26.51, y=50.56, z=300.61], EntityZombie['Zombie'/20404, l='MpServer', x=14.65, y=73.00, z=340.24], EntityCreeper['Creeper'/20405, l='MpServer', x=27.73, y=76.00, z=323.45], EntityCreeper['Creeper'/20158, l='MpServer', x=35.50, y=69.00, z=375.50], EntityCreeper['Creeper'/20415, l='MpServer', x=11.84, y=54.00, z=283.53], EntityBat['Bat'/194, l='MpServer', x=42.75, y=47.10, z=306.25], EntityCreeper['Creeper'/19906, l='MpServer', x=1.67, y=33.00, z=305.53], EntityBat['Bat'/195, l='MpServer', x=35.25, y=49.10, z=308.45], EntitySpider['Spider'/20419, l='MpServer', x=-48.06, y=9.00, z=239.00], EntitySpider['Spider'/20420, l='MpServer', x=-43.70, y=10.10, z=241.13], EntitySkeleton['Skeleton'/19909, l='MpServer', x=64.50, y=5.00, z=244.75], EntitySkeleton['Skeleton'/19910, l='MpServer', x=65.50, y=5.00, z=253.50], EntityZombie['Zombie'/20166, l='MpServer', x=-46.50, y=82.00, z=291.50], EntityCreeper['Creeper'/20425, l='MpServer', x=0.82, y=65.00, z=256.43], EntityOtherPlayerMP['BooperDooper'/579, l='MpServer', x=15.83, y=78.00, z=445.90], EntityItem['item.item.scorpionstinger'/20428, l='MpServer', x=23.13, y=23.00, z=263.77], EntityItem['item.item.scorpionstinger'/20430, l='MpServer', x=27.28, y=23.00, z=264.39], EntityOtherPlayerMP['BooperDooper'/579, l='MpServer', x=184.27, y=76.25, z=423.42], EntitySkeleton['Skeleton'/18646, l='MpServer', x=22.50, y=38.00, z=293.68], Entityscorpion['Scorpion'/18647, l='MpServer', x=18.49, y=41.00, z=305.43], EntityWolf['Wolf'/215, l='MpServer', x=61.86, y=83.00, z=381.50], EntitySkeleton['Skeleton'/18907, l='MpServer', x=-19.50, y=78.00, z=307.50], Entityscorpion['Scorpion'/20187, l='MpServer', x=-40.43, y=63.00, z=332.59], EntitySpider['Spider'/20191, l='MpServer', x=-38.50, y=64.00, z=327.50], EntitySpider['Spider'/20194, l='MpServer', x=-47.50, y=64.00, z=318.50], EntitySpider['Spider'/19941, l='MpServer', x=-22.50, y=35.00, z=348.50], EntityZombie['Zombie'/20200, l='MpServer', x=-18.50, y=72.00, z=259.50], EntitySkeleton['Skeleton'/20458, l='MpServer', x=-37.50, y=9.00, z=299.50], EntityCreeper['Creeper'/20203, l='MpServer', x=-9.50, y=5.00, z=260.50], EntityCreeper['Creeper'/20460, l='MpServer', x=-52.19, y=9.00, z=241.48], EntityOtherPlayerMP['BooperDooper'/20250, l='MpServer', x=22.31, y=65.00, z=312.33], EntityZombie['Zombie'/20468, l='MpServer', x=-32.50, y=56.00, z=349.50], Entityscorpion['Scorpion'/19957, l='MpServer', x=62.76, y=71.00, z=297.95], EntityBat['Bat'/18678, l='MpServer', x=16.25, y=53.10, z=287.25], Entityscorpion['Scorpion'/19958, l='MpServer', x=74.51, y=72.00, z=310.69], EntityZombie['Zombie'/20471, l='MpServer', x=60.59, y=71.00, z=320.78], EntityItem['item.item.scorpionstinger'/18936, l='MpServer', x=5.26, y=71.00, z=343.75], EntitySpider['Spider'/19960, l='MpServer', x=59.78, y=71.00, z=315.61], EntityZombie['Zombie'/20472, l='MpServer', x=74.22, y=71.00, z=328.41], EntityZombie['Zombie'/20473, l='MpServer', x=64.47, y=72.00, z=329.20], EntityItem['item.item.egg'/16639, l='MpServer', x=18.69, y=63.00, z=296.15]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1425826920 bytes (1359 MB) / 4080271360 bytes (3891 MB) up to 4080271360 bytes (3891 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
	IntCache: cache: 0, tcache: 3, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State       | ID                  | Version                      | Source                                          | Signature                                |
	|:----------- |:------------------- |:---------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAA | minecraft           | 1.12.2                       | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAA | mcp                 | 9.42                         | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAA | FML                 | 8.0.99.99                    | forge-1.12.2-14.23.4.2705.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | forge               | 14.23.4.2705                 | forge-1.12.2-14.23.4.2705.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | obfuscate           | 0.2.5                        | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAA | uncraftingtable     | 1.8-beta6                    | [1.12]UncraftingTable-1.8-beta6.jar             | None                                     |
	| UCHIJAAAAAA | ambientsounds       | 3.0                          | AmbientSounds_v3.0.4_mc1.12.2.jar               | None                                     |
	| UCHIJAAAAAA | architecturecraft   | @VERSION@                    | architecturecraft-1.12-1.20.jar                 | None                                     |
	| UCHIJAAAAAA | thebombzenapi       | 2.9.2                        | ThebombzenAPI-v2.9.2-mc1.12.2.jar               | None                                     |
	| UCHIJAAAAAA | autoswitch          | 5.6.2                        | AutoSwitch-v5.6.2-mc1.12.2.jar                  | None                                     |
	| UCHIJAAAAAA | better_diving       | 1.0.6                        | BetterDiving-1.12.2-1.0.6.jar                   | None                                     |
	| UCHIJAAAAAA | bibliotheca         | 1.3.3-1.12.2                 | bibliotheca-1.3.3-1.12.2.jar                    | None                                     |
	| UCHIJAAAAAA | bookworm            | 1.12.2-1.0.0                 | bookworm+-+1.0.0+(1.12.2).jar                   | None                                     |
	| UCHIJAAAAAA | catwalks            | 1.12.2-4.0.42                | catwalks-1.12.2-4.0.42.jar                      | None                                     |
	| UCHIJAAAAAA | cfm                 | 6.2.1                        | cfm-6.2.1-mc1.12.2.jar                          | None                                     |
	| UCHIJAAAAAA | chameleon           | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAAAA | codechickenlib      | 3.1.5.331                    | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | shadowmc            | 3.8.0                        | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UCHIJAAAAAA | extrarails          | 1.3.0                        | ExtraRails-1.12-1.3.0.jar                       | None                                     |
	| UCHIJAAAAAA | extremeanimals      | 1.0.2.1                      | ExtremeAnimals-1.0.2.1-1.12.2.jar               | None                                     |
	| UCHIJAAAAAA | fastleafdecay       | v14                          | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJAAAAAA | flansmod            | 5.5.2                        | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAAAA | flansmodapocalypse  | 1.0                          | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAAAA | flatcoloredblocks   | mc1.12-6.6                   | flatcoloredblocks-mc1.12-6.6.jar                | None                                     |
	| UCHIJAAAAAA | foamflower          | 1.12.2-1.0.0.0-beta1         | foamflower-1.12.2-1.0.0.0-beta1.jar             | None                                     |
	| UCHIJAAAAAA | furenikusroads      | 1.0.3                        | Furenikus-Roads-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAAAA | hammertime          | 2.0.0                        | Hammer-Time-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAAAA | hopperducts         | 1.5                          | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| UCHIJAAAAAA | hud                 | 1.3.9                        | hud-1.3.9-1.12.jar                              | None                                     |
	| UCHIJAAAAAA | inventorytweaks     | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAAAA | primitivecrafting   | 1.1                          | Primitive-Crafting-Mod-1.12.2.jar               | None                                     |
	| UCHIJAAAAAA | jei                 | 4.11.0.212                   | jei_1.12.2-4.11.0.212.jar                       | None                                     |
	| UCHIJAAAAAA | journeymap          | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAAAA | forgelin            | 1.5.1                        | Shadowfacts-Forgelin-1.12.2.jar                 | None                                     |
	| UCHIJAAAAAA | leveluphp           | 1.12.2-1.4.0                 | Level-Up-HP-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAAAA | longerdays          | 1.0.4                        | longerdays-1.0.4.jar                            | None                                     |
	| UCHIJAAAAAA | mcpaint             | 1.0.1                        | MC-Paint-Mod-1.12.2.jar                         | None                                     |
	| UCHIJAAAAAA | minecolonies        | 1.12.2-0.9.4-RELEASE         | minecolonies-1.12.2-0.9.4-RELEASE-universal.jar | None                                     |
	| UCHIJAAAAAA | minions             | 2.0.2                        | Minions-1.12.jar                                | None                                     |
	| UCHIJAAAAAA | movinglightsource   | 1.0.15                       | movinglightsource-1.12.2-1.0.15.jar             | None                                     |
	| UCHIJAAAAAA | naturalbabyanimals  | 1.0.4                        | naturalbabyanimals-1.0.4-mc1.12.1.jar           | None                                     |
	| UCHIJAAAAAA | neat                | 1.4-15                       | Neat+1.4-15.jar                                 | None                                     |
	| UCHIJAAAAAA | recipehandler       | 0.12                         | NoMoreRecipeConflict-0.12(1.12.2).jar           | None                                     |
	| UCHIJAAAAAA | nei                 | 2.4.1                        | Not-Enough-Items-1.12.2-Recommended.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | openglider          | @VERSION@                    | OpenGlider-1.12.1-1.1.0.jar                     | None                                     |
	| UCHIJAAAAAA | redstoneflux        | 2.0.1                        | RedstoneFlux-1.12.2.jar                         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAAAA | ropebridge          | 2.0.5                        | ropebridge-1.12-2.0.7.jar                       | None                                     |
	| UCHIJAAAAAA | simpleminingdrills  | 1.4.0                        | Simple-Mining-Drills-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAAAA | spartanshields      | 1.5.1                        | Spartan-Shields-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAAAA | storagedrawers      | 1.12-5.3.5                   | StorageDrawers-1.12.2-5.3.7.jar                 | None                                     |
	| UCHIJAAAAAA | terra               | 1.0                          | Terra+1.12.2+-+2.0.jar                          | None                                     |
	| UCHIJAAAAAA | treechopper         | 1.2.4                        | Tree-Chopper-Mod-1.12.2.jar                     | None                                     |
	| UCHIJAAAAAA | of                  | 0.13                         | Useful+Interior+-+0.13+[1.12.2].jar             | None                                     |
	| UCHIJAAAAAA | veinminer           | 0.38.2                       | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| UCHIJAAAAAA | veinminermodsupport | 0.38.2                       | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| UCHIJAAAAAA | vending             | 1.12.2-3.0.1.2               | vending-1.12.2-3.0.1.2.jar                      | None                                     |
	| UCHIJAAAAAA | worldedit           | 6.1.8                        | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 1060/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: jonesycraft-1-12-2-1513522851.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by Liruxo** [comment]
It seems you are using an outdated version. Please head over to https://github.com/FlansMods/FlansMod/releases and download v5.6-beta.3, the currently most stable version

Also in the future please put your crash report in a gist at https://gist.github.com/ and just link it in the report
