### ISSUE TITLE
5.6 Vehicle weapons bug

### ISSUE THREAD

**Issue by Modsojoy** [FlansMods/FlansMod#1066]
**Describe the bug**

Using the latest version in multiplayer prevents usage of vehicle guns and will crash the server. Handheld weapons are not affected.
**To Reproduce**
Steps to reproduce the behaviour:
1. Host a Forge FML server with the latest release
2. Spawn any vehicle with weapons on it
3. Load and attempt to fire (if you get that far)
4. 

**Expected behaviour**

A crash should be expected and a full server restart required to repair it
**Screenshots**

N/A
**Versions (please complete the following information):**
 - Forge: 14.23.5.2837
 - Flan's Mod: 1.12.2.5.6, the latest one found under the releases tab here on Github. 

**Additional context**

The server owner is out of town and i dont have access to the machine that hosts, so im unable to provide a crashlog immediately, when able i'll setup a local server to get one from.

**Comment by ChrisLane** [comment]
@Modsojoy do you have a crash log yet?
