### ISSUE TITLE
Vehicle Camera Crash.

### ISSUE THREAD

**Issue by singekoo** [FlansMods/FlansMod#1067]
Crashed when driving around in ground vehicle.  "No Cubes" was installed. a Mod that tries to morph the Terrain into a Smooth Continuous thing. might ally itself well to ground vehicles actually....
Steps to reproduce the crash:
1. Be in a Humvee form the modern weapons pack.  Also in third person I think.
2. 
3. 
4. 

**Versions (please complete the following information):**
 - Forge:  14.23.5.2838
 - Flan's Mod: 1.12.2-5.5.2

**Additional context**
https://paste.dimdev.org/mulibusoqa.mccrash

**Comment by Liruxo** [comment]
Version 5.5.2 is no longer officially supported, please download a newer version of FlansMod here:
https://github.com/FlansMods/FlansMod/releases.
(At this point in time i recommend v5.6-beta.3)
