### ISSUE TITLE
Crash when accsessing Mech Inventory.

### ISSUE THREAD

**Issue by singekoo** [FlansMods/FlansMod#1068]
Crashes the game when trying to acsess the Mechs (Small orange and Large Purple so far tested and has happened) inventory after it had run out of gas and you have not left the cockpit.

**To Reproduce**
Steps to reproduce the crash:
1. open mech inventory while sitting in cockpit, put fuel can in inventory and leave it in their.
2. walk around in the mech till it runs out of fuel.
3. attempt to open mechs inventory.
4. 

**Versions (please complete the following information):**
 - Forge:   14.23.5.2838
 - Flan's Mod: 1.12.2-5.5.2

**Additional context**
https://paste.dimdev.org/ubazebiheg.mccrash

**Comment by Liruxo** [comment]
Version 5.5.2 is no longer officially supported, please download a newer version of FlansMod here:
https://github.com/FlansMods/FlansMod/releases.
(At this point in time i recommend v5.6-beta.3)

**Comment by singekoo** [comment]
Ooops. sorry.
