### ISSUE TITLE
Bugs on guns:

### ISSUE THREAD

**Issue by danielchim** [FlansMods/FlansMod#1069]
I am using the latest version of flan's mod in Minecraft 1.7.10, and the guns are only in 2d icons like this:
![image](https://user-images.githubusercontent.com/12156547/59109981-a9d28780-8970-11e9-8371-95aca3ab57c7.png)
and the console output are with:
Unidentified block: flansmod:gunBox.DCsModernGunBox, id 446

Any help?

**Comment by Liruxo** [comment]
Minecraft version 1.7.10 is no longer officially supported, please download a newer version of FlansMod for the latest supported Minecraft version (currently 1.12.2) here:
https://github.com/FlansMods/FlansMod/releases.
(At this point in time i recommend v5.6-beta.3)

**Comment by Kiritoslayer115** [comment]
What does this mean?

**Comment by Kiritoslayer115** [comment]
I make my game mode 1.12.2 and downloaded the latest version but now im missing the 2d insteal of the 3d models i.e. 3d models show up and guns work but in inventory 2d models are replaced with black and purple missing texture

**Comment by danielchim** [comment]
> I make my game mode 1.12.2 and downloaded the latest version but now im missing the 2d insteal of the 3d models i.e. 3d models show up and guns work but in inventory 2d models are replaced with black and purple missing texture

This might be the mod author forgot to add 2d texture, or maybe one of your texture pack overrides it.
