### ISSUE TITLE
Mech equipment not craftable

### ISSUE THREAD

**Issue by LWnellA** [FlansMods/FlansMod#1070]
**Describe the bug**
Several mech tools/upgrades cannot be crafted and does not show recipes when a recipe viewer is used.
The upgrades/tools that can't be crafted are as follows:
iron drill, iron refiner, nanobots, redstone magnet, diamond detector, metal magpie, auto fueler, rocket pack, ore crusher, dust extractor, laser diamond cutter, diamond cutter, iron armor, waste compactor, rotary magnet, rotary super magnet, lantern, and diamond armor.
**To Reproduce**
Steps to reproduce the behaviour:
1.  Install Flan's mod and the mech packs
2.  Attempt to craft mech upgrade/tools
3. Attempt to view mech tool/upgrade recipe

**Expected behaviour**
For the parts to be crafted as per the recipes shown on the site

**Screenshots**
![2019-06-08_09 46 43](https://user-images.githubusercontent.com/23419184/59139996-18e0c800-89d3-11e9-8f1d-105b8ee772a7.png)

**Versions (please complete the following information):**
 - Forge: 1.12.2-14.23.5.2838
 - Flan's Mod: 5.5.2

**Additional context**
Not sure if related, but the medkit from the modern warfare pack is also not craftable, because the recipe now calls for 'uncraftable potion' rather than a health potion
![2019-06-08_09 50 51](https://user-images.githubusercontent.com/23419184/59139997-1ed6a900-89d3-11e9-8743-48b73b7fdf7e.png)

**Comment by Liruxo** [comment]
Version 5.5.2 is no longer officially supported, please download a newer version of FlansMod here:
https://github.com/FlansMods/FlansMod/releases.
(At this point in time i recommend v5.6-beta.3)
