### ISSUE TITLE
Missing textures in Modern Warfare and WWII packs

### ISSUE THREAD

**Issue by NovaCenturionXVI** [FlansMods/FlansMod#1071]
**Describe the bug**
Missing/broken textures for the STG 44, Panzerschreck, Luger, German WWII helmet, Leopard 2a6, and M1 Abrams. This seems to be a persisting issue in both Forge 2611 and 2768; Flans mod 5.5.1 to 5.6. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Download Forge 2611 or 2768, Flans Mod 5.5.1 or 5.6, Simple Parts, WWII pack, and/or Modern Weapons/Warfare pack
2. Open Minecraft and make a new world in creative
3. From creative, take the STG 44, Panzerschreck, Luger, German WWII helmet Leopard 2a6, and/or M1 Abrams.
4. Once you place/equip/select the weapons/helmet/vehicles, you will then see the missing/empty textures. 

**Expected behaviour**
Missing/empty textures for the STG 44, Panzerschreck, Luger, German WWII helmet, Leopard 2a6, and the M1 Abrams' tank tracks

**Screenshots**
![img 1](https://user-images.githubusercontent.com/52092610/59959187-35bfd580-9480-11e9-9952-afcf7d61b40d.png)
![img 2](https://user-images.githubusercontent.com/52092610/59959188-36f10280-9480-11e9-8db6-5bd959a0c5a9.png)
![img 3](https://user-images.githubusercontent.com/52092610/59959189-37899900-9480-11e9-89d3-7b34c47ff6b0.png)
![img 4](https://user-images.githubusercontent.com/52092610/59959190-39535c80-9480-11e9-9551-fa25e3c0d5c5.png)
![img 5](https://user-images.githubusercontent.com/52092610/59959192-39ebf300-9480-11e9-8a7f-8012f69249a9.png)
![img 6](https://user-images.githubusercontent.com/52092610/59959193-3b1d2000-9480-11e9-9b0f-b4543d2029d3.png)
![img 7](https://user-images.githubusercontent.com/52092610/59959194-3bb5b680-9480-11e9-9d45-349e5caea54d.png)

**Versions (please complete the following information):**
 - Forge: 2611 and 2768
 - Flan's Mod: 5.5.6 and 5.6

**Additional context**
I have been trying to find fixes for the past few days, but couldn't find anything conclusive. Also, when I was doing my search on the great Google machine, there seem to be a few others who had this same issue a couple of years ago. 

P.S: I have no other mods installed nor am I running optifine.

**Comment by NovaCenturionXVI** [comment]
Ok, I fixed the Luger and Panzerschreck by getting the skin png and txt files from here (also had to fix the FG42 and it was successful), but I still haven't been able to fix the STG 44, leopard, helmet, or M1 even though I changed the files :(

**Comment by MattFrags** [comment]
Hey I've the exact problems you're having but I have an additional one. When I use any mounted machineguns such as the MG42 the guns points down and the handles are right in front of my face, leading  me not being able to see and shoot anything. And please tell me how to fix the weapon textures thanks

**Comment by ChrisLane** [comment]
These issues are already fixed in v5.6 of the mod and content packs. I suspect you've only updated the mod.
Make sure you delete the old content packs and install the new versions from here: https://github.com/FlansMods/FlansMod/releases
