### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by Doktorjohs** [FlansMods/FlansMod#1072]
it's because when i add the mods too the mod folder it doesn't load in all features on the blocks and it is really annoying please help me VH. Doktorjohs

**Comment by Liruxo** [comment]
Can you please specify what "the mods" are and what "all features on the blocks" means. What blocks are you talking about? What are "the features" especially which features do you expect to load and which are loaded? Additionally please stick to the template, as you are missing crucial information like e.g. the FlansMod version.

**Comment by ChrisLane** [comment]
Not enough information.
