### ISSUE TITLE
Game crashes when shift clicking a gun into the mod table

### ISSUE THREAD

**Issue by chexo3** [FlansMods/FlansMod#1076]
**To Reproduce**
Steps to reproduce the crash:
1. Acquire gun.
2. Acquire Gun Modification table.
3. Shift click gun into table.
4. Game crashes.

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 14.23.5.2838
 - Flan's Mod: 5.5.2

**Additional context**

https://gist.github.com/chexo3/13b4a5f48b340d2120b9c3f1c85dbb40#file-crash-2019-07-10_21-31-32-client-txt

**Comment by ChrisLane** [comment]
This crash has already fixed, please get the latest version of the mod and content packs from [here](https://github.com/FlansMods/FlansMod/releases)
