### ISSUE TITLE
game crashes when holding some guns

### ISSUE THREAD

**Issue by kkbthe** [FlansMods/FlansMod#1077]
**To Reproduce**
Steps to reproduce the crash:
1. spawn in gun like desert eagle 
2. hold it in hand
3. move mouse

![bandicam 2019-07-15 04-37-18-872](https://user-images.githubusercontent.com/52895547/61189622-b1630b80-a655-11e9-8993-e929ad528bae.jpg)

**Versions (please complete the following information):**
 - Forge: 1.12.2-forge1.12.2-14.23.5.2838
 - Flan's Mod: 1.12.2-5.5.2
[fml-crash-2019-07-15_02.59.42.txt](https://github.com/FlansMods/FlansMod/files/3390440/fml-crash-2019-07-15_02.59.42.txt)

**Additional context**

**Comment by ChrisLane** [comment]
You're using an old version of the mod. Please download the latest [here](https://github.com/FlansMods/FlansMod/releases)

**Comment by kkbthe** [comment]
I downloaded the updates, and the problems still happen.

**Comment by ChrisLane** [comment]
The crash log that you posted doesn't match the crash that you had.
Please post a new crash log for the new version of flan's mod that you installed.

**Comment by ChrisLane** [comment]
Closing until a new crash log is given.
