### ISSUE TITLE
Various Bugs

### ISSUE THREAD

**Issue by SharpForceTrauma** [FlansMods/FlansMod#1078]
I'm not entirely sure if these have been solved yet or not, but I'm also not sure if i'm getting the mods from the right places

All of the bugs I have seen in the 1.12 version (downloaded from the official Flans Mod website) with Modern Warfare, Apocalypse, WW2 and Ye Olde addon packs that I can remember. There's a quite a few here, and if any or all of these have been addressed I apologize. There are also a few suggestions I will demarcate with + instead of - :
-Virtually every German WW2 weapon has a broken model with the exception of the Kar98. The Luger model apparently doesn't even exist as it can't be seen when equipped. As well, the Mills Bomb has a messed up texture.
-Many vehicles will not spawn into the world, and many more will crash the game when spawned, and a few have limited functionality such as driver machine guns not working. The ones that do not spawn or crash the game are usually the modern vehicles. This especially is true for Mechas. This is seemingly regardless of machine performance as trying these on a higher end computer results in the same.
-Mounted machine guns on blocks (off of vehicle mount) are virtually unusable as even when you can get them to be placed (placing them is a bit janky) usually they will point straight down regardless of where you're aiming. And many vehicle machine guns can simply not be used no matter what ammo you put in them.
-Dual wielding/off handing anything is, well useless. I can understand this since items in the offhand generally cannot be used or at least used well and the old 1.7.10 dual wielding tactic is now basically impossible. The only usable offhand tactic is using the riot shield and a one handed gun in offhand and I don't actually know if this will allow the shield to work
-Third person aiming and firing is strange, as your character no longer holds out their equipped weapon. This confuses me especially since in 1.7.10 the character model was able to do this, and not much has changed other than off hand being added.
-Explosives added in the mod are not deterred by water, in the sense that they will still cause destruction even when submerged (unlike vanilla TNT or creepers). As far to my knowledge this was not a problem in 1.7.10 either
-The FMG-9 will not accept any ammunition
-The Japanese handgun model has always been and is currently unfinished. As It stands, it would look more at home being labelled "Welrod".
-The flamethrower has no sound when fired other then, weirdly enough the sound of bullet ricochet when used on a surface.
+As cool as it would seem, it is often kind of annoying that hostile mobs can spawn with the flans armor equipped. For one, it can ruin the immersion in a survival world not utilizing flans on the same directory and for another, it can make fighting these mobs much harder in said survival world since there is now no knockback and the helmets allow them to survive in the daytime. It should either be made impossible or the rarity rate adjusted to the same as other vanilla armors
+Add more aquatic vehicles
+More armor patterns for different units/factions. Say there was a uniform for the 1st Infantry Division (Big Red One) or the 7th Panzer Division (Rommels tank div), things like that. Would make for an interesting try at historical reenactment within minecraft servers instead of just bland generic patterns.

If these have been addressed/fixed I would CERTAINLY appreciate links to the fixed files. I really enjoy this mod and want to finally play it in a newer version than 1.7.10.
Will also provide screenshots if needed, but I just have not obtained any atm.

**Comment by ChrisLane** [comment]
You're not using the latest version (the website is outdated)
Get a newer version here: https://github.com/FlansMods/FlansMod/releases

**Comment by SharpForceTrauma** [comment]
> You're not using the latest version (the website is outdated)
> Get a newer version here: https://github.com/FlansMods/FlansMod/releases

Ah, thanks! Will check if these work and then get back to you

**Comment by SharpForceTrauma** [comment]
Update: Got the latest versions from here
Most of the gripes I had were fixed, however a few remain and new ones exist
-FMG will still not work with any SMG ammo
-MP 40 texture will not show, and the MG42 texture is messed up
-Browning machine guns cannot be emplaced
-The Tunnel Bore texture appears to be made of brightly colored lego blocks and crashes the game when you try to enter it.

But overall, it is fixed to a point where it can be enjoyed. Good work!

**Comment by ChrisLane** [comment]
Please make new issues for each of those remaining bugs. Make sure to search for existing issues and not open duplicates.
MG42 and MP40 textures are already fixed for the next release.
The tunnel bore is incomplete and this is known.
