### ISSUE TITLE
The Part Crafting Table isnt working

### ISSUE THREAD

**Issue by TheBaithooven** [FlansMods/FlansMod#1080]
I can place the Part Crafting Table from the Flans Mod but CAN NOT use it. Regardless of Single or Multiplayer it just wont open.>

**To Reproduce**
Steps to reproduce the behaviour:
1. Get in Creative
2. Place the Part Crafting Table 
3. Try to Click on it 
4. See how nothing happens

**Expected behaviour**
The menu for crafting parts 
**Screenshots**

**Versions (please complete the following information):**
 - Forge: 1.12.2-14.23.5.2837
 - Flan's Mod: 5.5.1

**Comment by TheBaithooven** [comment]
Plus it seem like in my version the crafting recepice are off

**Comment by Liruxo** [comment]
Please head over to https://github.com/FlansMods/FlansMod/releases and download v5.6-beta.3, which should fix the problem.

**Comment by KatinuKanalas** [comment]
i cant get the part crafting table nor by crafting or creative what do i do?

**Comment by KatinuKanalas** [comment]
and i can see it on the jei but i cant do anything
