### ISSUE TITLE
Vehicle crash after hopping on/ staying on it for a couple seconds/firing main gun

### ISSUE THREAD

**Issue by knahdeidnu** [FlansMods/FlansMod#1081]
**To Reproduce**
Steps to reproduce the crash:
1. Place down a vehicle
2. Hop onto driver seat
3. Stay on it for a couple seconds/fire main gun or secondary gun
4. Game would display 'fatal error' screen and crash back to main menu.

 - Forge: 1.7.10 - 10.13.4.1614,  10.13.2.1291
 - Flan's Mod: 4.10.0

**Additional context**
No crash report was generated since the game did not crash entirely, but fml latest log reflected a little bit of the info.
[fml-client-latest.log](https://github.com/FlansMods/FlansMod/files/3412265/fml-client-latest.log)
[fml-client-latest.log](https://github.com/FlansMods/FlansMod/files/3412268/fml-client-latest.log)

**Comment by ChrisLane** [comment]
Sorry but 1.7.10 is no longer supported
