### ISSUE TITLE
No Gun Sounds

### ISSUE THREAD

**Issue by DerScherenmann** [FlansMods/FlansMod#1083]
**Describe the bug**

No Sounds when shooting a weapon or being shot by another Weapon. Only impact Sounds are heard.

**To Reproduce**
Steps to reproduce the behaviour:
1. gradlew build
2. 
3. 
4. 

**Expected behaviour**

Hearing Gun Sounds while shooting or when other Players are shooting. Also assets/flansmod/sounds/ is empty except for unlocknotch.ogg

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 1.12.2-forge1.12.2-14.23.5.2768
 - Flan's Mod: via git clone 23/07/2019

**Additional context**

**Comment by ChrisLane** [comment]
Could also be an issue with @Liruxo's PR but I'll look into it soon.

**Comment by Liruxo** [comment]
Is this in multiplayer? Because i can not reproduce this issue in single player

Edit: did some testing and it turns out the client was sending Packets, which works for some reason as long as your are not actually playing on a "real" server
