### ISSUE TITLE
Flans mod bug where I fall out the plane randomly 

### ISSUE THREAD

**Issue by syncromash** [FlansMods/FlansMod#1085]
**Describe the bug**
Randomly fall out the plane on minecraft forge 1.7.10

**To Reproduce**
Steps to reproduce the behaviour:
1.take off  
2. Fly straight 
3. Do a few manoeuvres at 100% throttle 
4.  Voila you have fallen out your plane
Versions:
 - Forge:1.7.10 
 - Flan's Mod: 1.7.10

**Additional context**

**Comment by Liruxo** [comment]
We are sorry, but Flans Mod for 1.7.10 is no longer supported
