### ISSUE TITLE
Flans mod and german helmet is missing textures

### ISSUE THREAD

**Issue by syncromash** [FlansMods/FlansMod#1087]
**Describe the bug**
Grey German helmet has the classic purple texture on it 

**To Reproduce**
Steps to reproduce the behaviour:
1. Put on grey German helmet 

**Expected behaviour**
Texture is present 

**Screenshots**

![ECBF32A8-5595-495C-9B67-19E1C269B680](https://user-images.githubusercontent.com/53299711/61878386-ce66cc80-aee8-11e9-903d-47409a76506a.jpeg)
![23E5DA11-50F9-4FBA-80D4-FD97D427AE7F](https://user-images.githubusercontent.com/53299711/61878387-ce66cc80-aee8-11e9-92b4-0d355f17ff81.jpeg)

**Versions (please complete the following information):**
 - Forge: 1.12.2
 - Flan's Mod: 1.12.2

**Comment by ChrisLane** [comment]
You didn't post your flan's mod version number but I assume you're using an outdated version of the mod and packs because this has already been fixed. 
Please search through existing issues next time before posting duplicates.

**Comment by syncromash** [comment]
I am using 5.5.2

Sent from my iPhone

On 25 Jul 2019, at 18:56, Chris Lane <notifications@github.com<mailto:notifications@github.com>> wrote:


You didn't post your flan's mod version number but I assume you're using an outdated version of the mod and packs because this has already been fixed.
Please search through existing issues next time before posting duplicates.

**Comment by syncromash** [comment]
Or the latest version
