### ISSUE TITLE
Question about removing vehicles

### ISSUE THREAD

**Issue by Trnrr** [FlansMods/FlansMod#1089]
Hey guys is there currently any easy-ish way to remove vehicles from the default pack? I know vehicles are a big part of flans but with the modpack I'm working on we have decided not to use them at the moment. Is there anyway to remove them all? Currently I have disabled the vehicle and parts crafting table, but the vehicles/parts still show up in JEI(obviously). I just wanted to ask before I manually hide them all with CraftTweaker. Also big thanks for continuing to update this mod.

**Comment by Liruxo** [comment]
Although i am not sure what you mean with "default pack", you should be able to just unpack a content pack, find the 'vehicles' folder and delete the files in it. Recompress it and now you have a content pack which doesn't includes vehicles.

**Comment by Trnrr** [comment]
> 
> 
> Although i am not sure what you mean with "default pack", you should be able to just unpack a content pack, find the 'vehicles' folder and delete the files in it. Recompress it and now you have a content pack which doesn't includes vehicles.

Ok thanks, I will try that. Also I just meant the packs that you get from https://github.com/FlansMods/FlansMod/releases so like Modern.Warfare-Content.Pack-1.12.2-5.6.jar etc.
