### ISSUE TITLE
I USE 5.5.2 AND HELMET IS STILL MISSING TEXTURE

### ISSUE THREAD

**Issue by syncromash** [FlansMods/FlansMod#1091]
**Describe the bug**
Helmet is missing texture i use latest version of flansmod 5.52

**To Reproduce**
Steps to reproduce the behaviour:
1. place the german helmet on

**Expected behaviour**

Helmet should have helmet as i am running latest version

**Versions (please complete the following information)**
 - Forge: 2838
 - Flan's Mod: 5.5.2

**Comment by ChrisLane** [comment]
Clearly you still havent used the search feature, otherwise you would have found countless other issues opened with the same problem.

This problem was fixed months ago in a version that is available at https://github.com/FlansMods/FlansMod/releases

**Comment by syncromash** [comment]
You haven’t given me a clear solution to the problem though where can I find this fixed version then

Sent from my iPhone

On 26 Jul 2019, at 21:10, Chris Lane <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1091<https://github.com/FlansMods/FlansMod/issues/1091>.

**Comment by ChrisLane** [comment]
If you follow the link I gave, you can download the latest "pre-release"
