### ISSUE TITLE
A new Release

### ISSUE THREAD

**Issue by rvveber** [FlansMods/FlansMod#1094]
I know this is not supposed to go into Issues,

I just really want a new fixed release, and forge 2838 compatibility

**Comment by ChrisLane** [comment]
I might release a new build when #1088 is done.
Does v5.6-beta.5 not work with 2838 in some way?

**Comment by TwiliDiamondOcelot** [comment]
Why are you using forge 2838? That version is bug identified; use the recommended forge version or the lowest version needed for all the mods you have.

**Comment by rvveber** [comment]
v5.6 works with 2838, Vehicles crash the game though.

**Comment by rvveber** [comment]
> Why are you using forge 2838? That version is bug identified; use the recommended forge version or the lowest version needed for all the mods you have.

I'm using it because it is required for the latest stable spongeforge version which my server is running on. The latest spongeforge version that does not require latest forge version is too old and does not include important bug- and perfomance fixes that i'd like to have on my server.

**Comment by ChrisLane** [comment]
> v5.6 works with 2838, Vehicles crash the game though.

I noticed this the other day, it's an issue that happens on servers but not in single player.
I'll work on getting that fixed.

**Comment by rvveber** [comment]
I have to apologize. I didn't know you would need the simple-parts pack for a few content packs.
I installed it on server and  client and it works without crashes now.
