### ISSUE TITLE
Tanks & Artillery Won't Fire Shells When Loaded

### ISSUE THREAD

**Issue by TwiliDiamondOcelot** [FlansMods/FlansMod#1101]
**Describe the bug**
When you try to fire a tanks or artillery's cannon when the vehicle is loaded, the cannon won't fire.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a tank or artillery vehicle (e.g. Bofors or M1 Abrams).
2. Load the vehicle.
3. Try to fire the cannon.

**Expected behaviour**
Cannons would fire.

**Versions (please complete the following information)**
 - Forge: 14.23.5.2837 
 - Flan's Mod: 5.6

**Comment by Liruxo** [comment]
Duplicate of #1037

**Comment by syncromash** [comment]
Chris hasn’t even told us how to fix this
