### ISSUE TITLE
Dual wielding not work in 1.12.2

### ISSUE THREAD

**Issue by matteof04** [FlansMods/FlansMod#1115]
**Describe the bug**
When I press shift the hotbar freezes and does not let me select the second weapon.

**Versions**
 - MC: 1.12.2
 - Forge: 2838
 - Flan's Mod: 5.6
 - OS: Ubuntu 18.04

**Comment by Liruxo** [comment]
I am completely unable to reproduce this issue. Please provide more information and try different configurations to reproduce your issue. What is supposed to happen when you press shift? Are other mods installed? Does it unfreeze after you release shift? Does only the hotbar freeze, or are other things also affected? Can you influence this behavior in any way?

**Comment by matteof04** [comment]
Sorry,
I tried to use the 1.7.10 dual wielding system, but it not work in 1.12.2 version because the mod use the minecraft native dual wielding system.

**Comment by UnitTHK** [comment]
it doesn't work for me as well, I'm on version 1.12.2, Windows OS, the scrollwheel completely froze up when I hold shift and it stop freezeing when I stop holding Shift, dual wielding via the native Minecraft dual wield feature only allow me to shoot the right one and not the left one
