### ISSUE TITLE
Game crashed while rendering screen, after browsing through the Macheteman russian gun box

### ISSUE THREAD

**Issue by Garvey64** [FlansMods/FlansMod#1118]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MekanismCoremod (Mekanism-1.12.2-9.8.1.383.jar)
  LesslagCorePlugin (Less-Lag-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 8/19/19 5:20 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.flansmod.client.gui.GuiGunBox.renderPanelForeground(GuiGunBox.java:290)
	at com.flansmod.client.gui.GuiGunBox.func_146976_a(GuiGunBox.java:223)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.flansmod.client.gui.GuiGunBox.renderPanelForeground(GuiGunBox.java:290)
	at com.flansmod.client.gui.GuiGunBox.func_146976_a(GuiGunBox.java:223)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)

-- Screen render details --
Details:
	Screen name: com.flansmod.client.gui.GuiGunBox
	Mouse location: Scaled: (208, 88). Absolute: (625, 480)
	Screen size: Scaled: (456, 249). Absolute: (1366, 745). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Garvey64'/288047, l='MpServer', x=1151.75, y=55.00, z=443.49]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (32,64,256), Chunk: (at 0,4,0 in 2,16; contains blocks 32,0,256 to 47,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 700047 game time, 36099 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 60 total; [EntityPlayerSP['Garvey64'/288047, l='MpServer', x=1151.75, y=55.00, z=443.49], EntitySheep['Sheep'/135, l='MpServer', x=1154.60, y=61.00, z=465.55], EntityBabySkeleton['Baby Skeleton'/288136, l='MpServer', x=1208.25, y=26.00, z=416.25], EntityCreeper['Creeper'/288138, l='MpServer', x=1078.50, y=27.00, z=496.50], EntityZombie['Zombie'/288139, l='MpServer', x=1078.50, y=27.00, z=493.50], EntityZombie['Zombie'/288149, l='MpServer', x=1145.50, y=29.00, z=493.50], EntityZombie['Zombie'/288150, l='MpServer', x=1102.78, y=42.00, z=522.50], EntityCamera['unknown'/24, l='MpServer', x=1184.27, y=66.00, z=447.88], EntityChicken['Chicken'/288156, l='MpServer', x=1116.82, y=75.00, z=511.44], EntitySkeleton['Skeleton'/288164, l='MpServer', x=1137.50, y=21.00, z=501.50], EntityCreeper['Creeper'/288165, l='MpServer', x=1136.50, y=21.00, z=497.50], EntityPlane['AH-64D Apache'/288038, l='MpServer', x=1184.27, y=66.00, z=447.88], EntityEnderman['Enderman'/288166, l='MpServer', x=1122.55, y=24.00, z=516.51], EntitySeat['entity.Seat.name'/288039, l='MpServer', x=1187.33, y=66.48, z=445.60], EntitySkeleton['Skeleton'/288167, l='MpServer', x=1119.73, y=26.00, z=519.53], EntityZombie['Zombie'/288163, l='MpServer', x=1140.50, y=29.00, z=499.50], EntityBat['Bat'/288044, l='MpServer', x=1178.25, y=16.76, z=447.44], EntityCreeper['Creeper'/288172, l='MpServer', x=1134.50, y=21.00, z=502.50], EntityItem['item.tile.cactus'/288045, l='MpServer', x=1147.28, y=63.00, z=460.73], EntityCreeper['Creeper'/288173, l='MpServer', x=1135.50, y=21.00, z=501.50], EntitySquid['Squid'/288046, l='MpServer', x=1140.85, y=62.00, z=460.60], EntityChicken['Chicken'/288174, l='MpServer', x=1121.83, y=67.00, z=478.27], EntityItem['item.item.egg'/288175, l='MpServer', x=1122.30, y=67.00, z=478.52], EntitySeat['entity.Seat.name'/288040, l='MpServer', x=1189.02, y=65.68, z=445.47], EntitySquid['Squid'/288168, l='MpServer', x=1130.60, y=61.08, z=408.55], EntityWheel['entity.Wheel.name'/288041, l='MpServer', x=1186.53, y=63.05, z=446.50], EntityCreeper['Creeper'/288169, l='MpServer', x=1136.50, y=25.00, z=376.50], EntitySkeleton['Skeleton'/288171, l='MpServer', x=1131.50, y=22.00, z=508.50], EntitySheep['Sheep'/232497, l='MpServer', x=1155.55, y=61.00, z=461.64], EntityWheel['entity.Wheel.name'/261313, l='MpServer', x=1172.32, y=69.54, z=451.01], EntitySheep['Sheep'/232640, l='MpServer', x=1154.39, y=61.00, z=461.64], EntityWheel['entity.Wheel.name'/261312, l='MpServer', x=1187.69, y=66.00, z=448.71], EntitySquid['Squid'/288065, l='MpServer', x=1184.08, y=60.00, z=426.59], EntityCreeper['Creeper'/288076, l='MpServer', x=1080.77, y=50.00, z=479.50], EntityCreeper['Creeper'/288078, l='MpServer', x=1082.46, y=50.00, z=451.20], EntitySheep['Sheep'/232527, l='MpServer', x=1155.35, y=61.00, z=462.52], EntityCreeper['Creeper'/288075, l='MpServer', x=1209.65, y=17.00, z=414.84], EntityBat['Bat'/288084, l='MpServer', x=1079.54, y=26.10, z=512.75], EntityBat['Bat'/288085, l='MpServer', x=1082.36, y=24.29, z=508.26], EntitySheep['Sheep'/232529, l='MpServer', x=1153.45, y=61.00, z=464.59], EntitySquid['Squid'/288208, l='MpServer', x=1170.02, y=58.87, z=409.65], EntitySheep['Sheep'/214, l='MpServer', x=1155.55, y=61.00, z=464.37], EntitySheep['Sheep'/215, l='MpServer', x=1153.61, y=61.00, z=465.49], EntityPig['Pig'/288083, l='MpServer', x=1070.67, y=71.00, z=444.81], EntitySheep['Sheep'/216, l='MpServer', x=1153.45, y=61.00, z=462.60], EntitySheep['Sheep'/217, l='MpServer', x=1155.55, y=61.00, z=465.55], EntityCreeper['Creeper'/288095, l='MpServer', x=1078.50, y=18.00, z=433.50], EntitySkeleton['Skeleton'/288228, l='MpServer', x=1217.50, y=36.00, z=381.27], EntityBat['Bat'/288101, l='MpServer', x=1085.54, y=37.68, z=408.20], EntitySpider['Spider'/288229, l='MpServer', x=1203.50, y=23.00, z=379.50], EntitySkeleton['Skeleton'/288230, l='MpServer', x=1201.27, y=16.00, z=379.49], EntityChicken['Chicken'/288103, l='MpServer', x=1165.55, y=76.00, z=484.79], EntitySheep['Sheep'/19430, l='MpServer', x=1153.56, y=61.00, z=463.70], EntityCreeper['Creeper'/288226, l='MpServer', x=1215.50, y=18.00, z=384.50], EntityCreeper['Creeper'/288227, l='MpServer', x=1219.15, y=36.00, z=380.40], EntitySheep['Sheep'/19432, l='MpServer', x=1154.62, y=61.00, z=464.32], EntitySkeleton['Skeleton'/288238, l='MpServer', x=1199.49, y=16.00, z=378.73], EntitySkeleton['Skeleton'/288107, l='MpServer', x=1092.31, y=15.00, z=440.48], EntityCreeper['Creeper'/288116, l='MpServer', x=1090.50, y=48.00, z=477.50], EntitySkeleton['Skeleton'/288124, l='MpServer', x=1214.50, y=22.00, z=412.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3470865880 bytes (3310 MB) / 5268045824 bytes (5024 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version          | Source                                          | Signature                                |
	|:------ |:------------------- |:---------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2           | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                 | 9.42             | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                 | 8.0.99.99        | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838     | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | lesslag             | 1.0              | minecraft.jar                                   | None                                     |
	| LCHIJA | bibliocraft         | 2.4.5            | BiblioCraft-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | jei                 | 4.15.0.268       | jei_1.12.2-4.15.0.268.jar                       | None                                     |
	| LCHIJA | forestry            | 5.8.1.322        | forestry_1.12.2-5.8.1.322.jar                   | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.2        | buildcraft-all-7.99.24.2.jar                    | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353        | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux        | 2.1.0            | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore            | 4.6.3            | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
	| LCHIJA | cofhworld           | 1.3.1            | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | zerocore            | 1.12.2-0.1.2.8   | zerocore-1.12.2-0.1.2.8.jar                     | None                                     |
	| LCHIJA | bigreactors         | 1.12.2-0.4.5.67  | ExtremeReactors-1.12.2-0.4.5.67.jar             | None                                     |
	| LCHIJA | flansmod            | 5.5.2            | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | flansmodapocalypse  | 1.0              | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| LCHIJA | waila               | 1.8.26           | Hwyla-Mod-1.12.2.jar                            | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.5b7   | JourneyMap-Mod-1.12.2-Unlimited.jar             | None                                     |
	| LCHIJA | mekanism            | 1.12.2-9.8.1.383 | Mekanism-1.12.2-9.8.1.383.jar                   | None                                     |
	| LCHIJA | mekanismgenerators  | 1.12.2-9.8.1.383 | MekanismGenerators-1.12.2-9.8.1.383.jar         | None                                     |
	| LCHIJA | mekanismtools       | 1.12.2-9.8.1.383 | MekanismTools-1.12.2-9.8.1.383.jar              | None                                     |
	| LCHIJA | thermalfoundation   | 2.6.3            | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion    | 5.5.4            | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | omlib               | 3.1.3-246        | omlib-1.12.2-3.1.3-246.jar                      | None                                     |
	| LCHIJA | openmodularturrets  | 3.1.3-355        | openmodularturrets-1.12.2-3.1.3-355.jar         | None                                     |
	| LCHIJA | harvestcraft        | 1.12.2zb         | Pam's+HarvestCraft+1.12.2ze.jar                 | None                                     |
	| LCHIJA | ptrmodellib         | 1.0.4            | PTRLib-1.0.4.jar                                | None                                     |
	| LCHIJA | thermaldynamics     | 2.5.5            | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |

	Loaded coremods (and transformers): 
MekanismCoremod (Mekanism-1.12.2-9.8.1.383.jar)
  mekanism.coremod.KeybindingMigrationHelper
LesslagCorePlugin (Less-Lag-Mod-1.12.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13521 Compatibility Profile Context 24.20.11020.2' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.5.13521 Compatibility Profile Context 24.20.11020.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 2200G with Radeon Vega Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13521 Compatibility Profile Context 24.20.11020.2
	OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Garvey64** [comment]
I dont know if anyone has seen anything like this (did some research, happened a few other times but should've been fixed) so, can you help, or at least point me in the right direction please? thx.

**Comment by mensreaMC** [comment]
If this isn't happening with any other boxes then it's probably an error with that boxes config. Can you paste the contents of the Russian gun box to pastebin and drop the link here? I think something similar happened to me and I might be able to help.

**Comment by Garvey64** [comment]
where can i find said config?

**Comment by mensreaMC** [comment]
yourminecraftdirectory\Flan\machetemancontentpack\boxes

**Comment by Liruxo** [comment]
This is indeed a problem with your content pack. We are unable to provide any support unless you can specify where you got the content pack. Please also make sure you are using the latest version of the content packs and the latest version of FlansMod, all available at https://github.com/FlansMods/FlansMod/releases
