### ISSUE TITLE
com.flansmod.common.guns.EntityAAGun cannot be cast to net.minecraft.entity.EntityLivingBase

### ISSUE THREAD

**Issue by HenkDeKipGaming** [FlansMods/FlansMod#1120]
**To Reproduce**
Steps to reproduce the crash:
1. Log in to my modded server
2. Play for a little while, do nothing in particular
3. Randomly Minecraft crashes, happens when mining / farming, whatever. Seems to be unrelated to what I do
4. Everytime I log into the server, I instantly crash

**Screenshots**
-

**Versions (please complete the following information)**
 - Forge: 1.7.10-Forge10.13.4.1558-1.7.10
 - Flan's Mod: Flans Mod-1.7.10-4.10.0

**Crash Log**
https://gist.github.com/HenkDeKipGaming/11aa3fd9048369097a15946e291c9de8

**Additional context**
I'm using flan packs:
- British Military Pack V1.131
- Modern Warfare-Content Pack-1.7.10-4.10.0
- Simple Parts-Content Pack-1.7.10-4.10.0
- WW2-Content Pack-1.7.10-4.10.0

The modpack works perfectly until I add flans mod. It doesn't only happen to me, my friends also crash.
The weird thing is that the client also crashes if it has flansmod installed while the server does not. Deleting flansmod from the mods folder solved everything.

Also, the server gives this error when I join en crash: https://gist.github.com/HenkDeKipGaming/c8341e7c46e632cb5e1503b04ed51dc2

**Comment by Liruxo** [comment]
We are sorry, but Flans Mod for 1.7.10 is no longer supported

**Comment by HenkDeKipGaming** [comment]
:( This makes me sad, Minecraft 1.7.10 was the absolute best version for mods and modpacks. I loved using it until this bug.
It makes no sense though, everything worked fine for a whole week and than suddenly everything stopped working
