### ISSUE TITLE
Crash when using simple parts content pack and tinker's construct

### ISSUE THREAD

**Issue by HenkDeKipGaming** [FlansMods/FlansMod#1121]
**To Reproduce**
Steps to reproduce the crash:
1. Install Flan's mod, simple parts content pack and tinker's construct
2. Create a crafting station
3. Try to fill the whole crafting station with a material by holding down the left mouse button with 9 of a material and fill it up
4. whoops crash

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 1.12.2-forge1.12.2-14.23.5.2768
 - Flan's Mod: 1.12.2-5.5.2

**Crash Log**
https://pastebin.com/Wa0mVEU6

**Additional context**
Also in the normal crafting table, try creating a redstone block out of 9 redstone. Everything will bug insanely, you can't create the block and when taking out the redstone it will duplicate.
Very strange indeed.
Also made a post of this with tinkers construct https://github.com/SlimeKnights/TinkersConstruct/issues/3935

Without simple parts, everything works perfectly. But, well, without simple parts Flan's mod's just not as fun.

EDIT: happened again without the simple parts content pack: https://pastebin.com/7inBcnAr
This happened while crafting an iron axe, when placing the third iron it crashes

**Comment by Liruxo** [comment]
I am unable to reproduce this issue. Can you please confirm that this still happens in the latest release of FlansMod, available here: https://github.com/FlansMods/FlansMod/releases

**Comment by TwiliDiamondOcelot** [comment]
I've looked though the crash reports, and none of the related code or information is from flans mod save for the info of it being installed, which is the same for all mods.

Looking at the issue he opened for Tinkers' Construct, the team member there stated that flans has, "a broken crafting recipe".

It looks to me as if the team member was to lazy to look into the issue, as the only mods that were shown in the error was Tinkers' and Mantle, both of which are SlimeKnights projects.

**Comment by ChrisLane** [comment]
Closing because of the two responses above and no response from the original.
