### ISSUE TITLE
[1.12.2] Crash after placing a vechicle

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#1125]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (CXLibrary-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 9/3/19 11:14 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:391)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:391)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: flansmod:vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 229502
	Entity Name: T-90MS
	Entity's Exact location: -1395.50, 5.50, -849.50
	Entity's Block location: World: (-1396,5,-850), Chunk: (at 12,0,14 in -88,-54; contains blocks -1408,0,-864 to -1393,255,-849), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/229503, l='New World', x=-1395.50, y=5.50, z=-849.50], EntitySeat['entity.Seat.name'/229504, l='New World', x=-1395.50, y=5.50, z=-849.50], EntityWheel['entity.Wheel.name'/229505, l='New World', x=-1393.91, y=4.88, z=-852.02], EntityWheel['entity.Wheel.name'/229506, l='New World', x=-1397.16, y=4.88, z=-851.97], EntityWheel['entity.Wheel.name'/229507, l='New World', x=-1397.06, y=4.88, z=-845.23], EntityWheel['entity.Wheel.name'/229508, l='New World', x=-1393.81, y=4.88, z=-845.28]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['LucasSport'/1243, l='New World', x=-1395.50, y=4.00, z=-852.86]]
	Chunk stats: ServerChunkCache: 256 Drop: 0
	Level seed: 4127424182164146868
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-1401,4,-852), Chunk: (at 7,0,12 in -88,-54; contains blocks -1408,0,-864 to -1393,255,-849), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513)
	Level time: 3001 game time, 3001 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 49491 (now: false), thunder time: 129681 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1677099000 bytes (1599 MB) / 3161456640 bytes (3015 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2844 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                           | Signature                                |
	|:------ |:-------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2844.jar                    | None                                     |
	| LCHIJA | forge                | 14.23.5.2844      | forge-1.12.2-14.23.5.2844.jar                    | None                                     |
	| LCHIJA | techguns_core        | 1.12.2-1.0        | minecraft.jar                                    | None                                     |
	| LCHIJA | securitycraft        | v1.8.12           | [1.12.2]+SecurityCraft+v1.8.12.jar               | None                                     |
	| LCHIJA | cxlibrary            | 1.6.1             | CXLibrary-1.12.2.jar                             | None                                     |
	| LCHIJA | advinv               | 1.4.2             | advInv-1.12.1-1.4.2.jar                          | None                                     |
	| LCHIJA | cfm                  | 6.3.0             | cfm-6.3.0-mc1.12.2.jar                           | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                        | None                                     |
	| LCHIJA | chisel               | MC1.12.2-0.2.0.31 | Chisel-Mod-1.12.2.jar                            | None                                     |
	| LCHIJA | subcommonlib         | 1.2.0.1           | subcommonlib-sublib-1.12.2-1.2.0.4.jar           | None                                     |
	| LCHIJA | rpginventory         | 1.12.2            | Rpg-Inventory-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | beastmaster          | $version          | Class-Armor-Mod-Beast-Master-1.12.2.jar          | None                                     |
	| LCHIJA | bma_addon            | 1.11.2 4.0.3.0    | Class-Armor-Mod-Berserker-Mage-Archer-1.12.2.jar | None                                     |
	| LCHIJA | umbralux             | 1.12.2            | Class-Armor-Mod-Necromancer-Paladin-1.12.2.jar   | None                                     |
	| LCHIJA | classiccombat        | 1.0.1             | Classic-Combat-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.357         | CodeChickenLib-1.12.2-3.2.3.357-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore             | 4.6.2             | CoFHCore-1.12.2.jar                              | None                                     |
	| LCHIJA | customspawner        | 3.11.4            | CustomMobSpawner-3.11.4.jar                      | None                                     |
	| LCHIJA | customnpcs           | 1.12              | CustomNPCs_1.12.2-30May19snapshot.jar            | None                                     |
	| LCHIJA | cyclopscore          | 1.5.0             | CyclopsCore-1.12.2-1.5.0.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | everlastingabilities | 1.5.1             | Everlasting Abilities Mod 1.12.2.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | flansmod             | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                      | None                                     |
	| LCHIJA | flansmodapocalypse   | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                      | None                                     |
	| LCHIJA | grapplemod           | 1.12.2-v11.1      | grapplemod-v11.1-1.12.2.jar                      | None                                     |
	| LCHIJA | ironbackpacks        | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                | None                                     |
	| LCHIJA | jei                  | 4.15.0.287        | jei_1.12.2-4.15.0.287.jar                        | None                                     |
	| LCHIJA | kaishiweapons        | v2018.01          | Kaishis-Weapon-Pack-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | levelup2             | ${version}        | Level-Up-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | nei                  | 2.4.3             | NotEnoughItems-1.12.2-2.4.3.245-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | reforged             | 0.7.5             | Reforged-Mod-1.12.jar                            | None                                     |
	| LCHIJA | somanyenchantments   | 0.4.4             | So+Many+Enchantments+V0.4.4.jar                  | None                                     |
	| LCHIJA | techguns             | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.1.jar               | None                                     |
	| LCHIJA | thedragonlib         | 1.12.2-5.3.0      | thedragonlib-1.12.2-5.3.0.jar                    | None                                     |
	| LCHIJA | trashslot            | 8.4.10            | TrashSlot_1.12.2-8.4.10.jar                      | None                                     |
	| LCHIJA | variedcommodities    | 1.12.2            | VariedCommodities_1.12.2(15may18.jar             | None                                     |

	Loaded coremods (and transformers): 
CXLibraryCore (CXLibrary-1.12.2.jar)
  cubex2.cxlibrary.CoreModTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['LucasSport'/1243, l='New World', x=-1395.50, y=4.00, z=-852.86]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Liruxo** [comment]
Please try using the latest FlansMod version, available here: https://github.com/FlansMods/FlansMod/releases
