### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheRob174** [FlansMods/FlansMod#1129]
My minecraft crashed and it was because of Flan's Mod Apocalypse

Here's the crash report: https://paste.dimdev.org/veqakecaba.mccrash

**Comment by Liruxo** [comment]
Please use the Crash Issue template. Filling out that form massively simplifies working on your problem for every involved party.
Anyways, i am able to see that you are using an outdated version of FlansMod. Please download the newest release here: https://github.com/FlansMods/FlansMod/releases

**Comment by TheRob174** [comment]
The issue was fixed by updating to the newest release of flans mod, thank you for the help!
