### ISSUE TITLE
Tunnel Bore Crash

### ISSUE THREAD

**Issue by siborg71** [FlansMods/FlansMod#1132]
Crafted the tunnel bore vehicle, but it crashes whenever I try to enter and control it. I've tried switching from single player to multiplayer (by opening game to LAN), but same error occurs. Also, the textures on the vehicle are missing (just getting colored blocks).

Here's one of my error logs:

---- Minecraft Crash Report ----
// Don't do that.

Time: 9/22/19 12:33 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at com.flansmod.common.driveables.EntityDriveable.func_70071_h_(EntityDriveable.java:966)
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:291)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.flansmod.common.driveables.EntityDriveable.func_70071_h_(EntityDriveable.java:966)
	at com.flansmod.common.driveables.EntityVehicle.func_70071_h_(EntityVehicle.java:291)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: flansmod:vehicle (com.flansmod.common.driveables.EntityVehicle)
	Entity ID: 469
	Entity Name: Tunnel Bore
	Entity's Exact location: -259.50, 96.50, 252.50
	Entity's Block location: World: (-260,96,252), Chunk: (at 12,6,12 in -17,15; contains blocks -272,0,240 to -257,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/470, l='MpServer', x=-260.43, y=97.75, z=252.59], EntityWheel['entity.Wheel.name'/471, l='MpServer', x=-258.19, y=96.00, z=253.13], EntityWheel['entity.Wheel.name'/472, l='MpServer', x=-258.32, y=96.00, z=251.64], EntityWheel['entity.Wheel.name'/473, l='MpServer', x=-260.81, y=96.00, z=251.87], EntityWheel['entity.Wheel.name'/474, l='MpServer', x=-260.68, y=96.00, z=253.36]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['siborg71'/253, l='MpServer', x=-258.78, y=96.00, z=253.31]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 06 - lostcities, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-208,64,256), Chunk: (at 0,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1172503 game time, 1440993 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 151 total; [EntityCow['Cow'/23, l='MpServer', x=-336.51, y=101.00, z=181.78], EntityPlayerSP['siborg71'/253, l='MpServer', x=-258.78, y=96.00, z=253.31], EntityZombie['Zombie'/32, l='MpServer', x=-338.51, y=60.00, z=318.19], EntityZombie['Zombie'/33, l='MpServer', x=-337.51, y=60.00, z=316.73], EntityChicken['Chicken'/35, l='MpServer', x=-338.44, y=89.00, z=304.88], EntitySpider['Spider'/44, l='MpServer', x=-328.28, y=78.00, z=178.70], EntityCreeper['Creeper'/46, l='MpServer', x=-332.62, y=72.00, z=314.96], EntitySpider['Spider'/47, l='MpServer', x=-329.10, y=72.00, z=314.06], EntityPig['Pig'/48, l='MpServer', x=-331.56, y=78.00, z=332.25], EntityChicken['Chicken'/52, l='MpServer', x=-299.78, y=78.00, z=192.51], EntityChicken['Chicken'/53, l='MpServer', x=-317.17, y=79.00, z=203.50], EntityChicken['Chicken'/54, l='MpServer', x=-307.03, y=79.00, z=205.82], EntityItem['item.item.egg'/55, l='MpServer', x=-310.47, y=79.00, z=203.43], EntityChicken['Chicken'/56, l='MpServer', x=-309.30, y=79.00, z=202.89], EntitySkeleton['Skeleton'/57, l='MpServer', x=-309.47, y=79.00, z=234.78], EntityBat['Bat'/58, l='MpServer', x=-294.88, y=44.92, z=287.12], EntityZombie['Zombie'/59, l='MpServer', x=-314.24, y=58.00, z=291.66], EntitySkeleton['Skeleton'/60, l='MpServer', x=-313.53, y=46.00, z=310.25], EntityZombie['Zombie'/61, l='MpServer', x=-317.19, y=57.00, z=305.48], EntityZombie['Zombie'/62, l='MpServer', x=-315.50, y=42.00, z=331.50], EntitySquid['Squid'/63, l='MpServer', x=-297.98, y=58.00, z=197.40], EntitySquid['Squid'/64, l='MpServer', x=-300.04, y=59.17, z=198.06], EntityChicken['Chicken'/65, l='MpServer', x=-302.21, y=107.00, z=282.55], EntityChicken['Chicken'/66, l='MpServer', x=-298.15, y=109.00, z=274.74], EntityItem['item.item.egg'/67, l='MpServer', x=-298.14, y=109.00, z=275.47], EntityBat['Bat'/69, l='MpServer', x=-274.31, y=39.00, z=234.70], EntityCreeper['Creeper'/70, l='MpServer', x=-279.50, y=84.00, z=227.30], EntityCreeper['Creeper'/71, l='MpServer', x=-274.82, y=84.00, z=233.13], EntityCreeper['Creeper'/72, l='MpServer', x=-275.60, y=84.00, z=230.45], EntityZombie['Zombie'/73, l='MpServer', x=-279.56, y=90.00, z=233.25], EntityZombie['Zombie'/74, l='MpServer', x=-276.50, y=90.00, z=230.50], EntityZombie['Zombie'/75, l='MpServer', x=-278.50, y=90.00, z=238.24], EntityChicken['Chicken'/76, l='MpServer', x=-273.69, y=83.00, z=271.77], EntityChicken['Chicken'/77, l='MpServer', x=-273.80, y=83.00, z=270.20], EntityChicken['Chicken'/78, l='MpServer', x=-273.80, y=83.00, z=267.20], EntityChicken['Chicken'/79, l='MpServer', x=-273.80, y=83.00, z=267.67], EntityChicken['Chicken'/80, l='MpServer', x=-273.27, y=83.00, z=267.26], EntityChicken['Chicken'/81, l='MpServer', x=-273.35, y=83.00, z=267.96], EntityItem['item.item.egg'/82, l='MpServer', x=-273.88, y=83.00, z=267.58], EntityItem['item.item.egg'/83, l='MpServer', x=-273.88, y=83.00, z=271.88], EntityItem['item.item.egg'/84, l='MpServer', x=-272.45, y=83.00, z=270.40], EntityItem['item.item.egg'/85, l='MpServer', x=-273.88, y=83.00, z=270.04], EntityMinecartEmpty['entity.MinecartRideable.name'/86, l='MpServer', x=-273.49, y=81.06, z=263.50], EntityBat['Bat'/87, l='MpServer', x=-273.46, y=12.94, z=281.30], EntityCreeper['Creeper'/88, l='MpServer', x=-280.50, y=23.00, z=274.50], EntityZombie['Zombie'/89, l='MpServer', x=-282.67, y=104.00, z=286.52], EntityCreeper['Creeper'/90, l='MpServer', x=-284.50, y=78.00, z=309.50], EntitySpider['Spider'/91, l='MpServer', x=-279.50, y=78.00, z=305.50], EntityChicken['Chicken'/92, l='MpServer', x=-286.99, y=101.00, z=307.70], EntityChicken['Chicken'/93, l='MpServer', x=-279.88, y=101.00, z=309.51], EntityChicken['Chicken'/94, l='MpServer', x=-281.83, y=101.00, z=313.43], EntityChicken['Chicken'/95, l='MpServer', x=-281.58, y=101.00, z=311.85], EntityItem['item.item.egg'/97, l='MpServer', x=-282.46, y=101.00, z=314.28], EntityItem['item.item.egg'/98, l='MpServer', x=-280.77, y=101.00, z=309.50], EntityBat['Bat'/99, l='MpServer', x=-292.98, y=50.51, z=322.53], EntityChicken['Chicken'/117, l='MpServer', x=-269.19, y=83.00, z=271.70], EntityChicken['Chicken'/118, l='MpServer', x=-269.68, y=83.00, z=270.78], EntityChicken['Chicken'/119, l='MpServer', x=-268.20, y=83.00, z=271.33], EntityChicken['Chicken'/120, l='MpServer', x=-268.20, y=83.00, z=270.81], EntityChicken['Chicken'/121, l='MpServer', x=-269.19, y=83.00, z=267.20], EntityChicken['Chicken'/122, l='MpServer', x=-268.55, y=83.00, z=268.64], EntityChicken['Chicken'/123, l='MpServer', x=-268.71, y=83.00, z=271.36], EntityChicken['Chicken'/124, l='MpServer', x=-270.15, y=83.00, z=267.20], EntityChicken['Chicken'/125, l='MpServer', x=-270.29, y=83.00, z=268.88], EntityChicken['Chicken'/126, l='MpServer', x=-271.16, y=83.00, z=267.70], EntityChicken['Chicken'/127, l='MpServer', x=-269.70, y=83.00, z=267.20], EntityChicken['Chicken'/128, l='MpServer', x=-268.67, y=83.00, z=271.80], EntityChicken['Chicken'/129, l='MpServer', x=-269.45, y=83.00, z=270.03], EntityChicken['Chicken'/130, l='MpServer', x=-270.43, y=83.00, z=270.83], EntityChicken['Chicken'/131, l='MpServer', x=-268.76, y=83.00, z=267.64], EntityChicken['Chicken'/132, l='MpServer', x=-268.20, y=83.00, z=267.20], EntityChicken['Chicken'/133, l='MpServer', x=-268.66, y=83.00, z=270.81], EntityChicken['Chicken'/134, l='MpServer', x=-268.20, y=83.00, z=271.80], EntityChicken['Chicken'/135, l='MpServer', x=-268.20, y=83.00, z=267.65], EntityChicken['Chicken'/136, l='MpServer', x=-269.81, y=83.00, z=269.40], EntityChicken['Chicken'/137, l='MpServer', x=-268.20, y=83.00, z=269.21], EntityChicken['Chicken'/138, l='MpServer', x=-269.19, y=83.00, z=270.67], EntityChicken['Chicken'/139, l='MpServer', x=-268.20, y=83.00, z=268.11], EntityChicken['Chicken'/140, l='MpServer', x=-269.02, y=83.00, z=268.79], EntityChicken['Chicken'/141, l='MpServer', x=-270.90, y=83.00, z=270.18], EntityChicken['Chicken'/142, l='MpServer', x=-269.16, y=83.00, z=271.27], EntityChicken['Chicken'/143, l='MpServer', x=-270.30, y=83.00, z=269.79], EntityChicken['Chicken'/144, l='MpServer', x=-268.61, y=83.00, z=268.08], EntityChicken['Chicken'/145, l='MpServer', x=-271.94, y=83.00, z=270.46], EntityChicken['Chicken'/146, l='MpServer', x=-268.20, y=83.00, z=270.37], EntityItem['item.item.egg'/147, l='MpServer', x=-268.13, y=83.00, z=271.88], EntityChicken['Chicken'/148, l='MpServer', x=-270.20, y=83.00, z=271.34], EntityItem['item.item.egg'/149, l='MpServer', x=-269.44, y=83.00, z=271.88], EntityItem['item.item.egg'/150, l='MpServer', x=-271.05, y=83.00, z=268.29], EntityItem['item.item.egg'/151, l='MpServer', x=-269.17, y=83.00, z=267.68], EntityItem['item.item.egg'/152, l='MpServer', x=-268.38, y=83.00, z=270.00], EntityItem['item.item.egg'/154, l='MpServer', x=-268.13, y=83.00, z=268.56], EntityItem['item.item.egg'/155, l='MpServer', x=-271.37, y=83.00, z=269.87], EntityItem['item.item.egg'/156, l='MpServer', x=-270.36, y=83.00, z=269.94], EntityItem['item.item.egg'/157, l='MpServer', x=-270.86, y=83.00, z=271.88], EntityZombie['Zombie'/158, l='MpServer', x=-259.50, y=37.00, z=282.50], EntityZombie['Zombie'/168, l='MpServer', x=-247.50, y=55.00, z=223.50], EntityZombie['Zombie'/169, l='MpServer', x=-249.50, y=55.00, z=229.26], EntityCreeper['Creeper'/170, l='MpServer', x=-247.50, y=55.00, z=229.50], EntitySkeleton['Skeleton'/171, l='MpServer', x=-254.50, y=35.00, z=262.50], EntityBat['Bat'/172, l='MpServer', x=-240.33, y=36.10, z=260.25], EntitySkeleton['Skeleton'/173, l='MpServer', x=-248.50, y=12.00, z=281.50], EntityCreeper['Creeper'/174, l='MpServer', x=-254.50, y=37.00, z=275.50], EntityBat['Bat'/175, l='MpServer', x=-251.31, y=55.83, z=274.25], EntityBat['Bat'/176, l='MpServer', x=-251.25, y=56.10, z=277.75], EntityZombie['Zombie'/177, l='MpServer', x=-241.50, y=22.00, z=296.50], EntityChicken['Chicken'/186, l='MpServer', x=-229.60, y=91.00, z=216.14], EntityItem['item.item.egg'/187, l='MpServer', x=-229.88, y=91.00, z=216.20], EntityBat['Bat'/188, l='MpServer', x=-226.54, y=62.10, z=280.17], EntityCreeper['Creeper'/189, l='MpServer', x=-227.50, y=60.00, z=283.50], EntitySkeleton['Skeleton'/190, l='MpServer', x=-232.50, y=66.00, z=283.50], EntityItem['item.item.egg'/446, l='MpServer', x=-306.84, y=79.00, z=205.13], EntitySkeleton['Skeleton'/191, l='MpServer', x=-227.50, y=66.00, z=278.50], EntitySkeleton['Skeleton'/192, l='MpServer', x=-225.72, y=66.00, z=286.48], EntityBat['Bat'/193, l='MpServer', x=-232.52, y=60.86, z=321.86], EntityBat['Bat'/194, l='MpServer', x=-228.77, y=60.03, z=325.81], EntityCreeper['Creeper'/197, l='MpServer', x=-210.50, y=15.00, z=180.50], EntityZombie['Zombie'/198, l='MpServer', x=-208.50, y=16.00, z=183.50], EntityChicken['Chicken'/199, l='MpServer', x=-212.77, y=91.00, z=201.50], EntityItem['item.item.egg'/200, l='MpServer', x=-213.61, y=91.00, z=202.19], EntityChicken['Chicken'/201, l='MpServer', x=-212.82, y=92.00, z=215.44], EntityChicken['Chicken'/202, l='MpServer', x=-217.20, y=77.00, z=243.20], EntityItem['item.item.egg'/203, l='MpServer', x=-217.13, y=77.00, z=243.13], EntityHorse['Horse'/204, l='MpServer', x=-220.90, y=78.00, z=276.84], EntityCreeper['Creeper'/205, l='MpServer', x=-210.50, y=52.00, z=293.50], EntityChicken['Chicken'/206, l='MpServer', x=-220.90, y=78.00, z=302.38], EntityItem['item.item.egg'/207, l='MpServer', x=-221.41, y=78.00, z=302.60], EntityChicken['Chicken'/212, l='MpServer', x=-200.09, y=88.00, z=198.32], EntityItem['item.item.egg'/213, l='MpServer', x=-200.34, y=88.00, z=198.58], EntityVehicle['Tunnel Bore'/469, l='MpServer', x=-259.50, y=96.50, z=252.50], EntityCreeper['Creeper'/214, l='MpServer', x=-203.81, y=22.00, z=269.48], EntitySeat['entity.Seat.name'/470, l='MpServer', x=-260.43, y=97.75, z=252.59], EntitySpider['Spider'/215, l='MpServer', x=-204.30, y=23.00, z=274.69], EntityWheel['entity.Wheel.name'/471, l='MpServer', x=-258.19, y=96.00, z=253.13], EntityBat['Bat'/216, l='MpServer', x=-193.45, y=25.81, z=274.74], EntityWheel['entity.Wheel.name'/472, l='MpServer', x=-258.32, y=96.00, z=251.64], EntitySkeleton['Skeleton'/217, l='MpServer', x=-193.51, y=60.01, z=283.56], EntityWheel['entity.Wheel.name'/473, l='MpServer', x=-260.81, y=96.00, z=251.87], EntityCreeper['Creeper'/218, l='MpServer', x=-200.48, y=60.00, z=274.80], EntityWheel['entity.Wheel.name'/474, l='MpServer', x=-260.68, y=96.00, z=253.36], EntityZombie['Zombie'/219, l='MpServer', x=-193.30, y=60.00, z=281.06], EntityCreeper['Creeper'/220, l='MpServer', x=-196.42, y=60.00, z=283.17], EntityCreeper['Creeper'/221, l='MpServer', x=-194.10, y=61.00, z=282.75], EntitySkeleton['Skeleton'/222, l='MpServer', x=-199.22, y=66.00, z=284.31], EntitySkeleton['Skeleton'/223, l='MpServer', x=-198.26, y=66.00, z=286.49], EntitySkeleton['Skeleton'/224, l='MpServer', x=-201.50, y=25.00, z=302.50], EntityBat['Bat'/225, l='MpServer', x=-196.21, y=60.86, z=316.70], EntityCamera['unknown'/481, l='MpServer', x=-259.50, y=96.51, z=252.50], EntitySpider['Spider'/226, l='MpServer', x=-201.50, y=101.00, z=312.50], EntitySpider['Spider'/227, l='MpServer', x=-204.50, y=101.00, z=314.50], EntityCreeper['Creeper'/231, l='MpServer', x=-195.21, y=66.00, z=273.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 972308088 bytes (927 MB) / 1946157056 bytes (1856 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                        | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2846.jar                 | None                                     |
	| LCHIJA | forge               | 14.23.5.2846 | forge-1.12.2-14.23.5.2846.jar                 | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | craftablegunpowder  | 1.12.2       | CraftableGunpowder.jar                        | None                                     |
	| LCHIJA | flansmod            | 5.6          | Flan.s.Mod-1.12.2-5.6.jar                     | None                                     |
	| LCHIJA | jei                 | 4.15.0.289   | jei_1.12.2-4.15.0.289.jar                     | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.5 | journeymap-1.12.2-5.5.5.jar                   | None                                     |
	| LCHIJA | lostcities          | 2.0.20       | lostcities-1.12-2.0.20.jar                    | None                                     |
	| LCHIJA | recipehandler       | 0.13         | NoMoreRecipeConflict-0.13(1.12.2).jar         | None                                     |
	| LCHIJA | nei                 | 2.4.2        | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | veinminer           | 0.38.2       | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2       | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13547 Compatibility Profile Context 25.20.15031.1000' Renderer: 'Radeon (TM) RX 480 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2846
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 480 Graphics GL version 4.6.13547 Compatibility Profile Context 25.20.15031.1000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

**Comment by ChrisLane** [comment]
Please use the issue templates in future.

Could you try the latest version from [here](https://github.com/FlansMods/FlansMod/releases) please and let me know if that fixes the crash?
Is this only an issue with the tunnel bore? The vehicle is incomplete and doesn't have a skin yet, it isn't provided in official releases of the content packs.
