### ISSUE TITLE
Console spam in server

### ISSUE THREAD

**Issue by SmokeyBBQx** [FlansMods/FlansMod#1139]
**Describe the bug**
Hello, I'm using the latest beta of flans mod, with the latest modernwarfare and the latest simple parts. I noticed that my console gets spammed with this error: [Server thread/ERROR] [flansmod]: Driveable already had a seat in place
The server doesn't crash, and it seems fine I think. But sometimes everyone gets kicked for reason: "Timed Out" and it may be related to this error. 
**Versions**
Forge: forge-1.12.2-14.23.5.2814-universal.jar
Flan's Mod: latest
ModernWarfare: latest
SimpleParts: latest
So thank you in advance if you try to help me :)

**Comment by Liruxo** [comment]
First, please do not use "latest" as version description. Please use the actual version string defined at the download page and in the name of the .jar-file (e.g. v5.6-beta.6)
Second, i find it highly unlikely that the "Timed out" is in any way related to the FlansMod Warning Message (It is called a "ERROR" but its more like a warning. Although its occurring multiple times, nothing mayor should break). But if you are able to reproduce this "Timed Out"-Issue with only FlansMod v5.6-beta.6, please open another issue for it

**Comment by OverKnown1** [comment]
Hey I know its been a while from when you posted this but could you tell me how to install Flan on a server?
