### ISSUE TITLE
No sound from guns, guns not "firing" on server.

### ISSUE THREAD

**Issue by DocSmitty** [FlansMods/FlansMod#1141]
Hello, 
I recently started a Flans mod server only to find that the guns in the server would not work, as in I could pull the item to my inventory, equip it, and load a magazine. The issue is when I went to fire it, the gun recoiled, no sound came from it and no bullets came from the gun. The gun was still at a full magazine. Hoping for a easy mistake to correct or fix!

Minecraft Version: 1.12.2
Forge: 14.23.5.2838
Flans Mod: 5.5.2

Thanks,
DocSmitty

**Comment by Liruxo** [comment]
Please try to use the latest version, available at https://github.com/FlansMods/FlansMod/releases

**Comment by FryCakes** [comment]
> Please try to use the latest version, available at https://github.com/FlansMods/FlansMod/releases

I am getting a very similar issue with the latest versions. The guns load, they fire, but if you shoot at the sky or far away, they don't make noise. Then when you run out of ammo, they make a reload animation but do not shoot or load ammo.

**Comment by TSH4RP** [comment]
Yeah im having this issue as well and i loaded in all the new Flan mods but it still doesnt work
