### ISSUE TITLE
Crash when holding some guns

### ISSUE THREAD

**Issue by Azuuno** [FlansMods/FlansMod#1143]
**To Reproduce**
Steps to reproduce the crash:
1. Take a gun (like the Glock or the Deagle)
2. Hold it in your hand
3. -Game Crash-

**Screenshots**
I can't, because I'm crashing x).

**Versions (please complete the following information)**
 - Forge: 1.12.2-2838
 - Flan's Mod: 1.12.2-5.5.2

**Crash Log**
The file is attached below.
[2019-10-27-2.log](https://github.com/FlansMods/FlansMod/files/3776477/2019-10-27-2.log)

**Additional context**
I've tried to reinstall Flans and the Modern Weapons Pack , but I'm crashing too.

**Comment by ChrisLane** [comment]
Please try the latest version from here: https://github.com/FlansMods/FlansMod/releases

**Comment by Azuuno** [comment]
I'll try that, thanks. If the crashes are here, I will send another crash report ^^.

**Comment by Azuuno** [comment]
I doesn't work... my crash report :
[crash-2019-10-28_00.07.11-client.txt](https://github.com/FlansMods/FlansMod/files/3776560/crash-2019-10-28_00.07.11-client.txt)

**Comment by ChrisLane** [comment]
It looks like your system is giving a non-standard code for your sneak keybinding.
I believe that I've fixed the crash by using Minecraft's built-in keybinding functions. I'll link a new mod jar for you to test soon.

**Comment by ChrisLane** [comment]
Please unzip the following file and see if the version inside fixes the crash.
[Flan's Mod-1.12.2-5.6.0-beta.6.jar.zip](https://github.com/FlansMods/FlansMod/files/3780674/Flan.s.Mod-1.12.2-5.6.0-beta.6.jar.zip)

**Comment by Azuuno** [comment]
Hello Chris, two hours ago, I changed my sneak keybinding, and the bug was fixed ^^'.
Thanks a lot for your help, I will take this Flans Mod !
It's a very nice mod you made :p !
