### ISSUE TITLE
Flashlight Lighting Issues

### ISSUE THREAD

**Issue by TwiliDiamondOcelot** [FlansMods/FlansMod#1146]
**Describe the bug**
With any of the light sources (flashlights) in flans mod, only one block at a time is lit up and stays lit up when you move away. Additionally, when you break or place a block next to the single lit up block, then the light spreads like normal, even with no flans light source. This happens with all flashlights: pistol flashlight attachment, flashlight attachment, and the mecha lantern and illuminator.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a gun or pistol with a flashlight attachment or a mecha with either the lantern or illuminatot.
2. With the guns, point at any blocks you want, and with the mecha just add the upgrade and move around. (It's easier to see at low light levels)
3. Notice the weird lighting, it only lights up blocks one at a time.
4. For weird effect, break or place any block next to the lit up block(s). Acts as if light source is there, and effect stays until exiting and reentering the world.

**Expected behaviour**
Light sources should work as normal like in previous versions before 1.12, or like optifine's real-time lighting for held light emitting items.

**Screenshots**
![lighting-issues-flansmod-1 12 2-optimized](https://user-images.githubusercontent.com/53383686/68088166-4fa7f680-fe2a-11e9-8e29-97448ae07e6f.gif)

**Versions (please complete the following information)**
 - Forge: 14.23.5.2837
 - Flan's Mod: All 1.12 versions (5.5.1 -> 5.6-beta.6)

**Comment by ChrisLane** [comment]
The fix for this is now released in v5.6-beta.7
