### ISSUE TITLE
Crash on shift-clicking gun into modification table

### ISSUE THREAD

**Issue by Sorathesec** [FlansMods/FlansMod#1149]
**To Reproduce**
Steps to reproduce the crash:
1. Craft/spawn any gun
2. Shift left-click the gun into the table

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 14.23.5.2847
 - Flan's Mod: 5.5.2

**Crash Log**
https://paste.dimdev.org/uvicobunij.mccrash

**Comment by Liruxo** [comment]
Please try to use the latest version, available at https://github.com/FlansMods/FlansMod/releases
