### ISSUE TITLE
Есть ли люди, которые могут помочь со стрельбой flans mod.

### ISSUE THREAD

**Issue by SkyMK** [FlansMods/FlansMod#1150]
Хочу переписать flans mod по исходникам, а точнее стрельбу, что бы она было по модельке, но не знаю как.

**Comment by ChrisLane** [comment]
I'm sorry but I don't know what you're asking.

**Comment by SkyMK** [comment]
ChrisLane, стандартная стрельба там на перёд пульками если не ошибаюсь. Вот я хочу её переписать, вроде есть откуда списать( с модов других серверов, но они не дописаны и я не знаю что делать) Вот решил спросить мб кто знает и поможет

**Comment by SkyMK** [comment]
Я не знаю как объяснить, проще показать

**Comment by SkyMK** [comment]
![2019-11-15_20 08 17](https://user-images.githubusercontent.com/57638360/68961577-c4444300-07e3-11ea-8da4-4507a94f6c52.png)
Вот что-то типо этого, но дамаг не прописан, а как прописать я не знаю)

**Comment by ChrisLane** [comment]
I'm sorry, I still can't understand what you're asking. Are you trying to modify the mod?
