### ISSUE TITLE
Minecraft won't start with Flan's mod 5.5.2 minecraft 1.12.2

### ISSUE THREAD

**Issue by BinaryVigilante** [FlansMods/FlansMod#1151]
Hello. After installing Flans mod Minecraft won't launch. It gives the error shown in the image.
![Screenshot_2019-11-18_02-49-59](https://user-images.githubusercontent.com/24778415/69018925-c6a6c880-09ae-11ea-8f4f-f150c20b0c76.png)

**To Reproduce**
Steps to reproduce the crash:
1. Install the mod
**Versions (please complete the following information)**
 - Forge: 2816
 - Flan's Mod: 5.5.2

Crashlog: https://paste.ubuntu.com/p/WVTZXbQhY5/

Kind regards!

**Comment by Liruxo** [comment]
Please try to use the latest FlansMod version for 1.12.2, available at https://github.com/FlansMods/FlansMod/releases

**Comment by BinaryVigilante** [comment]
@Liruxo That worked! Thank you so much! So sorry for the inconvinence, I didn't see this beta nor did I know you guys had a github :) Amazing mod btw one of my favorite!

Have a great day!
Kind regards!
