### ISSUE TITLE
Pink German helmet 

### ISSUE THREAD

**Issue by schollnw29** [FlansMods/FlansMod#1153]
The texture for the grey German helmet appears to be missing 

1. Equip the grey German helmet

![2019-11-23_20 20 00](https://user-images.githubusercontent.com/15615128/69488406-b23f5180-0e2e-11ea-92f8-90fe6d1cc2ba.png)
![2019-11-23_20 20 01](https://user-images.githubusercontent.com/15615128/69488407-b4091500-0e2e-11ea-95ee-22e0c06b48f3.png)

Versions
 - Forge: 14.23.5.2847
 - Flan's Mod: 5.5.2

**Comment by Liruxo** [comment]
Please try to use the latest FlansMod version for 1.12.2, available at https://github.com/FlansMods/FlansMod/releases
