### ISSUE TITLE
Simple Parts Pack Crafting Glitch

### ISSUE THREAD

**Issue by Thezapman1** [FlansMods/FlansMod#1156]
Flans Mod +
Simple Parts-Content Pack-1.12.2-5.5.2

Random Recipies will bug out and randomly switch between other recipes, not display one at all, delete or duplicate your items and overall cause a big fuss whilst trying to craft.
This happens while I have a fresh Minecraft client running Forge 1.12.2...2847 with Flans and the Simple parts content pack. Please help me out to see if there are any workarounds, would be much appreciated.

**Comment by Thezapman1** [comment]
For example if you try to craft a wooden chest with 8 pieces of wood chances are the result won't be displayed.

*Update - Dragging and dropping each item slowly is less likely to affect the crafting bug, drag crafting with right-click triggers the bug more likely when dragging more than a few items:

**Comment by Liruxo** [comment]
Please try to use the latest FlansMod and content packs for 1.12.2, available at https://github.com/FlansMods/FlansMod/releases

**Comment by Thezapman1** [comment]
Sounds good I’ll give it a try, thanks for replying I genuinely appreciate it.
