### ISSUE TITLE
1.7.10 - No more entity indicies left

### ISSUE THREAD

**Issue by NuclearAtoms** [FlansMods/FlansMod#1158]
In the middle of loading, Minecraft crashes and gives me this report : https://gist.github.com/NuclearAtoms/4337e1fa84e3f5c0d948f9f247c6720c

I've also used this with a later version and it still crashes.

 - Forge: 1.7.10-Forge10.13.4.1614-1.7.10
 - Flan's Mod: Flans Mod-1.7.10-4.9.0

**Comment by ChrisLane** [comment]
Sorry, we only support versions of the mod for Minecraft 1.12.2

**Comment by NuclearAtoms** [comment]
Well, that stings. Where can I go for older?

**Comment by NuclearAtoms** [comment]
Bro, atleast tell me how to fix it. Where else would I go for help!?

**Comment by NuclearAtoms** [comment]
CAN I GET AN ANSWER!? HELLO!?!?

**Comment by NuclearAtoms** [comment]
Seriously, I know that this is closed, but I need an answer.

**Comment by NuclearAtoms** [comment]
Seriously, I know that this is closed, but I need an answer.

**Comment by ChrisLane** [comment]
@NuclearAtoms Patience does not seem to be a trait that you posses, nevertheless, you can find details of Flans Mod+ at https://discord.gg/FYYyysq
