### ISSUE TITLE
Crash ExtraPlanet ExtraPlanets-1.12.2-0.6.0.jar With Flan's Mod Flan's Mod-1.12.2-5.5.1

### ISSUE THREAD

**Issue by Daltoro** [FlansMods/FlansMod#1163]
Hey !
I have a little Issue with Flan's mod and ExtraPlanet, when i install ExtraPlanet, my game just crash on loading :
Crash Reports :
https://gist.github.com/Daltoro/abd168bed068b50a692de9519455f998

It's an incompatibility ? or i'm just idiot ? x)
Thank you in advance ! :)

**Comment by ChrisLane** [comment]
You have an old version of the mod. Grab more recent files from here: https://github.com/FlansMods/FlansMod/releases
