### ISSUE TITLE
How to charge on electric engines

### ISSUE THREAD

**Issue by ym1025** [FlansMods/FlansMod#1166]
as above.

**Comment by Liruxo** [comment]
I am sorry, but i am unable to help. Please specify a FlansMod version, the installed ContentPacks and please provide a more detailed explanation of what you are trying to achieve (Examples are always great)

**Comment by ym1025** [comment]
Flan's mod:5.6 beta 6
content pack:all on the release page

**Comment by TwiliDiamondOcelot** [comment]
I was confused about this a while ago, but the electric engines are useless with only Flans mod; they are charged with RF, which is added by other mods. Such as EnderIO.

**Comment by CSdiscoveries** [comment]
I'd like to reopen this, as I have not been able to find out specifically how to add RF to vehicles. Putting a battery from some other mod into the fuel tank slot does not work, and I am not sure how else to go about powering the vehicle in any way other than that.
