### ISSUE TITLE
Vehicles cannot fire at all despite newest version

### ISSUE THREAD

**Issue by AdinaThePotato1** [FlansMods/FlansMod#1168]
I have ran into a bug with the flan's mod, more specifically the vehicle part of the content pack addons such as modern warfare vehicles or WW2 content pack. I am unable to fire the secondary machine gun whatsoever despite installing the latest version of flans mod, changing controls mode and I also suffer issues with guns like the STG44 and FG42 having missing parts of their textures, so it looks like there is air inbetween. The mods I am running are listed below. 

![image below](https://user-images.githubusercontent.com/60409672/73308940-95a20a00-4221-11ea-9868-bf7b3a3a6070.PNG)

I would be very thankful if someone could help me resolve this issue, and I'm unsure if another mod is conflicting with the original one.

**Comment by AdinaThePotato1** [comment]
PS : I also have issues with placing down mounted guns with bipods, I continue to get an "unknown error" and they do not place consistently.

**Comment by Liruxo** [comment]
It seems you are using an outdated version of FlansMod. Please head over to https://github.com/FlansMods/FlansMod/releases and try to use the latest Mod and Content Pack(s)

**Comment by AdinaThePotato1** [comment]
I still have an issue with mounted guns, they continue to cause crashes and unknown errors, and sometimes I cannot leave them.

**Comment by AdinaThePotato1** [comment]
even in vehicles, I sometimes cannot get out, and when I disconnect, it still says there is someone online on the server, and this tends to cause the server to crash once I rejoin

**Comment by Liruxo** [comment]
Please open one or more crash issues, i cannot help you without the necessary information

**Comment by ChrisLane** [comment]
Please use the issue templates to help us to assist you.
