### ISSUE TITLE
Update a Flans Datapack

### ISSUE THREAD

**Issue by MasterValler** [FlansMods/FlansMod#1169]
Can you or someone else update pack a punch pack to 1.12.2 i realy want it and i dont know how to code or edit code in such a way?

Or tell me about what to do to do it please!

**Comment by ChrisLane** [comment]
Sorry but that's not what this forum is for.
You might have some luck asking at https://discord.gg/gEJntrY

**Comment by physicainbazzar** [comment]
can anyone help me where to find flans pack a punch to download i cant find it anywhere?

**Comment by physicainbazzar** [comment]
for 1.7.10
