### ISSUE TITLE
Flans Mod Bomb bay. 

### ISSUE THREAD

**Issue by xXEmeraldCatXx** [FlansMods/FlansMod#1170]
In Flans or Simple Parts pack. There is no crafting recipe for the Bomb bay which is essential to crafting nearly all the planes. There's info online that you make it with 7 iron and 1 redstone dust but when you click on with JEI the recipe doesn't come up nore having the materials and crafting it in the crafting table and just doesn't craft the part
Forge: 1.12.2-forge1.12.2-14.23.5.2846
Flans Mod: 5.6-Beta

**Comment by Liruxo** [comment]
![image](https://user-images.githubusercontent.com/46451644/80246438-b1744b00-866c-11ea-8a4a-668e1394ddf9.png)
 
Your crafting recipe is wrong, i do not encounter any problems with this one
