### ISSUE TITLE
1.12.2 Malisiscore Conflict

### ISSUE THREAD

**Issue by The-Artificer** [FlansMods/FlansMod#1172]
**Describe the bug**

Weapons mounted on vehicles fire projectiles that do not behave properly and disappear after about a 2 blocks distance. Supposedly this is due to some odd conflict with malisisdoors of all things, but my only source is this kid screaming on the forums: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/2938348-flans-mod-shooting-problem-bug
I apologize if this hearsay is insufficient. I haven not tested to determine whether malisis is actually responsible, it is simply the best and only lead that I have.
Point being that vehicular weapons fail to hit their target on my 1.12.2 forge server unless at point blank range. Used debug key and F3+B to show hitboxes and flans entities to determine projectile behavior. All normal hand-held weapons seem to work fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. On a 1.12.2 forge server with both Flan's and malisisdoors mounted, enter a seat with control of a vehicle's gun
2. Try firing at anything

**Expected behaviour**

To be able to shoot things.

**Screenshots**

![image](https://user-images.githubusercontent.com/46545464/74601303-dd19fa00-5059-11ea-993b-688683d56f36.png)

**Versions (please complete the following information)**
 - Forge: 1.12.2-ForgeModLoader 14.23.5.2847
 - Flan's Mod: 1.12.2-5.5.2

**Additional context**

**Comment by Mortivarus** [comment]
Why has this issue been closed? After testing with only malisis core and flan, this issue is still there. It also causes shots that are fired to explode in the player's face.
