### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by zakerr99** [FlansMods/FlansMod#1175]
**To Reproduce**
Steps to reproduce the crash:
1. add mod
2. start game

**Screenshots**

**Versions**
 - Forge: 1.12.2-forge1.12.2-14.23.5.2847
 - Flan's Mod: 1.12.2-5.5.2

**Crash Log**
< The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Flan's Mod: Apocalypse (flansmodapocalypse)-->

[crash-2020-02-22_11.41.43-client.txt](https://github.com/FlansMods/FlansMod/files/4239790/crash-2020-02-22_11.41.43-client.txt)

**Comment by ChrisLane** [comment]
You're using an old version of the mod:
https://github.com/FlansMods/FlansMod/releases
