### ISSUE TITLE
.

### ISSUE THREAD

**Issue by TurismoR** [FlansMods/FlansMod#1179]

**Comment by TurismoR** [comment]
Of course I using forge 1.12.2 if you are wondering

**Comment by Liruxo** [comment]
I do not know what your friend is referring to. Your setup seems correct to me, apart from to fact that you are using an outdated version.
Please try using this [Guide](https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod) with v5.6-beta.6

**Comment by ChrisLane** [comment]
No response. Closing
