### ISSUE TITLE
Vehicle turrets not rotating

### ISSUE THREAD

**Issue by matt-bel** [FlansMods/FlansMod#1180]
**Describe the bug**
Vehicle turrets won't follow the rotation of the player unless the player is rotating very slowly. I can rotate the player model 180 degrees, but not the actual vehicle turret. This does not apply to planes. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Get in any vehicle, such as proto titan or t-90 tank
2. turn around 180 degrees
3. Right click rapidly while attempting to turn
4. In case 1, nothing will happen, case 2 will rotate the turret by jittering.

**Expected behaviour**
Expect turret to rotate like it did in previous versions?

**Versions (please complete the following information)**
 - Forge: 1.12.2 - 14.23.5.2768
 - Flan's Mod: v5.6-beta.6

**Comment by ChrisLane** [comment]
The fix for this is now released in v5.6-beta.7
