### ISSUE TITLE
Flan's mod apocalypse-5.5.2 not compatible with Galacticraft Core/MJRLegendslib1.12.2-1.1.9 Forge1.12.2-14.23.5.2846

### ISSUE THREAD

**Issue by velocityraptor-real** [FlansMods/FlansMod#1183]
To Reproduce:
Steps to reproduce the crash:
1. 
Install Flan's mod
Install Galacticraft Core, Galacticraft Planets, MJRLegendslib, micdoodle8core and Extra Planets
2. 
Run the game with these mods.

Versions:
 - Forge: 1.12.2-14.23.5.2846
 - Flan's Mod: 1.12.2-5.5.2

[crash-2020-03-21_09.18.20-client.txt](https://github.com/FlansMods/FlansMod/files/4362582/crash-2020-03-21_09.18.20-client.txt)

Additional info:
Game works with Flansmodapocalypse removed.
Please give me Flan's mod with ALL apocalypse code removed, so it also works severside.
Otherwise, please fix the Problem.

Thank you,
Velocityraptor

**Comment by velocityraptor-real** [comment]
Game works with Flansmod5.6 given in
https://github.com/FlansMods/FlansMod/issues/997
But some content packs do not work/ are inaccessible and Players get fatally missing registry entries message, if they try to join a lan world

**Comment by ChrisLane** [comment]
Please open a new issue for the new problems if one does not exist already.
