### ISSUE TITLE
Firing at-4 and panzerfaust Freezes the Game

### ISSUE THREAD

**Issue by Matcha7** [FlansMods/FlansMod#1185]
**Describe the bug**

Upon firing the at-4 rocket launcher and the panzerfaust, the gun drops to the ground and a weird animation is drawn repeatedly causing the game to slow down. FPS is dramatically reduced. Also, there is no reload animation for these two weapons. Please see the attached screenshot.
**To Reproduce**
Steps to reproduce the behaviour:
1. Fire the at-4 or the panzerfaust

**Expected behaviour**
Rocket launches, blows stuff up (like other rocket launchers ex. RPG seems to work fine)

**Screenshots**
https://i.gyazo.com/8565333d2ea55bd50382aa254249a6b3.png
https://i.gyazo.com/18f5e7b5e79ef47e0da8a71d5939bcd8.png

**Versions (please complete the following information)**
Forge: 1.12.2 - 14.23.5.2768
Flan's Mod: v5.6-beta.6

**Additional context**
It is possible that the bug is client-sided. Testing this bug on my flans mod server: I used another computer (one that the server isn't hosted on), the bug would occur causing my client-side FPS to drop. I quit the server and relogged and the animation/bug is no longer there. Does not seem to crash the server, but the bug happens every time I shoot the gun through my client.

**Comment by Zl0gix** [comment]
the LAW rocket launcher does the same thing
