### ISSUE TITLE
i don't have sound from guns, guns aren't firing on server.

### ISSUE THREAD

**Issue by martprenger** [FlansMods/FlansMod#1190]
hi,
I just made a server with the flans mod only when i fire a gun it doesn't make sound and it doesn't fire bullets. It makes a animation. The ammo counter doesn't go down.

minecraft version: 1.12.2
forge version: 12.23.5.2768
flans version: 5.6

Apologies for the bad English

**Comment by Liruxo** [comment]
It seems you are using an outdated version. Please follow the instructions at https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod to install the latest version
