### ISSUE TITLE
Hey i need help Please help me

### ISSUE THREAD

**Issue by goldenpizza** [FlansMods/FlansMod#1195]
Hello staff reading this i really want to get this mod but i dont know how to get it

Can you please send me an video teaching how to download this from

idk if this helps but im sure youve heard about tlauncher the website and launcher that lets you get an minecraft account for free yeah i did not pay for mc but other mods have worked

thanks

**Comment by Liruxo** [comment]
This Github repository is about FlansMod. If you are unable to use the official Forge Mod Loader, we are unable to help in any way, shape or form.
