### ISSUE TITLE
Crashed using WW2 armor box

### ISSUE THREAD

**Issue by Mb200175** [FlansMods/FlansMod#1196]
**To Reproduce**
Steps to reproduce the crash:
1. Place WW2 Armor Box
2. Enter GUI
3. Click Right arrow in GUI twice

**Versions (please complete the following information)**
 - Forge: 14.23.5.2772
 - Flan's Mod: 5.5.1&5.5.2 (Tried both versions)

**Crash Log**
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

**Comment by Liruxo** [comment]
It seems you are using an outdated version. Please follow the instructions at https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod to install the latest version
