### ISSUE TITLE
I can not load the project in the IDE

### ISSUE THREAD

**Issue by muffincolor** [FlansMods/FlansMod#1199]
**Describe the bug**
Error on load

**Screenshots**
[Photo](https://imgur.com/a/N1KVL4s)

**Versions (please complete the following information)**
 - Branch 1.12.2

**Additional context**
Could you please give me a glimpse of where the methods of driving cars are. For example, gatsar (id machines). For example, I want to add a function to lock the car with another player. Assign a vehicle to a specific player. Etc. Where can I find this functionality

**Comment by Liruxo** [comment]
I am sorry but we are unable to provide support for IDE specific problems. If you encounter any issues while doing so, please refer to the internet for help. From guessing, i would advise you to see a tutorial on forge modding and gradle and how to setup a project for that purpose.

For your actual question, driving cars are usually (no guarantee) an instance of `EntityDriveable`. However, FlansMod currently does not support permanently assigning a specific player to any vehicle which is necessary for the mentioned functionality
