### ISSUE TITLE
Block mounted MGs bullets come out at the wrong Y axis.

### ISSUE THREAD

**Issue by slyfoxD** [FlansMods/FlansMod#1202]
**Bug**
looking up shoots down and looking down shoots up.
This is a new bug only found on 5.6 Beta 7, and happens with both bullet entities and raytraced bullets.
The angle the gun model points the correct direction but the bullets appear to shoot out at the reversed Y of where you look.

**To Reproduce**
Steps:
1. Take any mounted MG and place it on a block.
2. Have a large wall to aim at and shoot at it while looking up and down side to side. 
3. Watch as you aim up and down the bullets will shoot out of the reversed angle Instead of following the aim point of the gun. 

**Screenshots**
![Looking down shoots up](https://user-images.githubusercontent.com/48050558/80778061-c188a080-8b2c-11ea-8cd5-46174ca08383.png)
This screenshot shows me looking down and firing the mounted MG, the bullets go up instead.
I changed the gun to have a slower bullet speed to make it easier to show the bullets hit box going the wrong way. 

**Versions**
 - Forge: forge-1.12.2-14.23.5.2838
 - Flan's Mod: 1.12.2-5.6.0-beta.7

**Additional context**
This bug is new to the mod all previous versions the bullets of MGs went where you aimed.

**Comment by chickenoodlez** [comment]
I'm having the same problem I believe... https://github.com/FlansMods/FlansMod/issues/1287
