### ISSUE TITLE
No Tank Body recipes

### ISSUE THREAD

**Issue by TheNumenorean** [FlansMods/FlansMod#1203]
**Describe the bug**
No recipes for tank bodies

**To Reproduce**
Steps to reproduce the behaviour:
1. Install
2. Check recipes using JEI

**Expected behaviour**
Tank bodies have recipes

**Versions (please complete the following information)**
 - Forge:  14.23.5.2847
 - Flan's Mod: 5.6.0-beta-7

**Additional context**
[18:47:08] [Client thread/INFO] [flansmod]: Registering Recipes.
[18:47:08] [Client thread/WARN] [flansmod]: Could not find trapdoor when adding recipe for unknown
[18:47:08] [Client thread/WARN] [flansmod]: Failed to find D in recipe for lightTankBody
[18:47:08] [Client thread/WARN] [flansmod]: Could not find trapdoor when adding recipe for unknown
[18:47:08] [Client thread/WARN] [flansmod]: Failed to find D in recipe for advancedTankBody
[18:47:08] [Client thread/WARN] [flansmod]: Could not find trapdoor when adding recipe for unknown
[18:47:08] [Client thread/WARN] [flansmod]: Failed to find D in recipe for heavyTankBody
[18:47:08] [Client thread/WARN] [flansmod]: Could not find trapdoor when adding recipe for unknown
[18:47:08] [Client thread/WARN] [flansmod]: Failed to find D in recipe for mediumTankBody
[18:47:08] [Client thread/WARN] [flansmod]: Could not find trapdoor when adding recipe for unknown
[18:47:08] [Client thread/WARN] [flansmod]: Failed to find D in recipe for bombBay

**Comment by Liruxo** [comment]
We are sorry, but JEI is currently not supported. Please refer to #1045 for further updates

**Comment by fjmacagno** [comment]
I dont believe jei is relevant here, as the recipe does not work irrespective of what jei shows. It is a standard part recipe possible in the standard crafting table, not one of the custom recipes for vehicles, so unless jei broke the name of the trapdoor somehow I doubt that is it. In addition, other part recipes work fine in jei.

My suspicion is that the trapdoor is just not discoverable using the existing custom recipe framework, perhaps since it is a tile, or another mod is tweaking it somehow.

If I have time i will put in a pr.

**Comment by Liruxo** [comment]
> [Client thread/WARN] [flansmod]: Could not find trapdoor when adding recipe for unknown
[Client thread/WARN] [flansmod]: Failed to find D in recipe for bombBay

I just recently tested it, so i know that the recipe for the `bombBay` works as intended. If you encounter any issues making items uncraftable, please open a new bug report

**Comment by TheNumenorean** [comment]
This is that bug report? 
![image](https://user-images.githubusercontent.com/809047/80823840-29250700-8b92-11ea-8e28-f8991e70afd5.png)
![image](https://user-images.githubusercontent.com/809047/80827905-4f01da00-8b99-11ea-8258-f83e0c2a0aa4.png)
The bomb bay recipe does not work.

Also apologies, accidentally used my work account above.

**Comment by Liruxo** [comment]
First, please explain what you expect the first crafting recipe to yield. It seems most similar to a medium tank body, but that does not require redstone.

Second am unable to reproduce these results, the warning in the logs suggest you have a faulty installation.
Please verify you are using the latest content packs and FlansMod jar. If the issue persists it is recommended to use a fresh Minecraft, Forge and FlansMod installation to rule out any outdated or faulty jars and/or configuration files
Please also verify you are following [these steps](https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod) to install FlansMod, if not note the differences to your process

**Comment by TheNumenorean** [comment]
First one is incorrect, i misread the part file here: https://github.com/FlansMods/FlansMod/blob/352a64809f554eb191c67c7b3bf1973c9c5f08a5/run/Flan/Parts%20Pack/parts/HeavyTankBody.txt#L10
Notably, it lists redstone as a component but does not use it. I think i may have found an older/incorrect version of the recipe online.

I have been able to reproduce the error in the development environment by adding Quark. Quark modifies the vanilla trapdoor name to oak_trapdoor (https://github.com/Vazkii/Quark/blob/84d797fadd81efdcd0c42bb31fd5eda7b8619434/src/main/java/vazkii/quark/decoration/feature/VariedTrapdoors.java#L96), which breaks the string name used for the part.

This can be fixed by setting `decoration."varied trapdoors"."Rename vanilla trapdoor to Oak Trapdoor"=false` in quark.cfg, which fixes the problem. This could also be fixed on the Flansmod side by adding support for the OreDictionary `trapdoorWood` entry added by Quark, though that certainly isn't Flansmod's responsibility. However, it could be a convenient simple improvement which avoids future problems.

**Comment by Liruxo** [comment]
There is a enhancement ticket for OreDictionary already (#146).
I also added this issue to the [1.12.2 compatibility list](https://github.com/FlansMods/FlansMod/wiki/1.12.2-Mods-compatibility-list)
