### ISSUE TITLE
[1.12.2] Game Freezes When Shooting Tank or Aircraft Guns While MalisisCore is Installed

### ISSUE THREAD

**Issue by CaveMiner1215** [FlansMods/FlansMod#1204]
**To Reproduce**
Steps to reproduce the crash:
1. Get into a world with both the latest Flan's Mod and MalisisCore installed.
2. Place any tank.
3. Load it with any compatible shell.
4. Fire the main gun (you may find that the shell will explode upon leaving the tank's barrel, which is another issue with the incompatibility; to avoid this, aim your gun higher).

After following these steps, the game should freeze around 4-5 seconds after firing the shell.

**Screenshots**
Not Applicable

**Versions (please complete the following information)**
 - Forge: 1.12.2 build 2847
 - Flan's Mod: 5.6.0 Beta 7

**Crash Log**
https://gist.github.com/CaveMiner1215/2ff569f6cc4ef65201532b9f9dfd7f4c

**Additional context**
When firing tank or aircraft guns while MalisisCore is installed, the game will freeze, requiring a forced shut down, producing a crash report detailing a StackOverflowError due to the ray tracing class(es).

**Comment by ChrisLane** [comment]
Same issue as #1145

**Comment by CaveMiner1215** [comment]
Hmm I see...it is indeed the same issue, and he/she had MalisisCore installed as well.  Fortunately, the problem can now be narrowed down to a current incompatibility between Flan's Mod and MalisisCore.

**Comment by vos6434** [comment]
Will this be fixed relatively soon?

**Comment by ChrisLane** [comment]
Closing this. Details in #1145
