### ISSUE TITLE
Simple parts problem

### ISSUE THREAD

**Issue by xSLUMA** [FlansMods/FlansMod#1207]
I am on the latest build of flans on 1.12.2 and can't craft some of the parts in the simple parts pack. pls help

**Comment by Liruxo** [comment]
We are sorry but we are unable to help you.
Please verify you are using the latest content packs and FlansMod jar. If the issue persists it is recommended to use a fresh Minecraft, Forge and FlansMod installation to rule out any outdated or faulty jars and/or configuration files
Please also verify you are following [these steps](https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod) to install FlansMod, if not note the differences to your process

If you still encounter issues please refer to
https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting

**Comment by xSLUMA** [comment]
I have tried a new forge installation forge-1.12.2-14.23.5.2847 and reinstalled flans, deleted the config and content pack and got the latest ones from github. everything runs except that I can't craft certain items like the light tank body and heavy body

**Comment by ChrisLane** [comment]
@xSLUMA What specific version of Flan's mod are you trying?
I was able to craft a light tank body with v5.6-beta.7
![](https://i.imgur.com/XoTrUOq.png)

**Comment by ChrisLane** [comment]
What other mods do you have installed? My guess is that you have Quark installed which causes compatibility problems: https://github.com/FlansMods/FlansMod/wiki/1.12.2-Mods-compatibility-list
