### ISSUE TITLE
Bomb Bay Uncraftable.

### ISSUE THREAD

**Issue by WaltWhitmanOG** [FlansMods/FlansMod#1208]
I cannot craft the bomb bay. I have tried every recipe imaginable, and when I click it in JEI, it doesn't give me options to craft it. 

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. 
2. 
3. 
4. 

**Expected behaviour**

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 14.23.5.2847
 - Flan's Mod: 5.5.2

**Additional context**

**Comment by ChrisLane** [comment]
A quick search of existing issues would find the solution to your problem.
Duplicate of #1170
