### ISSUE TITLE
Uncraftable bomb Bay

### ISSUE THREAD

**Issue by WaltWhitmanOG** [FlansMods/FlansMod#1209]
I've seen issue #1170 and the answer to try a crafting recipe with 7 iron and a trap door doesn't work. That's the whole reason I'm posting this issue. It doesn't have any way to craft and the solution is not to use 7 iron and 1 trap door.

**Comment by ChrisLane** [comment]
Please comment on the issue you already made.
You're also using an old version of the mod. Download the latest here: https://github.com/FlansMods/FlansMod/releases
