### ISSUE TITLE
Uncraftable Items

### ISSUE THREAD

**Issue by GladBody22** [FlansMods/FlansMod#1211]
Before you say I screwed up and didn't download everything right, I have. Me and my friends have run into multiple items being uncraftable. For example the Bomb Bay is uncraftable. The Mini-Gun is not in any of the weapons boxes. The Med-Kit requires the Uncraftable Potion, how do you make that? Some of these things need to be seriously looked at. You guys should focus on bug fixes before adding more content.

**Comment by ChrisLane** [comment]
@GladBody22 We can't provide any support if you don't fill out the bug issue template that we've created to make sure that we are able to get all of the information that we require to debug the problem.

https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting

Please open a new issue that uses the bug template after reading the information at the link above.
