### ISSUE TITLE
[1.12.2] Possible Memory Leak

### ISSUE THREAD

**Issue by Diamondman121314** [FlansMods/FlansMod#1215]
**Describe the bug**
It seems like Flan's Mod is causing a memory leak. The game kinda just froze out of nowhere.

**To Reproduce**
Steps to reproduce the behaviour:
1. Just have Flan's Mod with all addons.

**Expected behaviour**
No memory leak and the game not to freeze

**Versions (please complete the following information)**
 - Forge: 14.23.5.2854
 - Flan's Mod: 5.6.0-beta.7 + all packs on GitHub of the same version
**Additional context**
https://gist.github.com/Diamondman121314/64842375fd56e671ecec3a340a67b4f3

**Comment by ChrisLane** [comment]
What kind of environment is this occurring on? A single player world or a server?
If this is being run on a server, how many players and are you using the /teams features?

**Comment by Diamondman121314** [comment]
I'm on a server environment without any players at the time of that gist log. I was in the process of testing a modpack that I was making out and enabled the Netty leak detection. `-Dio.netty.leakDetection.level=advanced` So unless it does something automatically, I haven't used the teams feature.

I'm not sure if this is obvious from what I showed, but that log was from the client.

**Comment by Diamondman121314** [comment]
Small update. The game doesn't freeze because of this mod, but that memory leak is still a thing. It's not as major as I thought it was, just another random leak that happens. Not sure what causes it.

**Comment by ChrisLane** [comment]
@Diamondman121314 could you post your server log from a time when you got these leak alerts please?
