### ISSUE TITLE
Crashing Vehicles Causes Infinite Kick Loop

### ISSUE THREAD

**Issue by GladBody22** [FlansMods/FlansMod#1223]
**To Reproduce**
Steps to reproduce the crash:
1. Fly a vehicle low to the Ground
2. Slow Down 
3. Tip Vehicle into ground
I think this will recreate it. Whenever I've hit the ground with a vehicle it does this. It gets stuck in the blocks. 

**Versions (please complete the following information)**
 - Forge: 14.23.5.2847
 - Flan's Mod: 5.6(beta7) 

**Additional context**
This has happened to me twice when I've flown the MH-6 Littlebird and just a few moments ago when I tried flying the Tornado. I don't know why it happened with the Little Bird because all it did was glitch into the ground a few blocks and then I crashed and had to have my friends break it. Now though, with the Tornado, I believe I flew under the chunks as they were loading because i saw the bottom of bedrock. And now I'm stuck in a random chunk, infinitely getting kicked. Because of the location I'm, I don't think my friends can come break the plane. So I can't log onto my server.

This is the error I get when I crash. 
![2020-05-10_11 40 48](https://user-images.githubusercontent.com/62675926/81506531-38a00080-92b4-11ea-9b9b-0dbcf04e3437.png)

**Comment by ChrisLane** [comment]
Could you please post any client and server logs you have?

**Comment by GladBody22** [comment]
How would I find my client logs?
I don't believe it's server issues since it doesn't crash the server, just my client.

**Comment by GladBody22** [comment]
So we tried something on my server. We cleared all entities. And that worked. So it's something with the entity and I believe it's because it clips into the ground.

**Comment by ChrisLane** [comment]
> How would I find my client logs?
> I don't believe it's server issues since it doesn't crash the server, just my client.

They're in your .minecraft folder.
Server logs are required since it is the server that is kicking the client.

**Comment by ChrisLane** [comment]
Needed logs
