### ISSUE TITLE
Crash when holding flansmod item in player hand

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#1224]
Steps to reproduce the crash:
1. Compile the latest master (as of f3da61722fa9313c39bf9ea6c052acdaacb0f0c0)
2. Hold biplane from ye olde pack in the player hand

 - Forge: v14.23.5.2854
 - Flan's Mod: f3da61722fa9313c39bf9ea6c052acdaacb0f0c0

**Crash Log**
[gist](https://gist.github.com/DevyHeavy/7768fac6aa24a573f6a156d0398a3d4d)

May be related to #1193

**Comment by ChrisLane** [comment]
I suspect you've compiled the mod with Java 9+ and then it's failing when you try to run it on Java 8

Can you confirm this?

**Comment by ghost** [comment]
You're correct. Java path was set to version 11. Compiling with Java 8 fixes the problem.

I should have checked, thank you for your time.

Closing.
