### ISSUE TITLE
server crashes during startup once flans is added

### ISSUE THREAD

**Issue by rylandevans2312** [FlansMods/FlansMod#1227]
server crashes during startup once flans is added, from what i can tell the issue is caused by the flans apocalypse content pack but once i remove it the error still says flans apocalypse

**Comment by ChrisLane** [comment]
You've not followed any of the guidance [here](https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting) or used the crash report template. As a result, we're not able to help you so I'm closing this issue. Please open a new issue if you've followed the advice at the link given and still have the problem.
