### ISSUE TITLE
Opening fuel menu crashes client and server when a fuel can is used up

### ISSUE THREAD

**Issue by sambam05** [FlansMods/FlansMod#1228]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  CustomSkinLoader (CustomSkinLoader_Forge-14.11.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
  LoadingPlugin (Xaeros_Minimap_20.5.2_Forge_1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/19/20 3:05 PM
Description: Exception in server tick loop

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.util.NonNullList.add(SourceFile:56)
	at java.util.AbstractList.add(Unknown Source)
	at net.minecraft.inventory.Container.func_75138_a(Container.java:63)
	at net.minecraft.inventory.Container.func_75132_a(Container.java:52)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:101)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at com.flansmod.common.network.PacketDriveableGUI.handleServerSide(PacketDriveableGUI.java:52)
	at com.flansmod.common.network.PacketHandler.handleServerPackets(PacketHandler.java:171)
	at com.flansmod.common.CommonTickHandler.tick(CommonTickHandler.java:54)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_300_CommonTickHandler_tick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1855272184 bytes (1769 MB) / 9391439872 bytes (8956 MB) up to 13493403648 bytes (12868 MB)
	JVM Flags: 10 total; -Xmx13G -XX:TargetSurvivorRatio=90 -XX:+UseAdaptiveGCBoundary -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:NewRatio=2 -XX:+AggressiveOpts -XX:CMSInitiatingOccupancyFraction=90 -Xnoclassgc -XX:ReservedCodeCacheSize=1G
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 100 mods loaded, 100 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                           | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                               | 9.42              | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2.jar                                 | None                                     |
	| LCHIJA | forge                             | 14.23.5.2847      | forge-1.12.2.jar                                 | None                                     |
	| LCHIJA | micdoodlecore                     |                   | minecraft.jar                                    | None                                     |
	| LCHIJA | xaerominimap_core                 | 1.12.2-1.0        | minecraft.jar                                    | None                                     |
	| LCHIJA | randompatches                     | 1.12.2-1.21.0.0   | randompatches-1.12.2-1.21.0.0.jar                | None                                     |
	| LCHIJA | bspkrscore                        | 7.6.0.1           | [1.12]bspkrsCore-universal-7.6.0.1.jar           | None                                     |
	| LCHIJA | actuallyadditions                 | 1.12.2-r151       | ActuallyAdditions-1.12.2-r151-2.jar              | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar             | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | placebo                           | 1.6.0             | Placebo-1.12.2-1.6.0.jar                         | None                                     |
	| LCHIJA | attaineddrops2                    | 3.7.3             | Attained+Drops-1.12.2-3.7.3.jar                  | None                                     |
	| LCHIJA | attributefix                      | 1.0.10            | AttributeFix-1.12.2-1.0.10.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | biggerpacketsplz                  | 1.2               | biggerpacketsplz-since1.8-1.2.jar                | 266588b191a3e2974a4a577f282858a3bc07da42 |
	| LCHIJA | bookshelf                         | 2.3.585           | Bookshelf-1.12.2-2.3.585.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | buildcraftlib                     | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | crafttweaker                      | 4.1.20            | CraftTweaker2-1.12-4.1.20.574.jar                | None                                     |
	| LCHIJA | buildcraftcompat                  | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.24.5         | buildcraft-all-7.99.24.5.jar                     | None                                     |
	| LCHIJA | cctweaked                         | 1.86.2            | cc-tweaked-1.12.2-1.86.2.jar                     | None                                     |
	| LCHIJA | computercraft                     | 1.86.2            | cc-tweaked-1.12.2-1.86.2.jar                     | None                                     |
	| LCHIJA | jei                               | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                        | None                                     |
	| LCHIJA | chisel                            | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                     | None                                     |
	| LCHIJA | chunkpregenerator                 | 2.1               | Chunk+Pregenerator+V1.12-2.2.jar                 | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                          | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar           | None                                     |
	| LCHIJA | cofhworld                         | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | crafttweakerjei                   | 2.0.3             | CraftTweaker2-1.12-4.1.20.574.jar                | None                                     |
	| LCHIJA | waila                             | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | darkutils                         | 1.8.230           | DarkUtils-1.12.2-1.8.230.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | dynmap                            | 3.0-beta-4-213    | Dynmap-3.0-beta-4-forge-1.12.2.jar               | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.73     | EnderCore-1.12.2-0.5.73.jar                      | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion                  | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                           | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderiobase                       | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderioconduits                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                 | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | ftblib                            | 5.4.7.0           | FTBLib-5.4.7.0.jar                               | None                                     |
	| LCHIJA | enderiomachines                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderiopowertools                 | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                        | None                                     |
	| LCHIJA | enderstorage                      | 2.4.6.137         | EnderStorage-1.12.2-2.4.6.137-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | energyconverters                  | 1.3.6.24          | energyconverters_1.12.2-1.3.6.24.jar             | None                                     |
	| LCHIJA | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                       | None                                     |
	| LCHIJA | flansmod                          | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                      | None                                     |
	| LCHIJA | flansmodapocalypse                | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                      | None                                     |
	| LCHIJA | worldedit                         | 6.1.10            | worldedit-forge-mc1.12.2-6.1.10-dist.jar         | None                                     |
	| LCHIJA | forgeessentials                   | 12.3              | forgeessentials-1.12.2-12.3.82-server.jar        | None                                     |
	| LCHIJA | ftbutilities                      | 5.4.0.124         | FTBUtilities-5.4.0.124.jar                       | None                                     |
	| LCHIJA | ic2                               | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | itemfilters                       | 1.0.3.12          | ItemFilters-1.0.3.12.jar                         | None                                     |
	| LCHIJA | ftbquests                         | 1.8.0.237         | FTBQuests-1.8.0.237.jar                          | None                                     |
	| LCHIJA | ftbmoney                          | 1.1.0.42          | FTBMoney-1.1.0.42.jar                            | None                                     |
	| LCHIJA | cfm                               | 6.3.1             | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LCHIJA | galacticraftcore                  | 4.0.2.244         | GalacticraftCore-1.12.2-4.0.2.244.jar            | None                                     |
	| LCHIJA | galacticraftplanets               | 4.0.2.244         | Galacticraft-Planets-1.12.2-4.0.2.244.jar        | None                                     |
	| LCHIJA | gravestone                        | 1.10.2            | gravestone-1.10.2.jar                            | None                                     |
	| LCHIJA | helpfixer                         | 1.12.1-1.5.18     | HelpFixer-1.12.1-1.5.18.jar                      | None                                     |
	| LCHIJA | icbmclassic                       | 1.12.2-3.3.0.63   | ICBM-classic-1.12.2-3.3.0b63.jar                 | None                                     |
	| LCHIJA | railcraft                         | 12.0.0            | railcraft-12.0.0.jar                             | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | immersiveengineering              | 0.12-92           | ImmersiveEngineering-0.12-92.jar                 | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | immersivepetroleum                | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar              | None                                     |
	| LCHIJA | trackapi                          | 1.2               | TrackAPI-1.2.jar                                 | None                                     |
	| LCHIJA | immersiverailroading              | 1.7.3             | ImmersiveRailroading-1.7.3_1.12.2.jar            | None                                     |
	| LCHIJA | universalmodcore                  | 1.0.0             | ImmersiveRailroading-1.7.3_1.12.2.jar            | None                                     |
	| LCHIJA | laggoggles                        | FAT-1.12.2-4.9    | LagGoggles-FAT-1.12.2-4.9.jar                    | None                                     |
	| LCHIJA | mcjtylib_ng                       | 3.5.4             | mcjtylib-1.12-3.5.4.jar                          | None                                     |
	| LCHIJA | mekanism                          | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                    | None                                     |
	| LCHIJA | mekanismgenerators                | 1.12.2-9.8.3.390  | MekanismGenerators-1.12.2-9.8.3.390.jar          | None                                     |
	| LCHIJA | mekanismtools                     | 1.12.2-9.8.3.390  | MekanismTools-1.12.2-9.8.3.390.jar               | None                                     |
	| LCHIJA | mcef                              | 0.9               | Minecraft-Chromium-Embedded-Framework-1.12.2.jar | None                                     |
	| LCHIJA | mtrm                              | 1.2.2.30          | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar       | None                                     |
	| LCHIJA | mob-blacklister                   | 1.2.0             | mobblacklister-1.2.0-mc1.12.jar                  | None                                     |
	| LCHIJA | mob_grinding_utils                | 0.3.13            | MobGrindingUtils-0.3.13.jar                      | None                                     |
	| LCHIJA | recipehandler                     | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar            | None                                     |
	| LCHIJA | redstonearsenal                   | 2.6.3             | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | rftools                           | 7.73              | rftools-1.12-7.73.jar                            | None                                     |
	| LCHIJA | simpleoregen                      | 4.3.4             | SimpleOreGeneration-4.3.4+mc+1.12.2.jar          | None                                     |
	| LCHIJA | thermaldynamics                   | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | treecapitator                     | 1.43.0            | TreeCapitator-client-1.43.0.jar                  | None                                     |
	| LCHIJA | gvc                               | 1.2.0             | Voice+Chat+Reloaded-1.2.0.jar                    | None                                     |
	| LCHIJA | webdisplays                       | 1.0               | Web-Displays-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | worldborder                       | 1.0.0             | World-Border-1.12.2-1.0.6.jar                    | None                                     |
	| LCHIJA | xlfoodmod                         | 1.12.2-1.9.2      | XL-Food-Mod-1.12.2-1.9.2.jar                     | None                                     |
	| LCHIJA | claimitapi                        | 1.12.2-1.2.0      | claimitapi-1.12.2-1.2.0.jar                      | None                                     |
	| LCHIJA | claimit                           | 1.12.2-1.2.0      | claimit-1.12.2-1.2.0.jar                         | None                                     |

	Loaded coremods (and transformers): 
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
CustomSkinLoader (CustomSkinLoader_Forge-14.11.jar)
  customskinloader.forge.loader.LaunchWrapper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
  net.elnounch.mc.biggerpacketsplz.BiggerPacketsPlzClassTransformer
LoadingPlugin (Xaeros_Minimap_20.5.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
  com.therandomlabs.randompatches.core.RPTransformer
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	ForgeEssentials: Running ForgeEssentials 12.3.82 (b9cf068). Modules loaded: Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 3 / 20; [GCEntityPlayerMP['Sambam05'/229, l='earth', x=-387.05, y=63.14, z=-3211.47], GCEntityPlayerMP['Crazykid8080'/827, l='earth', x=-268.87, y=66.00, z=-3410.09], GCEntityPlayerMP['Boonert'/11292, l='earth', x=5094.70, y=72.00, z=-1365.24]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Trhod17** [comment]
try the latest release from here 
https://github.com/FlansMods/FlansMod/releases

**Comment by ChrisLane** [comment]
Not following issue posting guidelines. Isn't using the latest version suggested in the guidelines. Closing.
