### ISSUE TITLE
Raytracing Crash with Sponge Server

### ISSUE THREAD

**Issue by spruill7716** [FlansMods/FlansMod#1232]
Getting this crash with the newest  Flans beta on Sponge. It happens any time I shoot a gun.

**To Reproduce**

1. Open server using Sponge(v.7.2.2 RC4029), Forge(14.23.5.2847), and Flans(v.5.6.0 Beta 7)
2. Shoot any gun (Tried using WW2 and MW guns)

**Versions**
 - Forge: 14.23.5.2847
 - Flan's Mod: 5.6.0 Beta 7

**Crash Log**
https://www.dropbox.com/s/54m9zxwh1jya8os/crash-2020-05-24_11.51.27-server.txt?dl=0

**Comment by ChrisLane** [comment]
Duplicate of #1145
