### ISSUE TITLE
Rockets dont work in thermos server

### ISSUE THREAD

**Issue by LtTse24** [FlansMods/FlansMod#1233]
**Describe the bug**
The  bug happens only on the server but not in singleplayer, in singleplayer I can use hydra's and other rockets but when I connect to my server(thermos 1.7.10) they don't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to the server
2. take any helicopter(with rocket pods [correct ammunition])
3. sit down and try to shoot the rockets
4. they wont explode or anything

**Expected behaviour**
I was expecting that rockets would have exploded.

**Versions (please complete the following information)**
 - Forge: 17.10 1614
 - Flan's Mod: flans mod plus

**Comment by ChrisLane** [comment]
Sorry but we don't develop "Flan's Mod Plus" and so cannot support it.
