### ISSUE TITLE
Broadband usage has increased a lot

### ISSUE THREAD

**Issue by Natsukiw** [FlansMods/FlansMod#1237]
**Describe the bug**

In some cases, server broadband usage will increase a lot.
I tested it at 1.710 and I think most Flan versions have this problem.

**To Reproduce**
Steps to reproduce the behaviour:
1. Fill your backpack with guns, except for one slot
2. Keep more than two players around you,make sure you can see the changes in broadband
3. Hold the gun and observe broadband usage
4. Empty hands or holding a non-gun item, and then observe the broadband usage

**Expected behaviour**

**Screenshots**

https://cdn.discordapp.com/attachments/717069595353153569/717246951107723335/unknown.png

**Versions (please complete the following information)**
 - Forge: 1614
 - Flan's Mod: 1.7.10

**Additional context**

**Comment by ChrisLane** [comment]
Sorry, we no longer support 1.7.10 versions of the mod.
