### ISSUE TITLE
Additional gun options (muzzle flash, spread pattern, delay, underwater)

### ISSUE THREAD

**Issue by JValor2417** [FlansMods/FlansMod#1246]
**Describe the solution you'd like**
Adding more options for ShootDelay to ammo and attachments similar to that of “ recoil “ “ damage “ “ accuracy “ etc. I understand every one is very busy so these are just somethings I think would help a lot of people out. 

-Show ShootDelay T/F 
-ShootDelayMultiplier 0.0

Muzzle Flash models that can be rendered per shooting event and are definable by each weapons configuration. 

HasMuzzleFlash T/F
MuzzleFlashModel “Pack.namehere“
MuzzleFlashTexture “namehere.png”
MuzzleFlashSize 0.0 
MuzzleFlashTime 0.0
HasMuzzleFlashLight T/F

Another thing that might be easier is adding the “ShootParticles” field to Holdable gun configs,  which could then allow for custom particles or even just smoke for example.

If possible, re-add “ CanShootUnderWater T/F” 

Make guns with the field “ loadintogun # “
Have an option for “ HasSingleReload T/F “ which would work to the effect of every cartridge being loaded requires the reload key to be tapped. This would make tube fed weapons more useful and balanced, allowing ( one example ) shooting mid reload rather than filling up a magazine tube for not as many shots as other weapons. 

Add being able to see gun descriptions in the crafting tables. This way people can get a better idea of what they are making. 

Add spread patterns for both weapons, ammo and attachments. These could maybe be pulled in the config from presets like the following. These sets of patterns would allow for a lot of other options if configurable, like shooting lines of pellets. 

SpreadPattern <pattern> <Height> <width>
SpreadPattern Circle 1 1
SpreadPattern Square 1 1
SpreadPattern Triangle 1 1
SpreadPattern Random(current-state)

**Describe alternatives you've considered**
Non-applicable other than staying I have tried adding these things myself, however I’m not very Experienced In this category with java or Minecraft modding. 

**Additional context**
These things essentially would give a lot more immersion and quality of life aspects to the latest flans mod version(s)

**Comment by jamioflan** [comment]
See attached commits for new features. I think I missed the ShootParticles off, could you make a separate ticket though?
