### ISSUE TITLE
Optifine Bugs

### ISSUE THREAD

**Issue by lilnuggy** [FlansMods/FlansMod#1251]
Vehicles are transparent when placed down. The top half of a tall vehicle is often completely invisible depending on the perspective to the horizon. The Vehicle starts to become more visible higher the angle you look down from but is still transparent.

To try and recreate it I have Optifine_1.12.2_HD_U_F5 and the Shaders I'm using is KUDA-Shaders v6.5.56 

Spawning any vehicle will result in a transparent appearance 

![image](https://user-images.githubusercontent.com/64826719/85860992-9a95c600-b78d-11ea-949e-e148623a61ec.png)

 - Forge: Forge-1.12.2-14.23.5.2854 
 - Flan's Mod: Flan.s.Mod-1.12.2-5.6.0-beta.8
 - Flan's Content Packs:WW2-Content Pack-1.12.2-5.5.2, Alcara_v1

**Comment by Liruxo** [comment]
As listed here: https://github.com/FlansMods/FlansMod/wiki/1.12.2-Mods-compatibility-list
"Some shaders will make vehicles visible through walls (or other issues involving vehicles). If this happens try to use other shaders"

To my knowledge there is nothing we can do, as this is shader specific problem, but i am absolutely no expert on this topic so if you have deeper insights into this problem please let me know

Also, please follow these guidelines for issue reporting: https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting
