### ISSUE TITLE
Why does the Minecraft Flansmod 1.12.2 hold the weapon down and the 1.7.10 hold it forward?   (Google translator)

### ISSUE THREAD

**Issue by JarinnHD** [FlansMods/FlansMod#1254]
i'm creating a modpack for my future server and while working on the flansmod i noticed that in minecraft version 1.12.2 the gun is held down and in older versions the gun is held forward. is this because of the 1.12.2?

**Comment by ChrisLane** [comment]
What version of the mod are you using on 1.12.2? I believe this was fixed one of the beta versions.

**Comment by Jermanmafa** [comment]
Sorry to piggy-back their issue, but i have no idea how to set up an issue submission on here myself. As well, we have the same issue and more on our server. If you could help me to form my own issue (ticket, or whatever you want to call it) or assist me here, it would be very appreciated. Thanks in advance.

**Comment by Liruxo** [comment]
@Jermanmafa
This guide should explain everything you need:
https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting

**Comment by Jermanmafa** [comment]
Much obliged @Liruxo it seems we're running a v5.5.2, as well i noticed a few other mods that dont always play well with flans mod. Im a contributor to our modpack but i dont handle the coding or configs and such. Hopefully we can figure something out tho, fore i enjoy flans mod quite a bit. Thanks again.

**Comment by JarinnHD** [comment]
@ChrisLane Im use the version 5.5.2 of the Flan's mod

**Comment by Liruxo** [comment]
@JarinnHD Please follow this guide to use the latest version of FlansMod: https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod

**Comment by JarinnHD** [comment]
thanks its work

**Comment by JarinnHD** [comment]
Incidentally, the homepage is not yet up to date
