### ISSUE TITLE
Crafting table crash

### ISSUE THREAD

**Issue by DevilxHalo** [FlansMods/FlansMod#1255]
< so when you access the crafting table and fill it with items your game will crash with the tinkers crafting table and if you try it in the regular crafting table it will dupe items now I’ve looked at the report and it says that tinkers construct is causing it but that isn’t the case it’s the simple parts mod because when I get rid of tinkers it still does it but when I get rid of simple parts it’s fixed and it works
as you can -->
**To Reproduce**
Steps to reproduce the crash:
1. Install latest version of flans and simple parts and tinkers construct
2. Try to fill the tinkers or vanilla crafting table with item 
3. Crash

**Screenshots**

**Versions (please complete the following information)**
 - Flan's Mod: 5.5.2

**Crash Log**

**Additional context**

**Comment by DevilxHalo** [comment]
Btw it’s on Mc 1.12.2

**Comment by Liruxo** [comment]
It seems you are using an outdated version. Please follow the instructions at https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod to install the latest beta version of FlansMod

**Comment by ChrisLane** [comment]
Has updating to our latest version fixed the crashes for you @DevilxHalo?
