### ISSUE TITLE
Modpacks not reading skin files that have at least one upper case letter.

### ISSUE THREAD

**Issue by yagdev** [FlansMods/FlansMod#1261]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. 
2. 
3. 
4. 

**Expected behaviour**

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 
 - Flan's Mod: 

**Additional context**

Found it while porting a 1.7 pack to 1.12.2

**Comment by Fexcraft** [comment]
Since 1.11.2 **Minecraft** requires all/most assets (content under /assets folder) to be **lowercase**.
