### ISSUE TITLE
Problems on server.

### ISSUE THREAD

**Issue by CRAZYGAMER13** [FlansMods/FlansMod#1262]
I'm on a 1.12 .2 server with my friends and all vehicles don't fire their weapons. Bullets fly but just disappear directly after the barrel and shells bursts in the barrel and does no damage either. Same thing in singleplayer of this modpack. Works in a completly new modpack.

**Comment by Liruxo** [comment]
It seems you are using an outdated version. Please follow the instructions at https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod to install the latest version
Please also follow these instruction when reporting a issue: 
https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting

**Comment by CRAZYGAMER13** [comment]
Thanks i actually had a problem with anothernmod that was outdated and interferred with flans.
