### ISSUE TITLE
Crash when attempting to bring over a pack from 1.7.10 to 1.12 5.6 beta 8

### ISSUE THREAD

**Issue by TreeChairRope** [FlansMods/FlansMod#1265]
When I attempt to bring over my content pack from 1.7.10 gradle to 1.12 gradle in Flansmod 5.6 Beta 8 the game gets to the mojang screen then crashes. I've had several people look through the debuglog and couldnt figure out why its doing it more than something is messed up in the content pack.
[debug.log](https://github.com/FlansMods/FlansMod/files/4998042/debug.log)

**Comment by DubTheGrub** [comment]
1.7.10 packs aren't supposed to function on 1.12.

**Comment by Fexcraft** [comment]
It seems he said he wants to _update_ it, it IS supposed to work.

**Comment by TreeChairRope** [comment]
yes im trying to update it.

its something in a gun config cause removing those and leaving the tanks stopped the crashing, but i couldn't find anything that would break it, although now it wont even launch after editing a config and renaming a texture

**Comment by JValor2417** [comment]
@TreeChairRope If you'd like to send me the content-pack.JAR or in a .ZIP format over email I'll gladly sift through it and attempt a fix when i have some time. I'll summarize what concluded in that fix to the best of my ability. my email is kellydevelopmentteam@gmail.com 

If you do not feel comfortable sharing your work, post the config(s) here and I can run through them and see what i find, as that should be enough.

**Comment by ChrisLane** [comment]
Please provide the content packs for us to look at.

**Comment by ChrisLane** [comment]
Closing this until more info can be provided
