### ISSUE TITLE
Still getting crashes when shift-clicking items in survival.

### ISSUE THREAD

**Issue by RoggyRogg** [FlansMods/FlansMod#1266]
Typed this when trying to get crash log, but when i shift clicked this time, i didnt get a crash, not sure why just yet - wait nevermind lol

**To Reproduce**
Steps to reproduce the crash:
1. Take any Flan's Mod item into any container (inventory, chest, etc.)
2. Hold down Shift, and Left click on that item
3.  Screen shows "Shutting Down Internal Server"
4. Voila, you have yourself a crash.

**Versions**
 - Forge: 1.12.2-forge-14.23.5.2854
 - Flan's Mod: Flan's Mod-1.12.2-5.5.2

**Crash Log**
[crash-2020-08-01_21.56.25-client.txt](https://github.com/FlansMods/FlansMod/files/5011244/crash-2020-08-01_21.56.25-client.txt)

Please help, this is ruining my Flan's Experience.

**Comment by ChrisLane** [comment]
You're using an old version of the mod. Please upgrade
https://github.com/FlansMods/FlansMod/releases
