### ISSUE TITLE
Sentry guns levetaiting about 3 blocks when placed and not shooting enemies

### ISSUE THREAD

**Issue by RoggyRogg** [FlansMods/FlansMod#1269]
**Describe the bug**
When I place a sentry, the sentry raises up 3 or so blocka above the ground and sits there. The barrel dissapears

**To Reproduce**
1. Place down a sentry gun
2. (I've had one instance so far where it's fallen to the ground}

**Expected behaviour**
The sentry gun to not levitate at all

**Screenshots**
![image](https://user-images.githubusercontent.com/69091343/89180315-7053d700-d589-11ea-8b1b-ac9cafee5fa4.png)
![image](https://user-images.githubusercontent.com/69091343/89180485-c32d8e80-d589-11ea-9fe9-254c4d3e78a4.png)

**Versions**
 - Forge: 1.12.2-forge-14.23.5.2854
 - Flan's Mod: Flan's Mod-1.12.2-5.5.2

**Comment by ChrisLane** [comment]
You're using an old version of the mod, this was fixed in the following pull request that can be found by searching "sentry" in the issues section.
https://github.com/FlansMods/FlansMod/pull/983

Please download the latest version of the mod from here: https://github.com/FlansMods/FlansMod/releases
