### ISSUE TITLE
items don't work

### ISSUE THREAD

**Issue by The-Computerking** [FlansMods/FlansMod#1271]
I whent into a minecraft world and looked at the items and some of the tabs where empty, blocks where gliched and there wasn't any vehcles or guns

**Comment by ChrisLane** [comment]
Sounds like you didn't install any content packs. https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod

Closing for not following the issue reporting guidelines: https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting
