### ISSUE TITLE
Cannot shoot entities which doesn't have any blocks behind them

### ISSUE THREAD

**Issue by ComradeAlexi** [FlansMods/FlansMod#1272]
I cant seem to damage anything which doesn't have a block behind them and it makes fighting them in an open field or mountain very difficult. the firing animation and recoil still happens but no ammo is consumed or firing sound is played. 

i am using the 12.2 version of the mod. please help

**Comment by Lextona** [comment]
Yes! Someone please help! I've been having this same issue, but i've discovered that it could be due to a conflicting mod, i'm just not sure which.

**Comment by Lextona** [comment]
ComradeAlexi! I've found out that MalisisCore and MalisisDoors are causing this issue, if you have them in your pack remove them and it should work :D

Hopefully this works for you and I wish you well!
