### ISSUE TITLE
Part Crafting Table Not Working

### ISSUE THREAD

**Issue by Logybear18** [FlansMods/FlansMod#1274]
**Describe the bug**

The part crafting table does not work.. when i place it and right click it nothing happens
**To Reproduce**
Steps to reproduce the behaviour:
1. 
2. 
3. 
4. 

**Expected behaviour**

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 1.7.10
 - Flan's Mod: 1.7.10

**Additional context**

**Comment by ChrisLane** [comment]
I don't think the part crafting table was ever completed. It's not supposed to do anything at the moment.

**Comment by Logybear18** [comment]
> I don't think the part crafting table was ever completed. It's not supposed to do anything at the moment.

well then how am i supposed to craft any parts then?

**Comment by ChrisLane** [comment]
The content pack pages provide links to a page showing their recipes:
https://flansmod.com/content-packs
