### ISSUE TITLE
Weird Null issues during launch.

### ISSUE THREAD

**Issue by Buff555** [FlansMods/FlansMod#1277]
**To Reproduce**
Steps to reproduce the crash:
1. Press play and wait for forge to initialize Flans Apocalypse then crash.
2. 
3. 
4. 

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 14.23.5.2847
 - Flan's Mod: 5.5.2

**Crash Log**

https://pastebin.com/RgD1GLJ1

**Additional context**

Even after removing Flans Apocalypse and it's config files, it rebuilds the files and crashes.

**Comment by Liruxo** [comment]
It seems you are using an outdated version. Please follow the instructions at https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod to install the latest version
