### ISSUE TITLE
game gets stuck in a loading loop and has to be forced to close when I try to pick up a titan back into my inventory

### ISSUE THREAD

**Issue by Gurglebelly** [FlansMods/FlansMod#1279]
**Describe the bug**

So I've been playing in a new survival world with flan's mod, and every time i try to pick up any titan after I break it, the game gets stuck in an infinite loading loop and I am forced to close the game and afterwards I loose the titan. this may be because i added flan's mod to FTB revelations, but I am no modded expert and would like to play normally
**To Reproduce**
Steps to reproduce the behaviour:
1. add flan's mod, the titan content pack, and the modern warfare pack to FTB revelations
2. place down a titan of any type
3. break it and an untextured cube should drop
4. try to pick up the cube and this will happen
5. when you finish loading up after you were forced to close the game the titan will be gone not in your inventory not on the ground
**Expected behaviour**

What's supposed to happen is you will be able to pick the titan up normally and do whatever you needed to do with it in your inventory

**Versions 
 - Forge: 14.23.5.2846
 - Flan's Mod: 5.5.2

**Comment by ChrisLane** [comment]
It seems you are using an outdated version. Please follow the instructions at https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod to install the latest version
