### ISSUE TITLE
Repeat Crashing apon start up - Lastest Version of Flans and Forge

### ISSUE THREAD

**Issue by UneducatedCumt** [FlansMods/FlansMod#1280]
**To Reproduce**
Steps to reproduce the crash:
1.  Download Lapito's Galacticraft - Twitch 
2.  Install Flans Mods - Excluding the Apocalypse Extension and Zombie - Install all other content for 1.12.2
3. Install the latest Forge version 
4. Load game = crash

**Screenshots**

**Versions (please complete the following information)**
 - Forge: Minecraft Version: 1.12.2 (modded) forge-14.23.5.2854
 - Flan's Mod: 1.12.2 5.5.2 

**Crash Log**

**Additional context**

**Comment by ChrisLane** [comment]
Please read the issue guidelines. You're on an old version of the mod.

**Comment by UneducatedCumt** [comment]
> Please read the issue guidelines. You're on an old version of the mod.

please send me the lastest version link

**Comment by ChrisLane** [comment]
> ``

It's available at the link you ignored
