### ISSUE TITLE
Textures not working with some Guns?

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#1281]
G'Day mates,

I really tried hard finding the issue why some guns may not be working. Well it's just, some are working and have the 3d texture and some only have the texture of what is shown in the hotbar.

Here is an example picture what it looks like.

![Screenshot (93)](https://user-images.githubusercontent.com/67586937/90424352-4688cd00-e0be-11ea-83a9-85e6424af129.png)

I've put the main Flans Mod into the mod folder as normal and the content in the Flan folder. I am really curious about what I am doing wrong.

Have a good one lads, I appreciate every help and answer!
Best Regards 
xDawnshadow

**Comment by ChrisLane** [comment]
Looks like a place able gun to me. You'll need to right click it on a block.

**Comment by ghost** [comment]
I really haven't thought about that. I thought I could hold an MG42 per Hand. Thanks for the Answer, saved my dumbness xD
