### ISSUE TITLE
Mounted Machine guns aiming down 

### ISSUE THREAD

**Issue by Chinese-Chef** [FlansMods/FlansMod#1283]
The mounted guns in flans mod aim down in 1.12.2 and 1.8.9 which are the only versions I know that do that as I haven't tried any of the other versions yet. Anyway is there anyway of fixing this problem

**Comment by Liruxo** [comment]
Please follow https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting
I am not able see what exactly your issue is, nor am i able to help you in any way with the information provided

**Comment by Chinese-Chef** [comment]
> Please follow https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting
> I am not able see what exactly your issue is, nor am i able to help you in any way with the information provided

the issue-reporting has nothing to help me and do i need to show proof like a screenshot or video?

**Comment by ChrisLane** [comment]
You're likely using an old version of the mod, this issue was fixed a long time ago. Please read and follow the information from the link @Liruxo posted fully.

Closing for not using issue templates.
