### ISSUE TITLE
Crash when putting down a vehicle

### ISSUE THREAD

**Issue by ELPROFYTB** [FlansMods/FlansMod#1284]
**To Reproduce**
Steps to reproduce the crash:
1. install version 5.6-beta8 on either server or client
2. launch pack as normal, close pack, import any content pack with vehicles.
3. launch pack again, go into either server or single player world.
4. place any vehicle
5. crash

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 1.12.2-forge1.12.2-14.23.5.2846
 - Flan's Mod: version 5.6-beta8

**Crash Log**

Crash add [crash-2020-08-27_11.55.51-server.txt]
**Additional context**
(https://github.com/FlansMods/FlansMod/files/5135643/crash-2020-08-27_11.55.51-server.txt)

**Comment by ChrisLane** [comment]
Do you have the Simple Parts Pack installed?
