### ISSUE TITLE
Green dots and weird blue trail

### ISSUE THREAD

**Issue by XnsaneGaming** [FlansMods/FlansMod#1285]
**Describe the bug**

where ever look there are green dots and when I shoot a gun a blueish trail appears and mobs turn green If I look at them

**To Reproduce**
Steps to reproduce the behaviour:
1. I installed a different mod
2. logged into a singleplayer world
3. looking around for a little bit
4. green dots appear

**Expected behaviour**

 just to play around with mods
**Screenshots**

https://i.imgur.com/ORJHMty.png
**Versions (please complete the following information)**
 - Forge: 1.12.2
 - Flan's Mod: 5.5.2 

**Additional context**

**Comment by ChrisLane** [comment]
You've entered debug mode, that should go away if you press the F10 key.

Also, you're on an old version of the mod. I suggest installing a newer version as recommended in our issue guidelines.
https://github.com/FlansMods/FlansMod/releases
