### ISSUE TITLE
F5 in a plane made crash

### ISSUE THREAD

**Issue by yusuf72100** [FlansMods/FlansMod#1286]
**Describe the bug**
When I try to going in third person in a plane or in a aerial object, minecraft gonna to crash. But in a earthly vehicle, the 3rd person apair normaly.

**Versions (please complete the following information)**
 - Forge: 1.7.10 1614
 - Flan's Mod: customized

**Comment by ChrisLane** [comment]
1.7.10 isn't supported, sorry https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting
