### ISSUE TITLE
Flans 5.5.2 (1.12.2) Mountable Guns unable to aim, go two blocks higher.

### ISSUE THREAD

**Issue by chickenoodlez** [FlansMods/FlansMod#1287]
Steps to reproduce the behaviour:
1. Place a sentry gun or any other mountable machine gun.

Mountable guns can't aim or place properly. Watch the video, sums up everything.
IE Sentry, Browning, etc

https://drive.google.com/file/d/1XqSC4X4LwSNo4wkHiAu6txcXZyBbuYqG/view?usp=sharing

**Versions (please complete the following information)**
 - Forge: forge-14.23.5.2854
 - Flan's Mod: Flan's Mod-1.12.2-5.5.2

![vlcsnap-2020-09-13-10h51m01s100](https://user-images.githubusercontent.com/71221884/93021126-1d6d3680-f5af-11ea-84aa-779e106542a7.png)
![vlcsnap-2020-09-13-10h51m13s133](https://user-images.githubusercontent.com/71221884/93021129-1f36fa00-f5af-11ea-97e8-d1490ec63d1f.png)

**Comment by ChrisLane** [comment]
https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting
