### ISSUE TITLE
Guns aren't aiming properly, Sentry is misplaced. 1.12.2 Glitch

### ISSUE THREAD

**Issue by chickenoodlez** [FlansMods/FlansMod#1288]
**Describe the bug**

When I place machine guns like the Browning on top of blocks, and I right click to fire them, regardless of how I pan the weapon, the tilt is always max to the bottom, and is therefore impossible to aim. Also reloading seems broken. The guns basically point down. 

The Sentry gun is also placing too high, in the incorrect spot two blocks higher on Y.

**To Reproduce**
1. Place block in front of player
2. Take mountable machine guns from Flansmod, right click to place on top of block.
3. It mounts
4. Right click again to use the weapon
5. Will not aim properly, pointed downwards.

1. Get sentry gun from folder of items
2. Place on any block.
3. Observe that its two blocks higher than initially placed. 

Further presentation of both issues in video [here](https://drive.google.com/file/d/127q8pmKi3GaEeEwiHwlVz03DkiyjYiZW/view?usp=sharing)

**Expected behaviour**

Machine guns will aim normally and sentry gun will place on top of blocks on desired place.

**Screenshots**

![vlcsnap-2020-09-13-10h51m01s100](https://user-images.githubusercontent.com/71221884/93114044-12d2a000-f688-11ea-8f89-c3bae26942a1.png)
![vlcsnap-2020-09-13-10h51m13s133](https://user-images.githubusercontent.com/71221884/93114047-136b3680-f688-11ea-9cc0-e869a54daaab.png)

**Versions (please complete the following information)**
 - Forge: 1.12.2-forge-14.23.5.2854
 - Flan's Mod: Flan's Mod-1.12.2-5.5.2
Modern Warfare-Content Pack-1.12.2-5.5.2
Simple Parts-Content Pack-1.12.2-5.5.2
WW2-Content Pack-1.12.2-5.5.2

**Additional context**
 No errors or crashing.
Other mods
<img width="218" alt="mods" src="https://user-images.githubusercontent.com/71221884/93114281-680eb180-f688-11ea-986b-6acadee4dfc1.PNG">

**Comment by ChrisLane** [comment]
https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting
You're on an old version of the mod

**Comment by chickenoodlez** [comment]
That's not true, 5.5.2 is the latest for 1.12.2

**Comment by ChrisLane** [comment]
The reason I'm posting that link is because if you had read the instructions fully or even searched existing issues before creating your issues, you would know that 5.5.2 is not the latest version and that these bugs were fixed a very long time ago.

The following lines from that link are relevant here:
> - **Ensure you are using the [latest version](https://github.com/FlansMods/FlansMod/releases)**.
You can follow this tutorial, just make sure to use the latest (**including beta**) version:
[Installing FlansMod](https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod)

> - Ensure the issue has not already been reporting by using the search feature.

**Comment by chickenoodlez** [comment]
Ohh gotcha, those are the betas. I'll try them

**Comment by chickenoodlez** [comment]
How do I add these updates into minecraft?
