### ISSUE TITLE
Minecraft AVP/Flans Mod Crash 1.12.2

### ISSUE THREAD

**Issue by spiderking23** [FlansMods/FlansMod#1295]
**To Reproduce**
Steps to reproduce the crash:
1. Open a game with Flans mod (Newest version)
2. Place out a gun modification table, and get yourself a gun (AK-47 for my crash)
3. Shift Click it while the Gun Modification table is open.
4. Game Crashes.

**Versions (please complete the following information)**
 - Forge: 1.12.2-14.23.5.2854
 - Flan's Mod: 

**Crash Log**
https://gist.github.com/spiderking23/f9e399caf9cd21a8d67c54e4ac0c90ee

**Additional context**
Minecraft AVP mod is also downloaded and installed, but none of its assets were present.

**Comment by ChrisLane** [comment]
Hi, this is fixed in more recent versions of the mod.
Please use the files available here: https://github.com/FlansMods/FlansMod/releases/
