### ISSUE TITLE
mech with ai core for apocalypse doesen't nuke 

### ISSUE THREAD

**Issue by fbifridays** [FlansMods/FlansMod#1297]
**Describe the bug**
when spawning any mechs with ai core, it just stands there. it is supposed to spin around nuking the entire map but does not do so
**To Reproduce**

1.craft the vehicle crafting table
2.  craft any mechs with an ai core
3. spawn the mech

**Expected behavior**
proto titan spins around and shoots

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 1.12.2-14.23.5.2854
 - Flan's Mod: 5.6 beta 8

**Additional context**

**Comment by voidegg** [comment]
If you start minecraft instance with gradlew run client it should work but i dunno how to do it

**Comment by fbifridays** [comment]
> If you start minecraft instance with gradlew run client it should work but i dunno how to do it

alright ill try that

**Comment by fbifridays** [comment]
> If you start minecraft instance with gradlew run client it should work but i dunno how to do it

where could i get gradlew run client

**Comment by voidegg** [comment]
I have no idea i found this issue somewhere in ftb forums and someone said its a problem with the minecraft launcher

**Comment by voidegg** [comment]
Can someone please fix this issue? I really want to play acop with my friends

**Comment by fbifridays** [comment]
> Can someone please fix this issue? I really want to play acop with my friends
same bro
