### ISSUE TITLE
Flan's Mod Uploaded to CurseForge

### ISSUE THREAD

**Issue by spruill7716** [FlansMods/FlansMod#1298]
Not a bug, but rather a heads up. I'm not to sure if this is the original creator or not, but someone has uploaded Flan's Mod along with a number of content packs to CurseForge recently. 

[https://www.curseforge.com/members/flansgames/projects](https://www.curseforge.com/members/flansgames/projects)

If it is, there is an issue with CurseForge's auto-install feature. CurseForge installs all the content packs directly into the 'mods' folder instead of the 'Flan' folder, making them useless you manually create the folder and install them yourself. Twitch modpacks are completely unusable with Flan's until this issue is fixed.

**Comment by ChrisLane** [comment]
The uploads are legit but thanks. I believe @jamioflan was looking into the content pack issue so I'll leave this open until that's resolved.

**Comment by jamioflan** [comment]
Fix pushed, should be working once beta9 is approved on Curse
