### ISSUE TITLE
i cant break flag poles even with /kill @e

### ISSUE THREAD

**Issue by justaguyrandom** [FlansMods/FlansMod#1299]
when i try to break flag poles I click I /kill @e I use world edit and nothing happens

Please help me

 - Forge: 1.12.2
 - Flan's Mod: 1.12.2

**Comment by ChrisLane** [comment]
You need to run the `/teams getSticks` command and then right click the flag with the stick of destruction.

**Comment by Wonderingwalker243** [comment]
I also have a problem.I cant destroy the boats with /kill @e and they're stuck next to my base

btw this is modern era for 1.7.10 on technic launcher

**Comment by Wonderingwalker243** [comment]
this is the picture
![2024-06-15_14 32 00](https://github.com/FlansMods/FlansMod/assets/172929783/82a4fd08-e601-4a46-80f8-b0420e266475)
