### ISSUE TITLE
1.12.2 vehicles not ticking and vehicle guns won't shoot 

### ISSUE THREAD

**Issue by beetweenlands** [FlansMods/FlansMod#1301]
**Describe the bug**
i play on 1.12.2 and at first the guns wouldnt shoot and i could use the vehicles but then at one point i place a vichle and i was constantly crashing so i went into forge settings and made it so that any un-tickable entities would just not spawn so after doing that i found out the problem was that the vihicles would not tick too yea also sorry for the bad spelling and writing 
**To Reproduce**
Steps to reproduce the behaviour:
1. spawn a vehicle

**Versions (please complete the following information)**
 - Forge: 1.12.2
 - Flan's Mod: latest 

Edit; i don't know if this helps but the unticked entitys are registered as entity.wheel on damage indictors
edit: i fixed it by reinstalling flans and deleting the config files everything works however i will close it tommorow incase if anything changes then i will post a pull request

**Comment by beetweenlands** [comment]
help me

**Comment by ChrisLane** [comment]
Can you please provide the version number rather than "latest".

**Comment by beetweenlands** [comment]
5.5.2

**Comment by beetweenlands** [comment]
also on a side note what ammo would i need for the BF-901

**Comment by ChrisLane** [comment]
You're using an old version of the mod. I think your problems will be fixed by updating to a newer version https://www.curseforge.com/minecraft/mc-mods/flans-mod-5-5-2/files
