### ISSUE TITLE
Manually added mod in modpack The 1.12.2 Pack

### ISSUE THREAD

**Issue by zancii** [FlansMods/FlansMod#1302]
Hello,

i have a problem with your mod, i added it to modpack **The 1.12.2 Pack** but it doesn't work, i contacted modpack support but they couldn't help me and advised me to comment on you, and now i'm here.
I don't even know how to describe the problem, but i will try, when I run modpack it loads 2 out of 7 and creates a crash report and writes that it was caused by flange mod, I will also attach screenshots and crash log.
Screenshot in game:[https://prnt.sc/uybar6](url)
Crash log: [https://pastebin.com/ZRYb9smc](url)

I hope you will be able to help and advise me.
I apologize for the poor English.

**Comment by ChrisLane** [comment]
It looks like you're on an old version of the mod. I think your issues will be fixed with a newer version
https://www.curseforge.com/minecraft/mc-mods/flans-mod-5-5-2/files
