### ISSUE TITLE
Galacticraft-Flan's Mod Conflict, Timing Out Forge/Sponge Server

### ISSUE THREAD

**Issue by spruill7716** [FlansMods/FlansMod#1303]
**To Reproduce**
Steps to reproduce the crash:
1.  Launch rocket into space.

**Versions (please complete the following information)**
 - Forge: 14.23.5.2854
 - Flan's Mod: 5.6.0 Beta 10all
 - Galacticraft: 4.0.2.280

**Crash Log**
- Crash Report: https://gist.github.com/spruill7716/1e1300254b1bbdf6ab08b76f990404f4
- Server Console Spams: https://gist.github.com/spruill7716/6b32cff2ea7bccae9744cfce2d4b205f

**Additional context**
Since installing the most recent Flan's build, any attempt at going to space with Galacticraft ends up timing out the server. Whenever a player launches a rocket, the following: [https://gist.github.com/spruill7716/6b32cff2ea7bccae9744cfce2d4b205f](https://gist.github.com/spruill7716/6b32cff2ea7bccae9744cfce2d4b205f) is spammed in the console and overloads the server. I saw that there were mentions of Flan's mod in '_[flansmod]: Tried to add mp5k to player class gignDualWield1 but the item did not exist_' . Some kind of conflict perhaps? I've submitted another report to Galacticraft for safe measure.

**Comment by ChrisLane** [comment]
I think this has more chance of being a Galacticraft issue
https://gist.github.com/spruill7716/1e1300254b1bbdf6ab08b76f990404f4#file-gistfile1-txt-L43
https://gist.github.com/spruill7716/6b32cff2ea7bccae9744cfce2d4b205f#file-gistfile1-txt-L1202
