### ISSUE TITLE
The Items do not show

### ISSUE THREAD

**Issue by Stone3006** [FlansMods/FlansMod#1304]
**Versions (please complete the following information)**
 - Forge: 1.12.2
 - Flan's Mod: 1.12.2

**Additional context**

I downloaded 3 content packs and I have followed the instructions at the "README" text and nothing shows up exept the workbenches And the paintbucket thats all I see I tried to delete the install again but it is still the same result.

**Comment by ChrisLane** [comment]
Please provide the flan's mod and forge version numbers and your client log. (1.12.2 is the Minecraft version)

**Comment by CesarJH** [comment]
i have the same problem right now on a koopjeserver.nl minecraft server. I dont know how to fix it and someone maybe do. Please let me know, so i can play flans mod with some friends online!!!
