### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by davigsm** [FlansMods/FlansMod#1306]
can I help translate the mod into Brazilian Portuguese?

**Comment by ChrisLane** [comment]
You can!

1. Fork the project.
2. Clone your fork to your computer
3. You will need make language files matching the existing en_us.lang files in each mod and content pack resource location.
For example:
https://github.com/FlansMods/FlansMod/tree/1.12.2/src/main/resources/assets/flansmod/lang
https://github.com/FlansMods/FlansMod/tree/1.12.2/src/main/resources/assets/flansmodapocalypse/lang
https://github.com/FlansMods/FlansMod/tree/1.12.2/run/Flan/Apocalypse%20Pack/assets/flansmod/lang
4. Commit and Push your changes to your fork
5. Open a Pull Request detailing your changes

**Comment by davigsm** [comment]
thanks
