### ISSUE TITLE
Is flans mod dead?

### ISSUE THREAD

**Issue by voidegg** [FlansMods/FlansMod#1309]
I would hate if you ditched support for this mod
But theres a crap ton of bugs and not many new updates...

Btw i will be happy to help with models for vehicles and guns and such so dont be shy to ask.

**Comment by ChrisLane** [comment]
The mod isn't dead, some people still make fixes here and there.
There are currently no plans to update the mod beyond 1.12.2 but people are welcome to submit any changes as a pull request.

**Comment by voidegg** [comment]
If for example i did a new model for the m1911 how do i share it with you guys?
(I dont know anything about coding/modding and such im only good at 3d modeling

**Comment by ChrisLane** [comment]
You would need to submit the change as a pull request on GitHub.
Here's a resource I found that seems to take you through all the steps: https://www.dataschool.io/how-to-contribute-on-github/

**Comment by voidegg** [comment]
Thanks
