### ISSUE TITLE
Crash report and bug with Teams

### ISSUE THREAD

**Issue by Lolikcrafter** [FlansMods/FlansMod#1312]
Steps to reproduce the crash:
1. Add map (/teams addMap <Map> <map>)
2. Connect flags to spawners
3. Open GUI with (or without) Stick of Mapping
4. Name the base and choose a team (i.e "German" (Team 1) and "CCCP" (Team 2) (in "CCCP" all letters are latinic) and set as map a "map")
5. Do /teams addRound Map TDM German CCCP 60 60 (I've also tired do /teams addRound Map TDM germanTeam russianTeam 60 60)
6. Do /teams start
7. And here 1 bug and 1 crash (bug: it's unnable to open a GUI with "G"    crash: When I press "H" to see a score, the game crashes)

**Versions (please complete the following information)**
 - Forge: 14.23.5.2854
 - Flan's Mod: 5.5.2

**Crash Log**
https://gist.github.com/Lolikcrafter/ce288f7fe498340572af394c8786c073

**Additional context**
I do it in a singleplayer with opening to LAN (It doesn't depend upon amount of player on server)
All is done by this tutorial (Basic Setup): https://flansmod.com/teams-tutorial

**Comment by ChrisLane** [comment]
You're on an old version of the mod and I believe this is a duplicate issue. Please get the latest version from CurseForge or GitHub releases.

**Comment by Lolikcrafter** [comment]
> 
> 
> You're on an old version of the mod and I believe this is a duplicate issue. Please get the latest version from CurseForge or GitHub releases.

I've just downloaded v5.6-beta.10 and I still have the same problems.
Can you attach a link to the mod on the CurseForge? Because I can't find it there

**Comment by ChrisLane** [comment]
https://www.curseforge.com/minecraft/mc-mods/flans-mod-5-5-2

**Comment by Lolikcrafter** [comment]
> 
> 
> https://www.curseforge.com/minecraft/mc-mods/flans-mod-5-5-2

What version of the Flan should I use? I've donwloaded "Flan's Mod-1.12.2-5.6.0-beta.10-all.jar" from CurseForge and Teams don't work either.

**Comment by ChrisLane** [comment]
Teams don't work on any version on 1.12.
Here's the existing issue https://github.com/FlansMods/FlansMod/issues/908
