### ISSUE TITLE
Flans Mod Vehicles have a Breakdown when at far cords

### ISSUE THREAD

**Issue by HamsterThatCommitsStuff** [FlansMods/FlansMod#1314]
The Vehicles start to not work render properly after going far out, This has broken most of my server where its a 1:1 earth

Video
https://www.youtube.com/watch?v=8pJziZMYPts
I compared it to a boat, The player walking, and a bunny to show it was only the tank having the mental breakdown

**Comment by JValor2417** [comment]
To clarify, this is for Flans mod 1.12.2, forge-1.12.2-14.23.5.2854.

It is the standard MW pack. I just tested this myself and found the " jitters " start very subtly around 9,000 x 9,000. It increasingly becomes more noticeable every 1,000 x 1,000 blocks. The jitters do not seem to just be a rendering error, but rather the vehicle bouncing around similar to when placed in a wall or underground. This issue does not affect Mechas as far as I can see.

**Comment by Liruxo** [comment]
You may have luck trying the new beta versions (There have been some changes to the rendering), otherwise that seems to be a deeper problem with the way FlansMod handles/renders vehicles. Nevertheless, please use the this guide for future bug reports:
https://github.com/FlansMods/FlansMod/wiki/Issue-Reporting

**Comment by ChrisLane** [comment]
The exact version of the mod and content packs is useful for us to know as well as a client/server log.
This is information that is prompted for in the guide Liruxo posted and in the issue report templates.

**Comment by HamsterThatCommitsStuff** [comment]
Flans Mod Version: Flan's Mod-1.12.2-5.5.2
Packs that are on: 
Machetemen Arms Pack 1.12.2 Update
Modern Warfare-Content Pack-1.12.2-5.5.2
Simple Parts-Content Pack-1.12.2-5.5.2
WW2-Content Pack-1.12.2-5.5.2
Logs:
https://drive.google.com/file/d/18MJN6gojxh1SNsgZdIpTFQIVWLPP5LuM/view?usp=sharing
(edited to show when I placed the vehicle and to take out my name)
I hope this is the info you needed, sorry for not including it with the original post.

**Comment by ChrisLane** [comment]
You're on a very old version, could you try the latest and report back with the same details please?

https://github.com//FlansMods/FlansMod/releases/

**Comment by HamsterThatCommitsStuff** [comment]
Newer logs, most recent version of Flans, Modern Warfare, Simple parts, and WW2 content pack, Machetemen Stayed the same

https://drive.google.com/file/d/1KQuZGjhiocrtHN86y0kdIKJflmQOTIcg/view?usp=sharing
Edited to take out my name, nothing else
(Forgot to put this here, The vehicle continued to do the same as in the video)
