### ISSUE TITLE
Block mounted guns cannot point upwards from default angle

### ISSUE THREAD

**Issue by CheckpointK** [FlansMods/FlansMod#1321]
**Describe the bug**
Block mounted machine guns from the WW2 pack (such as Browning 30 and 50 cal, Vickers, DP-28 etc.) are unable to aim higher than the default downward pointed angle they are placed at. The guns are capable of looking downwards slightly, but not upwards beyond the resting angle when not used by the player. The makes it impossible to shoot anything with them that isn't below the gun.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place any block mounted machine gun
2. Mount gun via right click
3. Attempt to aim upwards, you will not be able to. Tested with many guns and locations

**Expected behaviour**
Block mounted guns expected to be able to aim at least level, but are permanently capped at a low aiming angle. Suspect that the default resting angle is somehow overriding what the maximum vertical angle should be.

**Screenshots**
![2020-11-22_21 43 19](https://user-images.githubusercontent.com/42954833/99902197-ed0eea80-2d0b-11eb-8e9b-b0164847aece.png)
Maximum aiming angle (equal to default angle the gun rests at when not being used by the player)
![2020-11-22_21 43 51](https://user-images.githubusercontent.com/42954833/99902214-06179b80-2d0c-11eb-9447-c479558d49a8.png)
First person max angle, on flat terrain is about 3 blocks ahead of the weapon
![2020-11-22_21 43 53](https://user-images.githubusercontent.com/42954833/99902226-20ea1000-2d0c-11eb-8f0a-ba2374a0960c.png)
First person minimum angle. Looking downwards seems fine, but the upwards maximum angle makes the weapons unusable.

**Versions (please complete the following information)**
 - Forge: 14.23.5.2854
 - Flan's Mod: 5.5.2 (For game version 1.12.2)

**Comment by CheckpointK** [comment]
Although closed without comment, I found a fix myself. Editing the topviewlimit paramater for the guns from 20 to -20 instead allows the guns to move as they should.

**Comment by Liruxo** [comment]
You are using an outdated version. Please follow the instructions at https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod to install the latest beta version
