### ISSUE TITLE
Particles folder not find

### ISSUE THREAD

**Issue by morliy** [FlansMods/FlansMod#1325]
** Describe the bug **
Unlike version 1.7.10 in the Flan 1.12 mod, we no longer find the particles folder allowing us to modify the texture of the flames(guns,missiles), flare (plane), smoke ...

** Expected behaviour **
I expected to find the realistic flames(flare) that we find in the turbos of planes during great acceleration, to reuse the particles of the contents pack of version 1.7.10 (example : global firestorm content pack).

**Screenshot**

https://user-images.githubusercontent.com/75388608/101175067-fe79c000-3644-11eb-9bd8-ec5c6e0f2f52.jpg

**Comment by jamioflan** [comment]
I believe this is a Flans Mod Plus feature, so should be directed to https://github.com/Unknown025/Flans-Mod-Plus
