### ISSUE TITLE
Cannot utilize the teams feature

### ISSUE THREAD

**Issue by ianespana** [FlansMods/FlansMod#1327]
**Describe the bug**
Trying to utilize the teams feature does not work correctly. After setting everything up on the server I am planning to use, I start a round but the main teams menu does not appear. Checking the console on the client gives me the following warning: `[Client thread/WARN] [flansmod]: Problem in landing page!`

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup teams and begin a rotation
2. Try to open the teams main menu

**Expected behaviour**
The teams main menu should pop up and display the "Choose a team" screen, allowing players to join any ongoing rounds. Instead it does nothing

**Screenshots**
N/A

**Versions (please complete the following information)**
 - Forge: 1.12.2 - 14.23.5.2854
 - Flan's Mod: 5.6.0-beta.10

**Comment by The1Dominater** [comment]
I am having the exact same issue and I am running Flans 1.12.2 as well.

**Comment by Fischchen** [comment]
I have the same Issue running flans mod 5.5.2 on a 1.12.2 Server

**Comment by Fischchen** [comment]
@jamioflan this seems to be a  important feature,  according to the website. So it would be nice from someone with Java knowledge to try and fix this.

**Comment by jamioflan** [comment]
Closed in favour of #1354
