### ISSUE TITLE
Bugged Texture 

### ISSUE THREAD

**Issue by Just-Yenzo** [FlansMods/FlansMod#1328]
**Describe the bug**
Hello, I am creating a RolePLay server. Before it was in 1.7.10 and now in 1.12.2. Would there be a way to migrate the content packs to 1.12.2 because currently the textures are in Purple and black ... If there is a person who is available to help me modify or make new packs if this it's impossible it would be beautiful

**Expected behaviour**

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 1.12.2 
 - Flan's Mod: 1.12.2

**Comment by morliy** [comment]
Hi!

Here you have an example of updating (1.7.10 to 1.12) in french : 
https://www.youtube.com/watch?v=83CgM_WcXqg

make the same things. DONT FORGET: No uppercases in 1.12 (for models; textures;skin...)

**Comment by Just-Yenzo** [comment]
> Hi!
> 
> Here you have an example of updating (1.7.10 to 1.12) in french :
> https://www.youtube.com/watch?v=83CgM_WcXqg
> 
> make the same things. DONT FORGET: No uppercases in 1.12 (for models; textures;skin...)

Thank you so much. My native language being French I fully understand the tutorials.
