### ISSUE TITLE
Fix MGs vertical visual aim inverted to practical aim

### ISSUE THREAD

**Issue by Pavelsvt** [FlansMods/FlansMod#1329]
When you place down fixed MG (Bren, Browning, etc), if you aim higher, you hit lower and vice versa. Not only is the gun non aligned to the place where it practicaly aims, but you also have to move your mouse towards you if you want to hit higher elevated places. 
PS: Browning .30cal and .50 shakes even when it currently doesnt fire.

**Comment by ChrisLane** [comment]
Could you please confirm which version of the mod you're on?

**Comment by Pavelsvt** [comment]
MC 1.12.2
Flans 5.6.0 Beta10

**Comment by Pavelsvt** [comment]
Any news?
