### ISSUE TITLE
Unable to spawn vehicle

### ISSUE THREAD

**Issue by RyanCR3000** [FlansMods/FlansMod#1331]
**Describe the bug**
Auto Crashes my game or server as soon as I spawn in a Vehicle from any content pack. (weapons work fine).

**To Reproduce**
Steps to reproduce the behaviour:
1. Take any civilian Vehicle content packs
2. Enter a world
3. Pick a vehicle
4. Game Crash

**Expected behaviour**
Expected to spawn the vehicle in. Instead game crash.

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 1.7.10 10.13.4.1558
 - Flan's Mod: latest

**Additional context**

**Comment by ChrisLane** [comment]
Sorry but we don't support 1.7.10 versions anymore
