### ISSUE TITLE
crashes as soon as i make a new world/enter a world that is the correct version

### ISSUE THREAD

**Issue by yeah-bananacannon** [FlansMods/FlansMod#1332]
**To Reproduce**
Steps to reproduce the crash:
1. Download 1.7.10-Forge10.13.4.1558-1.7.10
2. Download Flans mod plus-1.7.10-4.10.0-1.0.3, Flans-Simple-Parts-Pack-1.7.10, Flans-World-War-Two-Pack-1.7.10, Global Firestorm v3.2 - Thunder run (1.7.10), Machetemen-Arms-Pack-Mod-1.7.10
3. Put the main flans mod in the mod folder, and the others in the "Flans folder"
4. 

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 1.7.10-Forge10.13.4.1558-1.7.10
 - Flan's Mod: 1.7.10-4.10.0

**Crash Log**
<\The game crashed whilst unexpected error
Error: java.lang.IndexOutOfBoundsException
Exit Code: -1 
[mc flan crash 1.7.10.txt](https://github.com/FlansMods/FlansMod/files/5704684/mc.flan.crash.1.7.10.txt)

-->

**Additional context**

**Comment by ChrisLane** [comment]
Sorry, we don't support 1.7.10 anymore. Perhaps try searching old issues.
