### ISSUE TITLE
Black screen changing gamemode, to third person, and hiding HUD

### ISSUE THREAD

**Issue by lordofspearton** [FlansMods/FlansMod#1333]
**Describe the bug**
Black screen when changing gamemode, to third person, or hiding HUD

Steps to reproduce the behaviour:
1. press F1 or F5, type /gamemode
2. Black Screen

**Expected behaviour**
Change gamemode, hide HUD, ect.

**Versions **
 - Forge: 14.23.5.2854
 - Flan's Mod: 5.5.2

**Additional context**
Mods: https://pastebin.com/Vb2DASsd
Flan's seems to be causing the conflict, running the game with only Flan's does not produce the error. Running game without Flan's also does not produce the error.
Unable to find the other conflicting mod(s) at this time.

**Comment by ChrisLane** [comment]
Hi, you seem to be using an old version. Please find the latest version at https://github.com/FlansMods/FlansMod/releases or CurseForge.
