### ISSUE TITLE
Titan Rotation is Extremely Slow

### ISSUE THREAD

**Issue by CheckpointK** [FlansMods/FlansMod#1335]
**Describe the bug**

When piloting one of the Titans from the Titan Pack the vehicle turns extremely slowly. The vehicle is constantly dragging behind where the player is aiming to look at a snails pace. A 180 degree rotation takes 10 seconds for the titan to complete. Previous game versions of Flans mod had the Titans capable of matching the player's mouse speed and did not lag behind at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn and of the Titan Pack titans (proto, alpha, zero)
2. Mount the Titan
3. Look in any direction. You will notice that the titan very slowly rotates to catch up.

**Expected behaviour**
The titans when mounted should rotate the cockpit/arms at the same rate the player moves their mouse in order to keep pace.

**Versions (please complete the following information)**
 - Forge: 14.23.5.2768
 - Flan's Mod: 5.6 beta 10

**Additional context**
If I had been used the current version of Flans I might assume this snail pace rotation was intentional, but all previous game versions of the mod since Titans have been included did not do this in singleplayer. I faintly remember this may have been an issue for multiplayer servers in past game versions, but never in single player worlds.

**Comment by ChrisLane** [comment]
This is intentional behaviour, it was perhaps broken in previous versions.
