### ISSUE TITLE
Bug with Modern Warfare

### ISSUE THREAD

**Issue by Just-Yenzo** [FlansMods/FlansMod#1337]
Hello, I have a problem the outfits flan's mods are corrupted when I put the mods: Vic's Modern Warfare Mod. Do you have a solution to avoid this?

Version : Forge 1.12.2, flan's 1.12.2, Vic's Modern Warafare Mod  1.12.2

**Comment by jamioflan** [comment]
I suspect Vic has used the same IDs for the armour or the same model files, and so the packs are not compatible. Could you take up the issue with Vic?
