### ISSUE TITLE
Part Table still can't be accessed

### ISSUE THREAD

**Issue by epicgamer11** [FlansMods/FlansMod#1338]
I've got a Problem where I can't open the Part Crafting Table (one of the most essential features of the mod)
I am currently running 5.6.0 beta 10 and I also tried beta 3, where it was supposedly fixed.
Content Packs I have installed:
Simple Parts
Modern Warfare
Mech Parts
Titans
WW2 
Apocalypse
Utility

I've already checked and only found one post where it was supposedly fixed in a the beta3 version.
Forge 1.12.2

**Comment by jamioflan** [comment]
The part table doesn't do anything and isn't required for anything
