### ISSUE TITLE
Weapons box consumes all items when opened.

### ISSUE THREAD

**Issue by Maxian13** [FlansMods/FlansMod#1345]
**Describe the bug**
When I open a weapons box (i.e. British Weapons Box) and click on a weapon to craft (i.e. Lee Enfield) all required materials (i.e. Iron Ingots and Logs) disappear from inventory. Not just the required amount to craft the weapon disappears but literally all items of the same type required to craft the weapon disappear. Items will reappear when opening a chest, gun table, furnace, etc. a second time.

**To Reproduce**
Steps to reproduce the behaviour:
1. place a weapons box (i.e. British Weapons Box)
2. gather resources (Iron and Logs)
3. right click on the weapons box to open the crafting menu
4. left click on a weapon (i.e. Lee Enfield). All Logs and Iron will disappear
5. You can then right click on the weapons box again without selecting a gun for the resources to reappear in the inventory.

**Expected behaviour**
Materials required to craft weapon are consumed when CRAFT is clicked. Currently all stacks of items required to build a weapon that is selected are deleted.

**Versions**
 - Forge: forge-14.23.5.2854
 - Flan's Mod: 5.7.0-beta.2

**Additional context**
1. Additional Flan's Mod Content Packs used are: Modern Weapons Pack, Simple Parts Pack, WW2 Pack, Ye Olde Pack.
2. Items Reappearing in inventory is not fully reproducable.
3. Any required material to build items will disappear. (i.e. when building gold desert eagle gold ingots will disappear).
4. Sometimes only the Iron will disappear.
5. Items do not disappear instantly. They quickly 'drain' in ~0.5 seconds.
6. This issue does not occur on the 5.5.2 version of flans.

**Comment by BrennanMcDonald** [comment]
Possibly related to https://github.com/FlansMods/FlansMod/commit/66355cc29df50a4e8b3fb513d424ff4c7da4224d#diff-c3dd6c2fb7acb69f9482ef6cd4430239bb792439dba0ea92773c8e04f8dfb363
