### ISSUE TITLE
I played the Flans mod on the 1.8 for a while. Then I switched to the 1.12.2 and all the Guns aim too low. For example if i aim With a gun on a sheep, then shoot, the gun shoots the ground. not the sheep.

### ISSUE THREAD

**Issue by Leo-2668** [FlansMods/FlansMod#1371]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. 
2. 
3. 
4. 

**Expected behaviour**

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 
 - Flan's Mod: 

**Additional context**

**Comment by craftlofer** [comment]
i play on 1.12.2 and doesn't happen to me, maybe a conflict with a mod of yours?

**Comment by Leo-2668** [comment]
Thanks. It indeed was because of a mod
