### ISSUE TITLE
WW2 Content pack Lancaster not craftable.

### ISSUE THREAD

**Issue by balatamoghna** [FlansMods/FlansMod#1398]
**Describe the bug**
The crafting recipe for Lancaster is either incorrect or bugged as I am not able to craft the plane using the vehicle crafting table.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get the required materials as shown in the vehicle crafting table.
2. Click the Lancaster plane model
3. Click the enabled crafting button.
4. Nothing happens [Bugged]

**Expected behaviour**
When the button is clicked, the materials should be taken and then a lancaster plane should be crafted.

**Screenshots**
![image](https://user-images.githubusercontent.com/480968/124382283-38e33280-dce4-11eb-908f-684f8e4cc411.png)
![image](https://user-images.githubusercontent.com/480968/124382287-40a2d700-dce4-11eb-8773-38173c599d50.png)
![image](https://user-images.githubusercontent.com/480968/124382297-4ac4d580-dce4-11eb-93f1-5b9bbdbbe047.png)

**Versions (please complete the following information)**
 - Forge: 1.12.2-14.23.5.2855
 - Flan's Mod: 1.12.2-5.10.0
 - WW2 Content Pack: 1.12.2-5.7.2

**Comment by balatamoghna** [comment]
I believe its because the scroll button hides the entire recipe and only contents shown in the material grid inside the vehicle crafting table is taken. Then when it tries to craft, it doesn't have all the required materials and therefore doesn't craft it.
I think that's the case cause when in top page the crafting button is enabled even when I don't have the materials in the last row(hidden in the top 3 rows). Still a bug but maybe it can be solved by simply displaying the entire grid.

**Comment by PreedomCL** [comment]
I was having the same problem so I looked into the WWII Content Pack code for the Lancaster and found that it also requires 5 yellow dye to craft.

**Comment by Jaika1** [comment]
> 
> 
> I was having the same problem so I looked into the WWII Content Pack code for the Lancaster and found that it also requires 5 yellow dye to craft.

I can second this. The required 5 yellow dye is not visible in the recipe in the Vehicle Crafting Table.
