### ISSUE TITLE
3d weapons not working wolff's star wars pack

### ISSUE THREAD

**Issue by drame72** [FlansMods/FlansMod#1400]
every time I use a star wars gun in 1.7.10 it's not 3d the same goes for clone wars survival but I don't care about that as much. I'm sorta new to using flans but the addon is in the flans folder, I am on mac but that has no effect on the gameplay. everywhere I look this isn't an issue, Idk if it's just the file I downloaded. I have other mods, but they are minor and this was an issue from when I only downloaded this. I have other addons for flans too and the weapons are 3d but my star wars ones should be too. on technic launcher I have a mod pack downloaded and its weapons are 3d and it's the same mod but with less stuff. If someone can help me out, I would be very grateful.

My modded world
![Screen Shot 2021-07-28 at 1 07 37 AM](https://user-images.githubusercontent.com/88074963/127273093-d31ac44a-a3c1-4987-8aa9-9d467767123d.png)

Modpack on technic launcher
![Screen Shot 2021-07-28 at 1 12 33 AM](https://user-images.githubusercontent.com/88074963/127273171-c2b1807d-2fc1-49da-abda-5a6a8080d5b0.png)

one of wolf's screenshots
![Screen Shot 2021-07-28 at 1 14 19 AM](https://user-images.githubusercontent.com/88074963/127273223-90f7004f-6553-43f3-98db-339f34261c91.png)

 - Forge:  1.7.10-forge10.13.4.1614-1.7.10
 - Flan's Mod: Wolff's Star Wars Pack
https://flansmod.com/content-pack/758/Wolff039s_Star_Wars_Pack?search=star+wars&sort=_RELEVANCE&direction=DESC&seed=1627452061881.3&pageon=1

**Comment by Kiritoslayer115** [comment]
Were u able to find a solution? Having same issue.
