### ISSUE TITLE
Land vehicles consuming fuel very fast.

### ISSUE THREAD

**Issue by phobosad** [FlansMods/FlansMod#1416]
In the most recent version of flan's mod at time of writing, 5.10.0, the land vehicles seem to consume fuel at an unreasonable rate. I have viewed another bug report like this claiming it to be fixed, but this doesn't seem to be the case.

**Comment by Jomosoto** [comment]
Fixed in https://github.com/FlansMods/FlansMod/pull/1456. This can be closed.
