### ISSUE TITLE
How to disable Blockbreak to Vehicles?

### ISSUE THREAD

**Issue by Stormez1998** [FlansMods/FlansMod#1437]
Vehicles can Destroy blocks. i run a Server on Magma (Hybride Server PL and Mods) and Vehicles can destroy WorldGuard Protectet Regions. Is there a way to turn off BlockBreak to the Vehicles?

Steps to reproduce the behaviour:
1. /teams vehiclesBreakBlocks false (Nohing happend)

**Expected behaviour**
That Vehicles deal damage to Players but no Block Break

**Versions (please complete the following information)**
 - Forge: 1.12.2-forge-14.23.5.2855
 - Flan's Mod: Flan's+Mod-1.12.2-5.10.0

Thanks

**Comment by pixelrider2000** [comment]
I don't know if this is what you mean, but 'vehiclesBreakBlocks' refers **only** to collision damage. This means vehicles will no longer break blocks, when colliding with them. However they will still break blocks when e.g. dropping bombs or the like.
I think what you are looking for is '/teams explosions false', this will prevent vehicles from breaking blocks with their weaponry.

Let me know if this solved your problem ;)

**Comment by Stormez1998** [comment]
Hay, i tryed that. But that disable it only when u play in the teams Mode or? Bcs i dont use teams xD

**Comment by Stormez1998** [comment]
Oh my Bad i thougt u mean my command i already tryed. That worked perfekt. :)

**Comment by pixelrider2000** [comment]
Glad it works now!
Please close this issue though ;)

**Comment by Stormez1998** [comment]
Thanks!
