### ISSUE TITLE
Adding a licence

### ISSUE THREAD

**Issue by jamioflan** [FlansMods/FlansMod#302]
Adding a proper licence to the mod in preparation for the website launch.
I've decided on a Creative Commons Non-Commercial Share Alike licence, and so now I just need the relevant documents put in the right places and added to the build scripts

http://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-sharealike-(cc-nc-sa)

**Comment by ChrisLane** [comment]
@MarcinWieczorek Looks like I didn't check my commit two years ago and it went unnoticed until today.
I've re-added the license.
