### ISSUE TITLE
Flans mod zombie gamemode crash

### ISSUE THREAD

**Issue by daPoseidonGuy** [FlansMods/FlansMod#639]
Hi, in Flans 4.9.0, I make my map with the two flags for the teams, I tie them to a player spawner and give them each a different team, and then i do /teams addRound default ZOM team1 team2 100000 100000

Right when i do /teams start, it gives me the option for teams none/builder, spectator and none/builder, then it says infection in 10 seconds, and in to seconds it crashes, with this in the log:

[B#256]  Description: Exception in server tick loop
[B#256]  
[B#256]  java.lang.NullPointerException: Exception in server tick loop
[B#256]     at com.flansmod.common.teams.GametypeZombies.zombifySomeone(GametypeZombies.java:68)
[B#256]     at com.flansmod.common.teams.GametypeZombies.tick(GametypeZombies.java:58)
[B#256]     at com.flansmod.common.teams.TeamsManager.tick(TeamsManager.java:183)
[B#256]     at com.flansmod.common.CommonTickHandler.tick(CommonTickHandler.java:44)
[B#256]     at cpw.mods.fml.common.eventhandler.ASMEventHandler_15_CommonTickHandler_tick_ServerTickEvent.invoke(.dynamic)
[B#256]     at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[B#256]     at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[B#256]     at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
[B#256]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
[B#256]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[B#256]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[B#256]     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Any ideas??
Thanks for your time,
Poseidon5001

**Comment by ChrisLane** [comment]
Could you please post a full crash log pasted to a service such as http://paste2.org or http://pastebin.com and post the link here.
