### ISSUE TITLE
Console Spam w/ NEI

### ISSUE THREAD

**Issue by eschereatseverything** [FlansMods/FlansMod#647]
Using the newest available version of Flans mod for 1.7.10 (4.9.0), the Modern Warfare weapons pack and the Simple Parts pack installed along with NEI. As soon as the workbenches are shown in NEI, the console is suddenly spammed with errors and exceptions... the issue seems to be with the items showing up in NEI as fire with unlocalized names. Right clicking these "Fire Blocks" also causes a crash.

I apologize in advance for not providing a crash report, however i'm not at my own PC to do so, I will provide one once I get home. The console spam / crash can be recreated quite easily, however.

**Comment by ModifiedSrcCode** [comment]
It's supposed to be like that, and your not supposed to be able to right or left click on them... Flan should make that clear sometime =P

**Comment by eschereatseverything** [comment]
Seems like a strange choice on Flan's part... I cant understand forcing a crash when right clicking or the continuous stream of what look like debug messages every tick or so, although I genuinely dont remember what they are, as I've since removed Flans and its modules from my servers.

**Comment by ChrisLane** [comment]
This isn't intentional in Flan's mod I believe.
I wasn't able to reproduce the crash or console spam, could you please post a crash log and logs of the "console spam" as well as content pack versions.

**Comment by ModifiedSrcCode** [comment]
Well, it's an unused item, so what i said is a theory.
