### ISSUE TITLE
S0FPacketSpawnMob Crash

### ISSUE THREAD

**Issue by MC-Soupcup** [FlansMods/FlansMod#648]
So I've been occasionally (rare) been getting a crash that appears to happen when the game tries to spawn an entity from Flans. It's weird because I don't have any Flans items yet, no vehicles or things like that. It has happened right at the start of a fresh world as well, where I haven't done anything.

Here's the [crash log](http://pastebin.com/RQRQc135). I don't have the full log to show, but just before the crash occurs, there's a line that says "Skipping Entity with ID -118". As far as I know, entities can't have a negative ID, but I'm not sure. Dumping the entity ID list with NEI Integration shows that "118" is from a different mod, and I tried removing that but it didn't fix it, it actually just changed the number it shows in the crash to "-122" which "122" corresponds to the Flans TeamsItem entity. After that, I re-added the other mod and disabled Flans, and can play in the world without any issues, and haven't run into the problem since.

I should also note that in a test world I had this error, and instead of disabling other mods and reloading the world possibly messing with things, I straight disabled Flans and it fixed the issue. I have no idea what causes this all to happen, and it's probably some weird stuff due to the huge amount of mods I have, but I figured since removing Flans has been fixing it, I'd post about it here.

I use a large modpack, basically FTB's Infinity with a few additional ones, including Flans 4.9.0 and the Modern Warfare/Simple Parts packs.

**Comment by ChrisLane** [comment]
If this is indeed an issue with Flan's mod then it's going to be rather hard to fix considering there is no mention of any flan's mod running code in the stack trace.

Could you let me know if you are using the most recent version of Minecraft Forge and what versions of the Flan's Mod content packs you are using?

**Comment by MC-Soupcup** [comment]
I was using the Modern Warfare and Simple Parts packs, version 4.9.0 of each. As for Forge, I think at the time of this report I was using 1291 (sorry I forgot to include it in the OP), but now I'm on 1343.

I've been assembling an update and had moved up to Forge 1352 (latest that doesn't change the Fluid registry stuff and crash some mods), and updated to Flan's 4.10.0 to see if it'd still give me the error at some point, and it did. It's the exact same crash but I'm dumb and didn't bother to look at the full log to see the erroring entity ID, though I was able to once again log into the world after disabling Flan's, so that tells me it's still something to do with Flan's. I would try the absolute latest Forge builds but it doesn't work with a number of the mods that I have, at least not until they update.

I dunno though, it just seems to happen when something spawns, could it be a strange mod interaction messing with entity ID registry? I'm unsure of how entity stuff works in Minecraft's code so I probably don't know what I'm talking about here.

**Comment by ChrisLane** [comment]
Have you tested reproducing this issue with ONLY Flan's mod installed? This could be an issue with Flan's mod and another one you have installed.

**Comment by MC-Soupcup** [comment]
Yeah, I'll test that stuff today. It's always difficult to be sure if it's fixed since the error is so random unless a world has gotten the error before, But usually if I just leave the instance open for a good while it eventually happens in fresh worlds. I imagine it'll be the same test with an instance of just Flan's mod, but yeah it could just be a weird mod interaction. 

And yeah, I'll be sure to grab the logs, I kept forgetting to grab them and they (or at least the relevant parts...) keep getting overwritten when I restart the game. I'll post back what I find out.
