### ISSUE TITLE
Crash When Placing Vehicle 

### ISSUE THREAD

**Issue by spruill7716** [FlansMods/FlansMod#650]
My server crashes when placing a down a large number of vehicles from updated packs.

https://www.dropbox.com/s/t17hiftj0jhea0j/crash-2015-04-04_17.42.20-server.txt?dl=0

**Comment by ChrisLane** [comment]
Could you please let me know what content packs you are using and their versions?
I see from the log that you are using Flan's Mod v4.9.0.

**Comment by spruill7716** [comment]
I have a large number of content packs. They are:

Danish WW2 Addon 2.1 (1.7.10)
Italian WW2 Addon 2.1 (1.7.10)
Milox117's Car Package (unknown version)
Oskar's Pack (1.7.10)
Poker's Garage 4.0 - Prologue Starter Pack
Western Gun Pack [1.7.10] v2.6
[1.7.10] Kevin&Vini's Survival-Z Pack 3.0.1
Modern Warfare-Content Pack-1.7.10-4.9.0
Simple Parts-Content Pack-1.7.10-4.9.0
WW2-Content Pack-1.7.10-4.9.0
Ye Olde-Content Pack-1.7.10-4.9.0
Zombie-Content Pack-1.7.10-4.9.0
Akaku Vehicle Package 3.1 for 1.7.10
Manus Civil Package 1.7.10d
Manus DayZ Package 1.7.10d
Manus Modern Military Package 1.7.10d
Manus WW2 Package 1.7.10d
Manus SMP Simple Parts Package 1.7.10d

**Comment by ChrisLane** [comment]
Okay, could you please try testing this issue with only the official Flan's mod content packs?
These ones:
Modern Warfare-Content Pack-1.7.10-4.9.0
Simple Parts-Content Pack-1.7.10-4.9.0
WW2-Content Pack-1.7.10-4.9.0
Ye Olde-Content Pack-1.7.10-4.9.0
Zombie-Content Pack-1.7.10-4.9.0

**Comment by spruill7716** [comment]
Alright, the problem doesn't occur with the official packs. Does this mean the problem lies at the hands of the other content packs?

**Comment by ChrisLane** [comment]
Most likely. One of your content packs probably isn't up to date with the mod.
