### ISSUE TITLE
Vehicle Textures using Factions

### ISSUE THREAD

**Issue by Mobius762** [FlansMods/FlansMod#655]
I have no idea if Flans Mod supports factions (or even what that entails), but here's my idea:

Depending on your faction relationship with a person, the texture of the vehicle they are in should change. This would make it much easier to determine friend from foe in combat situations. There should be 4 different texture sets: one for neutral, one for the player's faction, one for allied/truce, and one for enemies. **The texture artist(s) would not need to make 4 different default texture sets**, players could simply add their own customized textures into the specific folders. If there is no texture for a vehicle in a folder, or if the server does not have factions installed, vehicles would default to the neutral faction (default) texture.

There are three ways the texture could be determined:
**(Option A)**
The driver's faction determines the texture; none of the passengers matter. This is the simplest option, but it allows a neutral/ally faction to be the driver, while carrying enemy faction members in the passenger seats. (This may be considered a legitimate deception tactic, though.)

**(Option B)**
The occupant with the highest Threat Level (Progresses from *Player's Faction* to *Allied/Truce* to *Neutral* to *Enemy*) determines the texture. So if a Lancaster had 4 allies and 1 neutral player, the vehicle would use the neutral faction texture. The same goes if there was an single enemy faction member occupant, but 3 neutral players, and 1 ally pilot; the vehicle would use the enemy faction texture. (This is my favorite of the three options.)

**(Option C)**
The number of occupants in each faction category would be totaled, and the highest amount of players in a certain category determines the threat level of the vehicle. If there were 3 allies and 2 enemies in a Lancaster, the allies would have the highest number, so the vehicle would use the allied texture. If there are 2 allies and 2 enemies in a Lancaster, both allies and enemies have the same number. In this case, the relationship with the highest threat level (AKA Enemy) would determine the texture of the plane. This is the most complicated option.

Unlike allowing players to see other players' textures, this suggestion would not require texture files to be sent over the server, put into a database, or use any other equally impractical method. It still doesn't allow you to see other players' textures directly, but it is a much more practical method.

**Comment by codycm9** [comment]
As a person who attempted to make a faction server using flans mod, I agree that this was would be a very interesting mechanic which could add more depth to the whole experience.

**Comment by ChrisLane** [comment]
I'm sorry but this will not be implemented simply because there is currently no API to be able to hook into the bukkit Factions plugin through Forge.
Even if simple features were added, to be able to have them the implementation would be very messy.
