### ISSUE TITLE
errors on the log

### ISSUE THREAD

**Issue by jochuan** [FlansMods/FlansMod#676]
i keep geting theses errors on the start up
https://gist.github.com/jochuan/4fca8929371999d258f4

**Comment by skittishtrigger** [comment]
Seeing as I am getting this same issue I'll confirm this problems.  My github might enable you to dig  a bit deeper as it has configs and logs. I'll link relevant areas. 

logs: (Ignore the rest of the errors as I am doing some major ts'ing atm for several issues now. lol)
https://raw.githubusercontent.com/skittishtrigger/TechnAintEasy/master/logs/server/fml-server-latest.log 

modules installed and HOW they are installed: WARNING! This is a instant download link.
http://solder.storagedragon.info/modpack/mods/flan/flan-1.2.zip

If there is any other info that I can provide or changes to help troubleshoot this just let me know.
