### ISSUE TITLE
The conflict between Flan's and Not Enough Items

### ISSUE THREAD

**Issue by iotachaos** [FlansMods/FlansMod#682]
Hello!

Using the Flan's (version 4.6.3 - 4.10.0) we have found some problem  with Not Enough Items.

The problem is in that fact that NEI shows such item type to which "tile.teamsSpawner.8.name" and "tile.flansWorkbench.5.name" relate (you can see it at the screenshots). 
If we look at them using NEI there are serious lags such as program hang-up. And if we try to take this items using NEI or "/give" command, the programm crush takes place.

Is it possible to make these items invisible in NEI? It will be a good decision for this problem.

I hope, in the later versions this problem will be solved.

Yours faithfully,
iotachaos.

screenshots:
![1](https://cloud.githubusercontent.com/assets/13209486/8541566/f86c104c-2497-11e5-9e86-887146921818.PNG)
![2](https://cloud.githubusercontent.com/assets/13209486/8541567/f86d7c20-2497-11e5-84bb-9b8bc56358e4.PNG)
![3](https://cloud.githubusercontent.com/assets/13209486/8541568/f872e5fc-2497-11e5-8cb1-5e0c1222ae5b.PNG)

Crash-reports:
https://vk.com/doc14294262_406132498?hash=a97aa1ad4079436c7d&dl=803884f4021b1971b4

**Comment by XakepSDK** [comment]
For flans maintainer:
http://www.minecraftforge.net/forum/index.php?topic=3438.0
Maybe i can make fix.
