### ISSUE TITLE
(Question for the person that maintains Flan's) 

### ISSUE THREAD

**Issue by border999** [FlansMods/FlansMod#685]
When do you intend to upgrade Flan's in order to fix many of these bugs that are pilling up?
And on the matter of bugs. The ender dragon from Hardcore Ender Expansion seems to be immune to bullets. took a minigun up against it, not a single half half heart was lost by it.

**Comment by BlackJack55** [comment]
Hello border999,

I already started partially fixing minor issiues with flans mod, most likely in terms of compatibility.
As soon as I have time again (after finishing some of my projects) I will go on and fix the most annoying bugs with the highest priotity (like killing faction members on plugin-servers).

I guess jamioflan has a lot of own stuff to finish, so maybe you just wait and let the bugs be fixed at some point in time.

Kind regards,

BlackJack55
