### ISSUE TITLE
Crafting recipe change for fiberglass

### ISSUE THREAD

**Issue by BlackJack55** [FlansMods/FlansMod#686]
In my eyes fiberglass is a bit too expensive to craft, especcially since it consumes 1 block of clay, which is hard to find in normal biomes. This becomes a problem on SMP servers that do not sell clay in adminshop.

Would it be possible to change it back to 1 clay?

Kind regards,

BlackJack55

**Comment by jamioflan** [comment]
I have changed this for 1.8
