### ISSUE TITLE
Render problems

### ISSUE THREAD

**Issue by Acdrybones** [FlansMods/FlansMod#694]
Is there any way next update, the render system could be changed so the Vehicles don't disappear visualy when they are not within 10 blocks of you? It's rather annoying when you are dogfighting and a vehicle disappears when they are too far away.

**Comment by Acdrybones** [comment]
And, I don't want to sound a bit impatient, but could you have players be seen farther away as well (Sniping, Enhancment, Better Realism).

**Comment by jamioflan** [comment]
Players is very difficult, since they are handled by Minecraft. 
I assume you are exaggerating when you say 10 blocks. Anyway, I'm afraid there are similar limitations on vehicles due to Minecraft only loading a certain area.
Minecraft just wasn't built for large scale
