### ISSUE TITLE
a list of game breaking bugs for 1.8

### ISSUE THREAD

**Issue by BlackJack55** [FlansMods/FlansMod#735]
-Flans mod armor absorbs all kind of damage, not just direct damage (e.g. hunger gets absorbed)
-Said armor does not take damage
-It is possible to get an armor that (almost ?) completely prevents you from dying even if in lava, poisoned and being shot at with a Minigun to the head at the same time. For obvious reasons I do not want to say the Configuration of said armour here.

-Gunpowder recipie is too expencive for not-apocalpyse gameplay

-explosions are not really explosions anymore (see PR)

-you crah on a MP server when client has apocalypse mod and content pack if someone with flans item is standing close

-you can find unobtainable armour in dungeons etc.

-planes point nose downwards when server lags

**Comment by ChrisLane** [comment]
Please split these into separate issues.
