### ISSUE TITLE
Wheels "vanishing".

### ISSUE THREAD

**Issue by Fexcraft** [FlansMods/FlansMod#757]
After testing what's new in the 5.1 release,
I noticed that the Wheels are vanishing/getting invisible.

It's happening when driving backwards,
even when later driving forward, they are still gone.

Screenshots.
![2015-11-03_18 38 27](https://cloud.githubusercontent.com/assets/11726534/10916327/3e5d37b8-825b-11e5-94d6-cc3743c42859.png)
![2015-11-03_18 38 51](https://cloud.githubusercontent.com/assets/11726534/10916334/46664972-825b-11e5-8fd8-ffaed2689207.png)
Happens with tanks aswel...
![2015-11-03_18 53 05](https://cloud.githubusercontent.com/assets/11726534/10916538/30a02fee-825c-11e5-891c-b77696f3e1af.png)

**Comment by war-monger** [comment]
Yeah, I've informed flan about this before the release. He'll fix it eventually, hopefully.

**Comment by Fexcraft** [comment]
Using the latest minecraft SMP pack seems to fix it :[
