### ISSUE TITLE
List of bugs that need fixing

### ISSUE THREAD

**Issue by gigiandearl** [FlansMods/FlansMod#763]
to make it easier here is a point form list of all the issues I have come across, and recommendations for how to fix them.
- Turret speed is super low for all vehicles, this is because it is set to around 0.0025 speed opposed to 0.025
- The black box still appears under vehicles in apocalypse.
-The new GUI gun crafting table is super sketchy (most weapons do not appear on it)
- A Exoskeleton crafting recipe is still not made.
-The boat turns into a magical flying Noah arc whenever it goes out of the water
-The B-52 goes flying like a crazy mothaf**ker out of no where.
-Vehicle damage systems are unbalenced (eg, WW2 planes can't kill eachother with there own bullets while crappy stuff like bazookas can, so there is no point of dogfighting because it will last forever.) Also to add on this many planes are weak compared to a modern plane or tank.

That is all I can think of right now, I will update it regularly

**Comment by ChrisLane** [comment]
Please split these into individual issues so that they can be handled properly.
