### ISSUE TITLE
Crashing everytime i join a server

### ISSUE THREAD

**Issue by spideroh1** [FlansMods/FlansMod#764]
this is what the error is!! 
20:24:54 Player spideroh1 disconnected (TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}) 20:24:41 hello 20:24:28 Player spideroh1 connected

here is the latest crash code!!!

[crash-2015-11-16_14.58.54-client.txt](https://github.com/FlansMods/FlansMod/files/35975/crash-2015-11-16_14.58.54-client.txt)

**Comment by Acdrybones** [comment]
Hmm, the mods you have installed may be conflicting with each other. First try loading up Flan's by itself, to see if it crashes again. If not, it is a mod conflicting.

**Comment by ChrisLane** [comment]
Looks to be an issue with one of your content packs. 
Please try removing all packs and adding them one by one to find the problematic pack.
