### ISSUE TITLE
Cannot use packs

### ISSUE THREAD

**Issue by turbo22** [FlansMods/FlansMod#774]
I have everything installed, forge 11.14.3.1474, 11.14.4.1577, and 11.14.4.1563, and flans 5.1 and apocalypse. I cannot craft the titans from the titan pack, cannot access the simple parts crafting table, craft the items to get to the apocalypse, or anything similar. I have removed all mods besides optifine, and NEI. But nothing seems to work. Any ideas?

**Comment by ChrisLane** [comment]
This is working for me. Shouldn't be a bug in the mod.

Make sure that you have the mecha parts pack installed too that the titan pack depends on I believe.
