### ISSUE TITLE
Inconsistent Pitches Of Sound Effects

### ISSUE THREAD

**Issue by TheProStickman** [FlansMods/FlansMod#784]
Whenever I try to play some audio using a weapon (example: some short music), it doesn't play the original pitch of itself, and sometimes go into a rather absurd pitch which causes the sound to become extremely weird. From the config parameter, I can see that there's a "DistortSound" option, but setting it to "false" doesn't work at all. Is this option still unimplemented yet?

**Comment by ChrisLane** [comment]
Dupe of #605
