### ISSUE TITLE
BUG:The aircraft doesn't have gun,Tank won't get damage when aircrft is booming(1.8.0version)......

### ISSUE THREAD

**Issue by HHH555JJJ** [FlansMods/FlansMod#796]
as the title say

WW2-Content Pack > 1.When I craft the air craft ,every aircraft don't need gun.
                                   2.Tank won't get damage when aircaft is booming.
                                   3.Tank won't get damage when it touch off the anti-tank mine.
                                   4. Why the Machine gun of Janpan(Type99) is white when it is builded on the                            
                                        block?  
                                   5.The Trenchgun's sound is strange(loading and shooting).
                                   6.It is lag when I use the warship of Germany(S-100 schnellboot).
                                   7.All of Machine guns will float when it is shooting.
========================Recommendation=========================================
                                   1.Can you change over the sound that every gun? They sound                                                                                      
                                      strange(1.8.0version).
                                   2.Can you change the skin of flag which print on the Janpan's tank? Let it look 
                                       like this > https://goo.gl/1S6Ud7
                                   3.Can you add some flag of the five countries in the context pack?

**Comment by ChrisLane** [comment]
1 problem per issue please.
