### ISSUE TITLE
AA guns breaking when canBreakGuns == false

### ISSUE THREAD

**Issue by IsaacAbrahamson** [FlansMods/FlansMod#797]
When **_/teams canBreakGuns_** is set to false, mg guns such as browning and mg42_ cannot _be broken; however, aa guns such as the flak still can be broken by the hand, projectiles, or explosions.

**Comment by ChrisLane** [comment]
AA guns are now technically vehicles or at least the ones in the official packs are. This means they are not protected by this rule.
