### ISSUE TITLE
i have a problem with the mod 

### ISSUE THREAD

**Issue by heematiger** [FlansMods/FlansMod#801]
i can't find anything in the mod i have tried more than 3 versions of forge but have the same problem 

![2016-03-10_02 19 20](https://cloud.githubusercontent.com/assets/17753943/13655308/1801afd4-e667-11e5-9cc6-12c2f211a110.png)

**Comment by XakepSDK** [comment]
Just install content pack!
http://flansmod.com/content-packs

**Comment by heematiger** [comment]
all packs ?

**Comment by XakepSDK** [comment]
No.
http://flansmod.com/content-pack/4/Official18Modern_Weapons_Pack
http://flansmod.com/content-pack/2/Official18Simple_Parts_Pack

And if you want more weapons/vehicles install this:
http://www.minecraft-smp.de/index.php/downloads/category/59-flans-mod-5-1 (you can choice, what to install).If you want to install something of these mods, install this too:
http://www.minecraft-smp.de/index.php/downloads/download/59-flans-mod-5-1/165-minecraft-smp-parts-package-for-flan-5-1-and-mc-1-8
