### ISSUE TITLE
Issue starting Server (Trivial)

### ISSUE THREAD

**Issue by DraksterAU** [FlansMods/FlansMod#806]
Hi Guys,

I'm seeing the below when starting flansmod - can you explain what it means exactly?
Probably not a mod issue, but it delays my server starting by about 5 seconds per dimension loaded ( we have 30)
`[14:05:05 INFO]: [Flan's Mod] Tried to add m4Carbine to player class gignAssault1 but the item did not exist`
`[14:05:05 INFO]: [Flan's Mod] Tried to add mp5k to player class gignDualWield1 but the item did not exist`
`[14:05:05 INFO]: [Flan's Mod] Tried to add mp5k+flanMWSilencer to player class gignSniper2 but the item did not exist``

**Comment by Lennified** [comment]
Looks like you don't have the Zombie Pack. You're gonna need it if you don't want this happening

**Comment by DraksterAU** [comment]
Thanks for the tip, it saves me 3 minutes on every reboot now!!!
