### ISSUE TITLE
Flans mod 1.6.4

### ISSUE THREAD

**Issue by rufo123** [FlansMods/FlansMod#819]
HI, I am running server with Flans mod 4.1.1 for 1.6.4 and This Crash occurs everytime 
[crash-2016-07-04_12.07.02-server.txt](https://github.com/FlansMods/FlansMod/files/346017/crash-2016-07-04_12.07.02-server.txt)

**Comment by ChrisLane** [comment]
Sorry but 1.6.4 versions of the mod are not supported any more.
The fix for this issue is in the 1.7.2 update.

Closing as duplicate of #373
