### ISSUE TITLE
Push Version 5.2 to Flan's Mod Website

### ISSUE THREAD

**Issue by gitgud-software** [FlansMods/FlansMod#827]
There's more than a few fixes in that latest minor version bump, would it be possible to get it on the website so the interested don't have to compile it manually?

An alternative if nobody has access would be to start using Github's release setup.

**Comment by PrototypeTheta** [comment]
There are still a few problems with it though. Vehicle MGs seem to crash upon firing which is not good. I'll see if I can fix it but it's from the fancy new hitscan stuff which I have not yet looked into properly.
