### ISSUE TITLE
Flans Mod only shows coloured wools

### ISSUE THREAD

**Issue by TBGaming** [FlansMods/FlansMod#838]
I have just installed Flans mod recently. I did exactly everything in the installation guide, but when I launch the game, I found that my Flans mod only shows some coloured blocks of wool. I tried to install some content packs to see if it could change anything. I put every content packs into the "Flan" folder and it was no use at all. Only a few more items appeared, and the rest was still the same as it was. I'm done and I don't know what to do more about this.
My Flans version is 4.10 for minecraft 1.7.10, and I used some content packs made by LabJac
![issue](https://cloud.githubusercontent.com/assets/23218081/19936844/a00bc748-a151-11e6-87cb-cad6a5dcab48.jpg)

**Comment by GolddolphinSKB-Fexcraftian** [comment]
The wool is just a placeholder for a thing which rotates round the item in each tab, The wool replaces the icon for an empty tab.

**Comment by Fexcraft** [comment]
Probably no content packs installed.

**Comment by TBGaming** [comment]
So do you know any solution to this problem?

**Comment by Fexcraft** [comment]
Most probably means that *_there isn't any more content loaded_*.
Check if the content-pack .zip's shouldn't be unpacked, maybe there is another zip inside?

**Comment by TBGaming** [comment]
Ok, I had checked it and found that my content packs were unzipped. Now everything works normally, thanks.

**Comment by darthdavid66** [comment]
it does'nt work for me, im still trying but can someone please post a pic of what there mod folder looks like?

**Comment by Fexcraft** [comment]
Content Packs go into the `.minecraft/Flan/` folder,
only the FlansMod jar goes to mods?

**Comment by darthdavid66** [comment]
Ty!!!I didn't really understand the concept of that untill I messed around
with the files...
