### ISSUE TITLE
Apocalypse Won't Load

### ISSUE THREAD

**Issue by DivideByPotato** [FlansMods/FlansMod#840]
When I make the mech with the AI chip, it spins and drops nukes like it should, but once it starts loading the dimension, it loads forever.  I have left the screen saying "Downloading terrain" for up to 30 minutes with no effect.  I am sure I have all required content packs for it to work.  I have even tried using the teleporter from CustomNPCs, but to no effect.  Please fix this as soon as possible, I really enjoyed playing with the apocalypse pack when it worked on my old computer.

**Comment by ChrisLane** [comment]
Could not reproduce in latest version
