### ISSUE TITLE
instant crash when using armor crafting box

### ISSUE THREAD

**Issue by uncleLieutenant** [FlansMods/FlansMod#854]
I have been playing on this technic based pack called blockfront and the armors in this pack are sexy asf. Unfortunately, When I try open the ww2 armor box it crashes instantly. I want this issue to be resolved as soon as possible, please any tips will help out dearly.

This is the file txt so if there is anything out of place let me know please:Name WW2 Armour Box
ShortName ww2Armour
TopTexture ww2ArmourBox
SideTexture ww2ArmourBoxSide
BottomTexture ww2ArmourBox
Recipe W wood C cloth
WWW
CCC
WWW
//AddArmour
AddArmour american American
americanHelmet cloth.4 5
americanCoat cloth.4 8
americanPants cloth.4 7
americanBoots cloth.4 4
AddArmour british British
britishHelmet cloth.4 5
britishCoat cloth.4 8
britishPants cloth.4 7
britishBoots cloth.4 4
AddArmour german German
germanHelmet cloth.7 5
germanCoat cloth.7 8
germanPants cloth.7 7
germanBoots cloth.7 4
AddArmour japanese Japanese
japaneseHelmet cloth.13 5
japaneseCoat cloth.13 8
japanesePants cloth.13 7
japaneseBoots cloth.13 4
AddArmour russian Russian
russianHelmet cloth.4 5
russianCoat cloth.4 8
russianPants cloth.4 7
russianBoots cloth.4 4
AddArmour britishDesert British Desert
britishDesertHelmet cloth.4 5
britishDesertCoat cloth.4 8
britishDesertPants cloth.4 7
britishDesertBoots cloth.4 4
AddArmour germanDesert German Desert
germanDesertHelmet cloth.4 5
germanDesertCoat cloth.4 8
germanDesertPants cloth.4 7
germanDesertBoots cloth.4 4
AddArmour americanDesert American Snow
americanSnowHelmet cloth.0 5
americanSnowCoat cloth.0 8
americanSnowPants cloth.0 7
americanSnowBoots cloth.0 4
AddArmour germanDesert German Snow
germanSnowHelmet cloth.0 5
germanSnowCoat cloth.0 8
germanSnowPants cloth.0 7
germanSnowBoots cloth.0 4
AddArmour germanForest German Forest
germanForestHelmet cloth.13 5
germanForestCoat cloth.13 8
germanForestPants cloth.13 7
germanForestBoots cloth.13 4

**Comment by MarcinWieczorek** [comment]
What is your error log?

**Comment by uncleLieutenant** [comment]
Don't have a log at the moment due to my WiFi acting up but if you can check for me install the blockfront technical pack"its on technic" and try crafting with the box it should give you the report. Please help me!!!!

**Comment by uncleLieutenant** [comment]
Don't have a log at the moment due to my WiFi acting up but if you can check for me install the blockfront technical pack"its on technic" and try crafting with the box it should give you the report. Please help me!!!!
