### ISSUE TITLE
Release Flan's

### ISSUE THREAD

**Issue by Pierresa15** [FlansMods/FlansMod#855]
Hi everyone ! And sorry for Bad english ... (I'm french and very Bad un english).

If I'm here today it's because last week, I tried to make a minecraft with guns in 1.10.2 and my favorite mod, Flan's are not release on this version.

So, I would like to know if the dev's of the mod have definitely stop to release the mod or if it's possible to have a 1.10 version of the mod ?

Thanks you for learning. See you soon guys !

**Comment by mgdgfbhevdyeh** [comment]
Hello,
I am flans mod fans,too
now this mod not any 1.10.2 port by jamioflan and his team
they're very busy.
have a nice man,he port this mod to 1.10.2 and 1.11
https://github.com/Fexcraft/FlansMod
jamioflan is busy,need waiting more time

**Comment by Pierresa15** [comment]
Thank you very much mgdgfbhevdyeh ! (I have copy your pseudo !! :o ) But when I try to make the mod on the .minecraft/mods folder , they're just the FexCraft library who works :/

Have a solution ?

EDIT : I have found how the mod works ;)
