### ISSUE TITLE
Assistance teleporting flans vehicles and preserving state data

### ISSUE THREAD

**Issue by StargateMC** [FlansMods/FlansMod#859]
Hi All,

I'm working with the dev for SGCraft and (will offer this code to) the WarpDrive dev to solve issues teleporting Flans vehicles without crashing a server, preserving state & passengers.

If you have some time would you be able to give a quick list of data to be preserved, and the best way to obtain and set it again?

We'd love flans vehicles to be able to travel through stargates and between dimensions (Transitioning from space to planet and vice versa for some of them) without issue.

-- Will work on this myself, but it will be a lot faster going If I have assistance :) 

Kind Regards,
Bysokar

**Comment by StargateMC** [comment]
Guess this mods dead. Time to see if I can update to 1.10! lol

**Comment by Fexcraft** [comment]
https://github.com/Fexcraft/FlansMod
1.10 with/-out guns and diff packet system.

**Comment by StargateMC** [comment]
Oh wow thanks mate - is that compatible with existing content packs? @fexcraft

**Comment by Fexcraft** [comment]
`it should`, and so far it worked `fine`
it is based off the 1.8 branch, so what worked in 1.8 should work there too.
- - - -
look at `"branch information"`, it's a small summary of the feature set
https://github.com/Fexcraft/FlansMod/issues/2

**Comment by StargateMC** [comment]
Reopening this as I am still having trouble with teleporting flans vehicles with players in them... feel free to close if not able to help me.

**Comment by ChrisLane** [comment]
@Bysokar The latest version of Flan's Mod is for 1.12.2, is there a version of Stargate for 1.12.2?
1.7.10 Flan's Mod is no longer being worked on for official versions.

**Comment by StargateMC** [comment]
Yes there is an SGCraft for 1.12.2.... haha

I'm not asking you to code anything. Im just asking for advice on the best way to allow players to fly through stargates in their vehicles.

The way Flans works is odd. Every other mod I've seen I have  been able to get working. This not so much.

I'll be pushing these changes to both 1.7 and 1.12.2 SGCraft builds... so advice for 1.12 only will be fine :)

Regards

Bysokar

**Comment by Deliphin** [comment]
```
Forge 2838
Flan's Mod-1.12.2-5.5.2
SGCraft-2.0.2
```

Flans vehicles still don't go through Stargates. You hear the teleport woosh, but nothing actually changes, you just go through the entry stargate as if it didn't exist, you do not come out the exit stargate.

**Comment by StargateMC** [comment]
Isnt going to happen.
