### ISSUE TITLE
nothings working

### ISSUE THREAD

**Issue by darthdavid66** [FlansMods/FlansMod#861]
![flanmod](https://user-images.githubusercontent.com/29822006/27764637-34c86d96-5e9e-11e7-9b56-eabb87acef3a.PNG)
and if you cant see the picture,it shows that when i go to the page in the inventory were the mod items are, there are non just some sorts of crafting tables and spawns,NOTHING ELSE i mean nothing at all but that, i have the two 1.8 mods in the mods folder, using a 1.8 forge.please help

**Comment by Isaac96** [comment]
You need to get the content packs and put them in the "flan" folder in your MC folder.

**Comment by xFaiafokkusu** [comment]
Isaac96 have right
