### ISSUE TITLE
"429 drop box error" when trying to download content packs"

### ISSUE THREAD

**Issue by GilbertTh3Savage** [FlansMods/FlansMod#863]
![untitled](https://user-images.githubusercontent.com/29844225/27773403-f6216d28-5f46-11e7-9835-ef28f501e512.png)
I keep getting this screen when i try to download the content packs for flans mod.

**Comment by darthdavid66** [comment]
same for me i just download the flan stuff from other websites :(

**Comment by GilbertTh3Savage** [comment]
what website?

**Comment by Isaac96** [comment]
I have been downloading from here https://github.com/FlansMods/FlansMod/releases
The version is from 2015 but it works fine :)

**Comment by Davoleo** [comment]
hi, i have the same problem is there anyone who has official content packs for 1.8 version?

**Comment by mgdgfbhevdyeh** [comment]
@ChrisLane @jamioflan

**Comment by blooditor** [comment]
All official content packs as Flan's Mod uploaded it on facebook once: http://www.minecraft-breakdown.net/download/FlansModOfficialQuickStart.zip

If I could help you and you are looking for a Flan's Mod 1.8 server, go visit the website http://minecraft-breakdown.net   ;)

**Comment by xFaiafokkusu** [comment]
You can download from  https://github.com/FlansMods/FlansMod/releases
renember to put this in Flan folder

**Comment by shadowboy070** [comment]
i have flans 5.3 bud i can't get the content packs from the links pls give me a link that has all basic content packs for 5.3

**Comment by Fexcraft** [comment]
check pinned messages in #general 
https://discord.gg/NqqZhCr
I guess..
