### ISSUE TITLE
Corrupted Textures And Missing Parts, Etc

### ISSUE THREAD

**Issue by RandomUsernameHereXD** [FlansMods/FlansMod#866]
Guns,Vechicles And Gear in flans mod are all broken for some reason, some still work but there all corrupted and missing parts, i don't know how do am i missing a mod? Planes,Helecopters are invisible, Guns textures are corrupted, some tanks don't have there top of them, some tanks are just invisible, Vehicles are boncy,  Theres so many issues happening.

![screen shot 2017-08-21 at 6 50 12 am](https://user-images.githubusercontent.com/31208231/29516081-020561b8-863d-11e7-8e46-a3d1aec6bae1.png)

![screen shot 2017-08-21 at 6 51 04 am](https://user-images.githubusercontent.com/31208231/29516111-1fc65c3e-863d-11e7-9120-694b73e7c422.png)

![screen shot 2017-08-21 at 6 51 49 am](https://user-images.githubusercontent.com/31208231/29516162-501eef68-863d-11e7-9b75-a2d9947c982b.png)

![screen shot 2017-08-21 at 7 00 33 am](https://user-images.githubusercontent.com/31208231/29516594-edd785b6-863e-11e7-9bb9-545e43f56f2a.png)

Can someone please help me?

**Comment by xFaiafokkusu** [comment]
You have bug with textures
you can download good textures here: https://github.com/FlansMods/FlansMod/releases

**Comment by RandomUsernameHereXD** [comment]
Do i put the textures in my mods folder or in the content folder.

I'm new to the mod.

**Comment by RandomUsernameHereXD** [comment]
Nevermind i fixed the issue.

Thank you!
