### ISSUE TITLE
Flan mod wird nicht geladen

### ISSUE THREAD

**Issue by kingnic** [FlansMods/FlansMod#870]
hallo ich habe alles soweit in die Ordner verschoben und installiert. die Forge werden minecraft angezeigt aber das flan bei den mods nicht somit läd er auch alle mods nicht! kann mir jmd helfen bitte

danke

**Comment by xFaiafokkusu** [comment]
can you write english?

**Comment by LindowMods** [comment]
ist das Problem immer noch da?
Wenn ja hast du die 1.7.10  oder  1.8 ?
