### ISSUE TITLE
Flan's mod crash

### ISSUE THREAD

**Issue by PrinterPrime** [FlansMods/FlansMod#882]
My game keeps on crashing when I get something from Flan's mod. Is it from other mods I have? Or is it from the other mods? Anyway,heres the crash report.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8-1.5.22.47.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  MalisisCorePlugin (malisiscore-1.8-1.2.0.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 28/01/18 13:04
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.item.ItemStack.func_111283_C(ItemStack.java:864)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1615)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:229)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:44)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_111283_C(ItemStack.java:864)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1615)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:229)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:44)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
	Entity Type: Skeleton (net.minecraft.entity.monster.EntitySkeleton)
	Entity ID: 12963
	Entity Name: Skeleton
	Entity's Exact location: 117.50, 14.00, -191.50
	Entity's Block location: 117.00,14.00,-192.00 - World: (117,14,-192), Chunk: (at 5,0,0 in 7,-12; contains blocks 112,0,-192 to 127,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: Mod Testing Grounds
	All players: 1 total; [EntityPlayerMP['ExcaliburPrime'/165, l='Mod Testing Grounds', x=215.74, y=67.00, z=-158.24]]
	Chunk stats: ServerChunkCache: 1187 Drop: 0
	Level seed: 2657949192548928734
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 136.00,64.00,-40.00 - World: (136,64,-40), Chunk: (at 8,4,8 in 8,-3; contains blocks 128,0,-48 to 143,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 10307 game time, 10307 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 44590 (now: false), thunder time: 164383 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 914839272 bytes (872 MB) / 2442702848 bytes (2329 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.22.47} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	securitycraft{v1.8.0} [SecurityCraft] ([1.8] SecurityCraft v1.8.0.jar) 
	UCHIJAAAA	imsm{1.8} [Instant Massive Structures Mod] ([1.8]InstantMassiveStructuresMod2.jar) 
	UCHIJAAAA	iChunUtil{5.5.0} [iChunUtil] (iChunUtil-5.5.0.jar) 
	UCHIJAAAA	BeeBarker{5.0.1} [BeeBarker] (BeeBarker-5.0.1.jar) 
	UCHIJAAAA	bunkermod{2.0} [Bunkermod] (Bunkermod-mc1.8-v2.0.jar) 
	UCHIJAAAA	cfm{4.0.1} [MrCrayfish's Furniture Mod] (cfm-4.0.1-mc1.8.jar) 
	UCHIJAAAA	customnpcs{1.8.0} [CustomNPCs] (CustomNPCs_1.8.0.jar) 
	UCHIJAAAA	eyemod{5.5} [EyeMod] (eyemod-5.5.jar) 
	UCHIJAAAA	flansmod{5.3.1} [Flan's Mod] (Flan's Mod-1.8-5.3.1.jar) 
	UCHIJAAAA	flansmodapocalypse{1.0} [Flan's Mod: Apocalypse] (Flan's Mod Apocalypse-1.8-1.0.jar) 
	UCHIJAAAA	GravityGun{5.0.0} [GravityGun] (GravityGun-5.0.0.jar) 
	UCHIJAAAA	InventoryPets{1.3.3} [Inventory Pets] (inventorypets-1.8-1.3.3.jar) 
	UCHIJAAAA	ThinkBigCore{1.2} [§5§m===§r §e§lThink Big Core §5§m===§r] (ThinkBigCore-1.2-[1.8].jar) 
	UCHIJAAAA	LOT{1.2} [§9§lLots of Things] (LotsOfThings-1.2-[1.8].jar) 
	UCHIJAAAA	lucky{5.2.0} [Lucky Block] (LuckyBlock_1-8-1_v5-2-0.jar) 
	UCHIJAAAA	malisiscore{1.8-1.2.0} [MalisisCore] (malisiscore-1.8-1.2.0.jar) 
	UCHIJAAAA	malisisdoors{1.8-2.0} [Malisis' Doors] (malisisdoors-1.8-2.0.jar) 
	UCHIJAAAA	moreplayermodels{1.8.0_beta} [MorePlayerModels] (MorePlayerModels_1.8.0_beta.jar) 
	UCHIJAAAA	oceancraft{1.5} [Oceancraft] (oceancraft-1.5.jar) 
	UCHIJAAAA	OpenComputers{1.5.22.47} [OpenComputers] (OpenComputers-MC1.8-1.5.22.47.jar) 
	UCHIJAAAA	rafradek_blocklauncher{1.4.1} [Block Launcher] (rafradek_blocklauncher-1.8-2.0.jar) 
	UCHIJAAAA	corerm{1.2c} [RikMuld's Core] (RikMuldsCore_1.2c.jar) 
	UCHIJAAAA	camping{2.2e} [The Camping Mod 2] (TheCampingMod_2.2e.jar) 
	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8-1.5.22.47.jar)
  li.cil.oc.common.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
MalisisCorePlugin (malisiscore-1.8-1.2.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.

**Comment by ChrisLane** [comment]
Please comment if this still occurs in 1.12
