### ISSUE TITLE
Crash on joining my server

### ISSUE THREAD

**Issue by TophBeiFong078** [FlansMods/FlansMod#883]
So I recently started up a new modded server with my friends on which we play we have ran into many bugs and crashes because of the amount of mods installed and we have fixed quite a few of them. Everything was working fine until I ran into a crash with the Minecraft client that i couldn't fix. So i was hoping someone out there could help me.

My crash Report: https://pastebin.com/9tM4D0Hh

**Comment by ChrisLane** [comment]
1.7.10 is no longer supported
