### ISSUE TITLE
Crafting in crafting table doesn't work properly

### ISSUE THREAD

**Issue by JackTheRedCreeper** [FlansMods/FlansMod#886]
The problem happens mainly with 3x3 recipes like the weapon boxes or even a normal chest. The game will not reconize the input items, they will corrupt and you will end up with either less or more than what you had (usually a lot less).
Other recipes (such as 'sand and clay mixture') work properly.

[latest.log](https://github.com/FlansMods/FlansMod/files/1776567/latest.log)

**Comment by NisseTuta** [comment]
I have the same problem. I can make clay and sand mixture. but i cannot build anything that has to do with the airplanes or machines. i was able to build a vehicle crafting bench but no more. But no propellers och wheels or anything in that category.

**Comment by Master-lego** [comment]
Can confirm Issue. Crafting doesn't work at all. Even vanilla crafting is broken. Stacks of Items get corrupted.

**Comment by ChrisLane** [comment]
Think this should be fixed in the latest version
