### ISSUE TITLE
(1.12.2) Vehicles, Guns and Armors missing textures, game keeps crashing

### ISSUE THREAD

**Issue by DManOmega** [FlansMods/FlansMod#887]
Great mod no doubt, but latest release seems to be unstable. 
Textures for German helmet, B1 tank and Sherman are missing ( they are black and purple ) , some textures seem to be broken such as STG44s and Panzershrecks texture which are partially invisible.

So far i found out game crashes when i use ww2 armor box thingy and it happens after scrolling first 2 armors ( which are american and Brittish, if i remember correct ). Game also randomly crashed few more times but im not sure how or why. 
Also survivors are not spawning in apocalypse and it seems like they are not in the mod at all. There are no spawn eggs for them.
Few icon textures are missing for some items in apocalypse section of creative inventory. 

I had same problem with test release. I reinstalled the mod and forge few times already but issue did not get fixed. My forge version is 14.23.2.2611 but i also tried using newer version during one of my re-installs.

**Comment by ChrisLane** [comment]
Seems that a few of the missing textures may originate from this commit: e29538d6be0b0bde4b0802792d95f6edda68fe4d

About to push a fix for the tanks

**Comment by DManOmega** [comment]
Keep up the good work

**Comment by DManOmega** [comment]
Edited 2 .txt files in ww2 pack, can confirm tank textures work now.

**Comment by DManOmega** [comment]
Also i think i found new bug. When you spawn German BMWR75 it keeps rotating in the spot. Not sure if bug or not but still kinda weird so i might as well report it. Also Leopards 2A6 model has broken texture and M1 Abrams is missing track texture.

**Comment by DManOmega** [comment]
Found few more bugs. When you fire M72 LAW game crashes, also when you spawn sentry gun its floating about 2 blocks above the ground.

**Comment by Tattipls** [comment]
The ww2 armor box crashes my game after i scroll through the first two packages and panzerschrek,luger,fg42 aren't appearing in my hand and stg 44 has half of it's body missing when it is in my hand

**Comment by ChrisLane** [comment]
@Tattipls  Many issues on GitHub are easier to track than one containing lots of different problems. Please search if your problem has been reported before and then create a new issue.

P.S. The armour box crash was already fixed for the next version: d02694aa1fe6d254606e82bc2c9735221d05c56f

**Comment by upupaepops** [comment]
How do I download the fix then? Let's say for the armour box or the missing gun textures? They're not in the version 5.5.2
