### ISSUE TITLE
Client crashes when trying to put weapon in the weapon customization table.

### ISSUE THREAD

**Issue by matty45** [FlansMods/FlansMod#891]
Game Version: 1.12.2
Forge Version: 14.23.2.2611
Flans Version: 5.5.2

Whenever i try to put a weapon into the modification table on my server, this happens: https://i.imgur.com/JFuTFLW.png

I have no idea what causes this error and i have tried using it with a weapon with loaded ammo and it still crashes.

**Comment by CobaltFluoride** [comment]
I have the same issue.
Game Version: 1.12.2
Forge Version: 14.23.2.2625
Flans Version: 5.5.2

**Comment by matty45** [comment]
Nvm, fixed by updating forge for both server and client.
