### ISSUE TITLE
Flans 5.5.2 - Gun always aims at the ground

### ISSUE THREAD

**Issue by Gladorme** [FlansMods/FlansMod#893]
Hello guys,
there is a problem with the new version of Flans (1.12.2) when you have a gun in your hand, your gun always targets the floor not like previous versions where the gun was targetting where you was aiming at. I don't know if it is intentional or not, but I think it's really better because you can know if the enemy spotted you or not and it's really more beautiful. Please add this feature for Flans 1.12.2!

Thanks in advance!

**Comment by italyguy60** [comment]
I am experiencing the same thing. If this feature could be added back it would make the guns less strange and "realistic" you could say. Thank you!

**Comment by ChrisLane** [comment]
Assuming you mean in third-person since I can't see an issue in the first-person view.
Fixed in 30d98fbcfce5623df4508eda899c933ab19fd60b

**Comment by mensreaMC** [comment]
Where do we get updated flans files? It looks like you're doing a lot of fixing but the mod is still listed as 5.5.2 on his page? EDIT: Nevermind, just saw it on the front page.

**Comment by ChrisLane** [comment]
@mensreaMC https://github.com/FlansMods/FlansMod/releases/tag/v5.6-beta

**Comment by mensreaMC** [comment]
Nice, thanks. Btw I did try to build it but it kept looking for JDK related stuff in the JRE folder. I do have JDK installed but I couldn't figure out a way to tell it to look in the right folder.

**Comment by ChrisLane** [comment]
Sounds like you need to set the JDK in your PATH
