### ISSUE TITLE
crash 5.5.2

### ISSUE THREAD

**Issue by collwee** [FlansMods/FlansMod#894]
https://paste.ee/p/2WaGL

crash at line 3164

**Comment by flin7101** [comment]
Collwee,

I have same error and crash at load screen, however I don't have as many mods installed as you do. 

I have managed to track it down to some form of failure when either of the below Galacticraft addons from MJRLegends are installed along with Flans Mod -1.12.2-5.5.2 and any content packs. 

Theres some kind of conflict going on might be a dimension thing or some crosscode / incompatability but i'm no code guru.

When I remove MJRLegends Extra Planets-1.12.2-0.3.2 & Blank Planet-0.1-1.12.2 the game loads without any problems. Also works if I remove the Flan's Mod -1.12.2-5.5.2 and all content packs and leave in MJRLegends above two mods 

However I still have other Galacticraft Addons in from other Modders and strangly the MJRLegends Lib and it loads fine.

Hope some one is able to figure out the issue.

**Comment by CanineCraver** [comment]
I managed to find a solution, get the flans mod jar and change its name to a zip using hidden file extensions, if you don't know how to turn them on look up a video. Once the name is changed you can access the zip and look for 'flansmodapocalypse" delete it and any other files related to apocalypse, then go to your flan folder in .minecraft and delete the apocalypse content pack, worked for me, hopefully it works for you.

**Comment by flin7101** [comment]
Hi Canine 

Yeah thanks for the info however 7 zip also lets you open a , jar file direct. Hehe the solution is a neat one though reminds me of old days when removing or replacing out of date APi files in Jar's was a thing. Was hoping to be able to use or look at apocalypse  but hey some flans is better than no flans lol

**Comment by tpdriver** [comment]
For some reason its still giving me issue. I can now load into the game but then when i load into a world I crash.. Help?

**Comment by CanineCraver** [comment]
Are you using the 1.12.2 version and updated to at least forge 14.23.3.2655? Thats the version that worked for mine and it's still working with forge -2705 as far as I'm aware. Also no problem flin7101, I saw other people were having the same issue so I was hoping this fix would allow others to be able to use these two great mods together aswell. I looked at the crash report saw it said apocalypse, and tried to mess around a bit, didn't think it would actually work though. Glad it worked for you.

**Comment by tpdriver** [comment]
I thought I had that forge. Still issues

**Comment by CanineCraver** [comment]
Well in order to tell what the problem is, I'll have to see your crash report. Also how much ram to you have allocated to minecraft? I'm pretty good with computers but no modder, although seeing as the mod publisher has been rather inactive since it's 1.12 update, I'll see what I can do.

**Comment by tpdriver** [comment]
Not sure what i did but i fixed the crashing issue some how. But now i am having a big issue with hit boxes maybe?

I already did one of those issue things. But i have not found a fix and it pretty much makes it impossible to use any vehicle or the rpgs

**Comment by tpdriver** [comment]
Alright without doing what you said and just having flans and the addon packs it will shoot correctly... Weird.
But if i add the other mods and try to launch flans normally it crashes

**Comment by tpdriver** [comment]
Yeah If i delete the apocalypse stuff it makes a lot of stuff glitched out.

**Comment by tpdriver** [comment]
Also forgot to say! I have 6gb of ram into the game.

**Comment by ChrisLane** [comment]
Crash log missing
