### ISSUE TITLE
[v5.5.2] seems mounted vehicles guns bullets and rockets cant escape the hitbox, and explode directly..

### ISSUE THREAD

**Issue by Kaploks** [FlansMods/FlansMod#895]
So, there is a bug with flan v5.5.2 and 5.5.1 for mc 1.12.2:
i cant shot with any vehicle or plane mounted weapons, the projectiles explode (for rockets), or disapear directly and dont reach any targets.

**Comment by Jordan-Nguy** [comment]
For me, even the browning on land can't aim. The gun just glitches downwards and shoots into the ground.

**Comment by madpat1998** [comment]
Yes, i also have that issue with every vehicle
