### ISSUE TITLE
Some weapon issues

### ISSUE THREAD

**Issue by XakepSDK** [FlansMods/FlansMod#899]
Dragunov - wrong shooting range
ACR - Shoots strange
SIG P232 - No texture
~Sentry - Wrong position, hovers in the air~
FIN SCAR - Small shooting range
M21 - Recheck shooting range
Hydra - No model, can't shoot
Ammo bag - Too big interaction range, can pickup items even if not looking at it
Many rocket launchers doesn't have reload animation

**Comment by ChrisLane** [comment]
Single issues per problem please
