### ISSUE TITLE
Can't craft certain items

### ISSUE THREAD

**Issue by mattmatheson** [FlansMods/FlansMod#900]
SIngle player or multiplayer on my forge server I cant craft any engine parts. Using simple parts pack and the yeOld stuff. Can't make pistons or fuel cans. Very Confused. 1.12.2

**Comment by ChrisLane** [comment]
It seems the crafting recipes weren't being created correctly, this should be fixed in the next version of the mod.

Until a new version is released, you can see the working but incorrect crafting recipes using a mod like "Not Enough Items".
