### ISSUE TITLE
Game crashes when i get in a vehicle. flans 5.1 and 5.2, Minecraft 1.12.2

### ISSUE THREAD

**Issue by IvorAmlug** [FlansMods/FlansMod#901]
The title says everthing. I tried it with 5.1 and 5.2 of flans but both times it crashed.

**Comment by ChrisLane** [comment]
Please post a link to a crash log. Use https://paste.ee/

**Comment by IvorAmlug** [comment]
https://paste.ee/p/xHJUq
Note: I also tried it with no other mods than flans.

**Comment by ChrisLane** [comment]
Looks like your game has something registered to key code 316 which LWJGL doesn't know about.

Could you look into your options.txt file, have a look at what's using value 316 as a keybinding and let me know what that key is on your keyboard?

**Comment by IvorAmlug** [comment]
its : < used by most control stuff i dont need.
key_Bomb Key:316
key_Gun Key:316
key_key.backpackloader.load:316
key_key.backpackloader.edit:316
key_key.backpacks.permission:316
key_key.saveToolbarActivator:316
key_key.loadToolbarActivator:316
key_nei.options.keys.gui.enchant:316
key_nei.options.keys.gui.potion:316
key_nei.options.keys.gui.prev:316
key_nei.options.keys.gui.next:316
key_key.jei.toggleOverlay:316
key_key.jei.focusSearch:316
key_Look at Gun:316
I hope this is wath  you meant.

**Comment by JackTheRedCreeper** [comment]
Similarly related (as a friend's been having this problem with the same crash log), I've been having an alternative crash when hopping into a vehicle: https://pastebin.com/WY2EyNCR

The player screen shows a void as if the vehicle was incredibly far away and the chunks didn't render.

**Comment by IvorAmlug** [comment]
Ohh i forgot the void there is nothing its almost like the chunk that im in is gone (i cant remember if the vehicle ist gone too because i dont play with the flans mod if the vehicles dont work).

**Comment by IvorAmlug** [comment]
Never mind i reinstalled minecraft and it works fine :)
