### ISSUE TITLE
Texture bugs ,when i put a weapon to my hand

### ISSUE THREAD

**Issue by SimiD15** [FlansMods/FlansMod#905]
Hi guys ! 
I have an issue ,with the mod .. When i put a weapon into my hand I get a free xray ,just i don't see the blocks... I created some pictures from this ,but for the easier work.. 
![image](https://user-images.githubusercontent.com/38857739/39427326-a84ea6ee-4c83-11e8-8004-8105a61555ff.png)
![image](https://user-images.githubusercontent.com/38857739/39427315-9e97b744-4c83-11e8-8eda-58d667075dc7.png)
The pictures are bugging so please check the background ..

**Comment by ChrisLane** [comment]
Could you please provide a client log too? Use https://paste.ee

**Comment by XakepSDK** [comment]
Use in-game screenshot feature.

**Comment by tigerpower4** [comment]
j'ai le mêle problème 
![2018-06-24_13 05 12](https://user-images.githubusercontent.com/40538308/41818433-74c0a7a8-77af-11e8-8ead-c9ca05e6a864.png)
![2018-06-24_13 05 22](https://user-images.githubusercontent.com/40538308/41818434-78b1a11e-77af-11e8-98a3-0f371efd997e.png)

**Comment by tigerpower4** [comment]
même*

**Comment by IvorAmlug** [comment]
do you have stuff like optifine enabled or to be more preciese any kind of shader ?
