### ISSUE TITLE
Some items are buggy in ww2 contents pack

### ISSUE THREAD

**Issue by thingevery1234** [FlansMods/FlansMod#907]
I've enjoyed your mod since MC 1.7.10, that's when I had knew your mod first. Thank you for your great work.
Currently I am playing MC with your recent Flan mod 1.12.2-5.5.2 and found some issues in ww2 contents pack.
1. Luger pistol doesn't appear. I can shoot, reload, but shape of the gun just simply does not appear.
2. ~Littlebird chopper won't start. Other helicopters works fine (maybe) but can't start the littlebird even with some fuel. It just stay still.~

There can be more issues with other stuffs, but those two were I could check about.

Hope you track those bugs soon, and again thanks for your great work.

**Comment by cpttuttle** [comment]
Make sure you are in the pilot's seat of the little bird on the right side of the vehicle. You can also access the vehicle inventory from the passenger seats, so it may be misleading.
