### ISSUE TITLE
Apocalypse Issues: Survivors (Flans Mod Version 5.5.2 for Minecraft 1.12.2)

### ISSUE THREAD

**Issue by cpttuttle** [FlansMods/FlansMod#912]
I have been trying out the updated flans mod for Minecraft 1.12.2 and have encountered errors when playing the apocalypse. Survivors do not recognize players as hostile entities and will not attack me as they have in the past, thus making it less of a challenge to survive myself. Additionally,  there is no "Spawn Survivor" egg in the creative inventory. I am not sure if this is intentional or not, but the egg used to be there in previous versions. I can not comment if survivors attack each other. I have not witnessed a conflict between survivors yet (maybe less spawning?).

**Comment by FangMRider** [comment]
how do you go into apocalypse???

**Comment by cpttuttle** [comment]
You need to credt a Mecha with an AI chip. This can be done in the vehicle crafting table. Make sure you have all of the parts for a Mecha and an AI chip in your inventory.

**Comment by FangMRider** [comment]
Thanks u heh I figured it out sometime last night. 
But the apocalypse world doesn't render at all. My gui is squished and the whole world is gone. Just another problem with the 1.12.2 Verson I guess XD

**Comment by fbifridays** [comment]
yeh im having this problem as well

**Comment by voidegg** [comment]
My friends and i had the same issue. We solved it by starting the world in survival mode.

**Comment by ghost** [comment]
I'm having this issue as well... any fix?

**Comment by jamioflan** [comment]
This has been covered in the recent Apocalypse revamp
