### ISSUE TITLE
Weapons drop 

### ISSUE THREAD

**Issue by simswars** [FlansMods/FlansMod#914]
When I drop a weapon (on the floor for example), the weapon is duplicated (Only on a server, not in singleplayer).

![Uploading 2018-06-03_22.27.02.png…]()

**Comment by TheSebakl** [comment]
i think it's linked. sorry if it doesn't...
When i enter command /give TheSebakl flansmod:ak47 
the weapon is duplicated (one in inventory and the other in front of me) 
i didn't test in singleplayer.

**Comment by ChrisLane** [comment]
This has been fixed for the next version
