### ISSUE TITLE
can't run flansmod[1.12.2]

### ISSUE THREAD

**Issue by pianoman1916** [FlansMods/FlansMod#915]
error message: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Flan's Mod: Apocalypse (flansmodapocalypse)

I am using forge 2707and I tried with forge 655 both didn't work

**Comment by FangMRider** [comment]
did u use 2611 as said in the readme text

**Comment by pianoman1916** [comment]
@wolfey2900 
yup

**Comment by ChrisLane** [comment]
Should be fixed for the next version
