### ISSUE TITLE
Fuel Can causing Crash

### ISSUE THREAD

**Issue by StarConquest** [FlansMods/FlansMod#919]
When the fuel can is completely empty, it causes a crash. Here is the report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  ForgelinPlugin (Forgelin-1.7.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/14/18 10:47 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:438)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:82)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2013)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2480)
	at net.minecraft.entity.player.EntityPlayer.func_70098_U(EntityPlayer.java:461)
	at net.minecraft.world.World.func_72866_a(World.java:1985)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72866_a(World.java:2050)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72866_a(World.java:2050)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:438)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:82)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2013)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2480)
	at net.minecraft.entity.player.EntityPlayer.func_70098_U(EntityPlayer.java:461)
	at net.minecraft.world.World.func_72866_a(World.java:1985)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72866_a(World.java:2050)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72866_a(World.java:2050)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: flansmod:plane (com.flansmod.common.driveables.EntityPlane)
	Entity ID: 1022
	Entity Name: BF109
	Entity's Exact location: -474.48, 71.00, 1140.51
	Entity's Block location: World: (-475,71,1140), Chunk: (at 5,4,4 in -30,71; contains blocks -480,0,1136 to -465,255,1151), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntitySeat['entity.Seat.name'/1023, l='New World', x=-474.18, y=72.63, z=1140.54], EntityWheel['entity.Wheel.name'/1024, l='New World', x=-471.77, y=71.00, z=1139.80], EntityWheel['entity.Wheel.name'/1025, l='New World', x=-471.93, y=71.00, z=1141.73], EntityWheel['entity.Wheel.name'/1026, l='New World', x=-480.44, y=71.01, z=1140.00]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['StarConquest'/103, l='New World', x=-474.38, y=72.21, z=1140.52]]
	Chunk stats: ServerChunkCache: 897 Drop: 0
	Level seed: 5955978504002318196
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (212,64,200), Chunk: (at 4,4,8 in 13,12; contains blocks 208,0,192 to 223,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 271920 game time, 271920 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 100135 (now: false), thunder time: 103770 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1256200760 bytes (1198 MB) / 4278190080 bytes (4080 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                           | Version                  | Source                               | Signature                                |
	|:--------- |:-------------------------------------------- |:------------------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft                                    | 1.12.2                   | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp                                          | 9.42                     | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.4.2705.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                        | 14.23.4.2705             | forge-1.12.2-14.23.4.2705.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                        | None                                     |
	| UCHIJAAAA | arcanelamps                                  | 1.5                      | Arcane_Lamps_[1.5.1].jar             | None                                     |
	| UCHIJAAAA | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar               | None                                     |
	| UCHIJAAAA | bibliocraft                                  | 2.4.4                    | BiblioCraft[v2.4.4][MC1.12.2].jar    | None                                     |
	| UCHIJAAAA | guideapi                                     | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar          | None                                     |
	| UCHIJAAAA | bloodmagic                                   | 1.12.2-2.2.12-97         | BloodMagic-1.12.2-2.2.12-97.jar      | None                                     |
	| UCHIJAAAA | thaumcraft                                   | 6.1.BETA16               | Thaumcraft-1.12.2-6.1.BETA16.jar     | None                                     |
	| UCHIJAAAA | botania                                      | r1.10-354                | Botania+r1.10-354.jar                | None                                     |
	| UCHIJAAAA | crafttweaker                                 | 4.1.8                    | CraftTweaker2-1.12-4.1.8.jar         | None                                     |
	| UCHIJAAAA | ctgui                                        | 1.0.0                    | CraftTweaker2-1.12-4.1.8.jar         | None                                     |
	| UCHIJAAAA | mtlib                                        | 3.0.5                    | MTLib-3.0.5.jar                      | None                                     |
	| UCHIJAAAA | modtweaker                                   | 4.0.12                   | modtweaker-4.0.12.jar                | None                                     |
	| UCHIJAAAA | jei                                          | 4.10.0.198               | jei_1.12.2-4.10.0.198.jar            | None                                     |
	| UCHIJAAAA | crafttweakerjei                              | 2.0.2                    | CraftTweaker2-1.12-4.1.8.jar         | None                                     |
	| UCHIJAAAA | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar      | None                                     |
	| UCHIJAAAA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar  | None                                     |
	| UCHIJAAAA | flansmod                                     | 5.5.1                    | Flan's Mod-1.12.2-5.5.1.jar          | None                                     |
	| UCHIJAAAA | flansmodapocalypse                           | 1.0                      | Flan's Mod-1.12.2-5.5.1.jar          | None                                     |
	| UCHIJAAAA | forgelin                                     | 1.7.2                    | Forgelin-1.7.2.jar                   | None                                     |
	| UCHIJAAAA | icbmclassic                                  | 1.12.2-3.0.0.29          | ICBM-classic-1.12.2-3.0.0b29.jar     | None                                     |
	| UCHIJAAAA | immersiveengineering                         | 0.12-82                  | ImmersiveEngineering-0.12-82.jar     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | immersivepetroleum                           | 1.1.9                    | ImmersivePetroleum.jar               | None                                     |
	| UCHIJAAAA | trackapi                                     | 1.1                      | TrackAPI-1.1_1.12.jar                | None                                     |
	| UCHIJAAAA | immersiverailroading                         | 1.2.1                    | ImmersiveRailroading-1.2.1_1.12.jar  | None                                     |
	| UCHIJAAAA | ic2                                          | 2.8.73-ex112             | industrialcraft-2-2.8.73-ex112.jar   | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | wizardry                                     | 0.8.5                    | wizardry-0.8.5.jar                   | None                                     |
	| UCHIJAAAA | librarianlib                                 | 9.4                      | librarianlib-1.12.2-4.9.jar          | None                                     |
	| UCHIJAAAA | radixcore                                    | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar | None                                     |
	| UCHIJAAAA | mca                                          | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar       | None                                     |
	| UCHIJAAAA | mekanism                                     | 1.12.2-9.4.11.346        | Mekanism-1.12.2-9.4.11.346.jar       | None                                     |
	| UCHIJAAAA | projecte                                     | 1.12-PE1.3.0             | ProjectE-1.12-PE1.3.0.jar            | None                                     |
	| UCHIJAAAA | thaumicjei                                   | 1.2.1                    | Thaumic-JEI-Mod-1.12.2.jar           | None                                     |
	| UCHIJAAAA | thaumicequivalence                           | 1.12.2-1.0.2             | ThaumicEquivalence-1.12.2-1.0.2.jar  | None                                     |
	| UCHIJAAAA | thaumicperiphery                             | 0.2.3                    | thaumicperiphery-0.2.3.jar           | None                                     |
	| UCHIJAAAA | librarianliblate                             | 9.4                      | librarianlib-1.12.2-4.9.jar          | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
Wizardry Plugin (wizardry-0.8.5.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ForgelinPlugin (Forgelin-1.7.2.jar)
  
LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['StarConquest'/103, l='New World', x=-474.38, y=72.21, z=1140.52]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by PhysicalNova** [comment]
I'm not a developper here, but I think it's because the game tries to replace it with an empty version of the can, which doesn't exist. I would be fairly easy to fix I think. That's sad :'(...

**Comment by ChrisLane** [comment]
Just tried to recreate this in single player but couldn't. Could you provide more information and a crash log with just Flan's Mod installed?

**Comment by PhysicalNova** [comment]
@ChrisLane 
You couldn't reproduce it ? How curious. You simply need to put a fuel can in a vehicle and wait until the fuel can's durability reaches 0. The game should crash automatically... The last time I've seen this error was in the latest version of flan's mod (as of 03/07/2018, version 5.5.2 for minecraft 1.12.2)

**Comment by ChrisLane** [comment]
Hi, could you please check if the bug still happens with the files included in the zip below?
Please note that this is a test version only and should not be used on any worlds that you have not backed up.

[flans-test-15-10.zip](https://github.com/FlansMods/FlansMod/files/2480558/flans-test-15-10.zip)
