### ISSUE TITLE
Sometimes when jumping into Tiger tank

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#920]
[crash-2018-06-17_17.45.03-client.txt](https://github.com/FlansMods/FlansMod/files/2109142/crash-2018-06-17_17.45.03-client.txt)

It contains something like stack trace so should help. I will post video when I reproduce error (this is very rare exception and I don't know what causes it)

**Comment by ChrisLane** [comment]
Unable to reproduce
