### ISSUE TITLE
Transport bugs 1.12.2

### ISSUE THREAD

**Issue by DFO28** [FlansMods/FlansMod#922]
Hello! Recently I've started using Flans mod, and firstly installed 2 transport packs from different authors. On some reason, some car models of both packs, when start driving them, give an awful gluck. FPS falls down to 0 (!), game stops for minutes (!), but doesnt fully crash, than picture changes, and only when I use brakes and speed becomes 0, car stops and  FPS return to normal numbers. Strange thing that only some (I think most) models of cars are glitchy, not all. Some of them are working properly, as in other mods. I'd say it was something with exact pack, but the same thing happens to both, not just one, so it's definitely mod's issue. How can this problem be solved? Advanced thanks for help.

**Comment by DFO28** [comment]
After installing 3rd pack, all of it's cars are working normal, but their texture is pink and black colours, just as their icon in inventory, looks ugly. No details, only pink and black squares on the whole car body.

**Comment by ChrisLane** [comment]
Hi, this sounds like it might be an issue with the content packs. Could you post this issue to them?
