### ISSUE TITLE
minecraft 1.12.2 forge 14.23.4.2705 will not start due to Flans mod

### ISSUE THREAD

**Issue by LokosManyMan** [FlansMods/FlansMod#925]
https://paste.dimdev.org/ubelaroqal.mccrash

**Comment by CanineCraver** [comment]
Here's a link to an issue similiar to yours in that both crash reports contained apocalypse as far as I remember, fixed mine this way:

https://github.com/FlansMods/FlansMod/issues/894#issuecomment-386789804

Don't know why it selected that comment, whatever, it's the one above it.

**Comment by ChrisLane** [comment]
Should be fixed in the next version.
