### ISSUE TITLE
Can't shoot guns into the air.

### ISSUE THREAD

**Issue by EmeraldTiger64** [FlansMods/FlansMod#927]
Hello. I was in-game and noticed while trying to shoot at flying mobs that I can't just randomly shoot into the air. Is this a feature of the mod now or is it a bug? I am just wondering, because I am confused as to why I can't.

**Comment by ChrisLane** [comment]
Couldn't reproduce this issue. Could you confirm that you're using the latest version? Some more details would be great.
Closing for now.
