### ISSUE TITLE
Big Issues that makes the tank and anti air unusable!

### ISSUE THREAD

**Issue by tpdriver** [FlansMods/FlansMod#928]
For some reason the rounds explode right outside of the barrel of the tank or anti air..

**Comment by IvorAmlug** [comment]
its same with rockets and bombs from planes and Helicopters

**Comment by Joeburrell64** [comment]
Im having the same issue. Any fixes yet?

**Comment by tpdriver** [comment]
it was some door mod giving me the issues

**Comment by IvorAmlug** [comment]
Massilis ?

**Comment by IvorAmlug** [comment]
Massilis Doors ?

**Comment by tpdriver** [comment]
Yes it is

**Comment by IvorAmlug** [comment]
okay now i know the problem at least but theire is still the shader issue going on so yeah
