### ISSUE TITLE
How to hide friends' names?

### ISSUE THREAD

**Issue by Frankjyn** [FlansMods/FlansMod#929]
I've set up the game as the description on the official website. However, I found That I could not hide name tags on my and my friends' head. I've tried the scoreborad system, but the game only tell me that there's no code like "nametagVisibility ". I failed to create one-man team either. My game version is 1.7.2 forge. Would anyone give me a hand on this?

**Comment by ChrisLane** [comment]
Sorry but we don't support 1.7 versions anymore.
