### ISSUE TITLE
Help in Flans Mod

### ISSUE THREAD

**Issue by Hypergamer373** [FlansMods/FlansMod#930]
Hi i am a new user of flans mod
When i first downloaded it and checked inv in creative it showed no cars and guns and when i clicked the gun making box and vehicle making box it was empty and it was all white no vehicle or no gun just white boxes in vehicle and gun maing box .
i am using 1.7.10
please help me

**Comment by Hypergamer373** [comment]
i cnt even see them in my inventory

**Comment by IvorAmlug** [comment]
Download content packs and put them in the flans folder in your .minecraft
