### ISSUE TITLE
All deployable MGs are pointing to the floor

### ISSUE THREAD

**Issue by sasdasaslas** [FlansMods/FlansMod#931]
I have a glitch in the 1.12.2 version of flan's that makes all MG's pointing to the floor, i cant find any solutions online so im gonna ask here 
btw. i DONT have optifine or any other mods
Here some screenshots:
![2018-07-23_20 50 19](https://user-images.githubusercontent.com/41592170/43096612-f6a12d8a-8eb9-11e8-8dd1-25edc71f6395.png)

![2018-07-23_20 36 28](https://user-images.githubusercontent.com/41592170/43096552-bf33ab8e-8eb9-11e8-944f-1df20cc5cc09.png)
Any help is appreciated

**Comment by ghost** [comment]
it also happens to me
