### ISSUE TITLE
Flans shader issue 

### ISSUE THREAD

**Issue by IvorAmlug** [FlansMods/FlansMod#932]
There are some stuppid issues with flans and Shaders (SEUS) that make the water seable trough walls or at least glitches it out. Any fix for that ?
With out shaders not holding a gun:
![2018-07-25_19 33 16](https://user-images.githubusercontent.com/38656481/43217403-d5223bd4-9041-11e8-84dd-6b37db0dc9fe.png)
With out shaders holding a gun:
![2018-07-25_19 33 18](https://user-images.githubusercontent.com/38656481/43217454-fce689c2-9041-11e8-8008-3f7a98e32301.png)
With Shaders not holding a gun:
![2018-07-25_19 32 28](https://user-images.githubusercontent.com/38656481/43217501-1aaf207c-9042-11e8-9f29-f52af2f5819e.png)
With Shaders holding a gun:
![2018-07-25_19 32 26](https://user-images.githubusercontent.com/38656481/43217526-30136522-9042-11e8-851a-0fb492e4025b.png)

**Comment by yindaheng98** [comment]
i have same problems
not only SEUS

**Comment by IvorAmlug** [comment]
I only writen SEUS because i use it. I know its with every shader.

**Comment by IvorAmlug** [comment]
I fell kind of ignored. I know the devs have much to do and also that they have a realife and i love their work Flans and Optifne and Shaders are one of my favorite things in MC. 
But at least i want an answer to the question if its the shader (other shaders have other problems with cuda or kuda (how ever you spell) the rendering is complete gone its just a white world with enteties and you) or one of the mods (Optifine or Flans) and does this happen with other shader (optifine like) mods ?
And also if you are working on a fix or if it can get fixed.

**Comment by IvorAmlug** [comment]
![2018-09-29_13 43 50](https://user-images.githubusercontent.com/38656481/46245456-35614500-c3ee-11e8-9540-a6a820d91a4c.png)
![2018-09-29_13 43 51](https://user-images.githubusercontent.com/38656481/46245457-38f4cc00-c3ee-11e8-8a25-8272d244c336.png)
![2018-09-29_13 43 52](https://user-images.githubusercontent.com/38656481/46245458-3befbc80-c3ee-11e8-8fba-d302459b89bd.png)
![2018-09-29_13 45 23](https://user-images.githubusercontent.com/38656481/46245460-3f834380-c3ee-11e8-8643-1b5aba1a5167.png)
![2018-09-29_13 45 24](https://user-images.githubusercontent.com/38656481/46245465-4316ca80-c3ee-11e8-8aa9-98c1381a8308.png)
![2018-09-29_13 45 26](https://user-images.githubusercontent.com/38656481/46245469-4611bb00-c3ee-11e8-8101-3fa3533996dd.png)

Weird its only in Ego perspective...

**Comment by gnomed-by-steve** [comment]
This is a known issue, and I doubt it will be fixed anytime soon.

**Comment by IvorAmlug** [comment]
Well lets hope for the best. :D
