### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by khela9** [FlansMods/FlansMod#933]
screen and GUI somewhat flashed,couldnt see all items,when i created proto titan with ai chip game crashed.now when i enter the game with flans apocalypse mod it crashes everytime.intalled all content packs.version 1.8
also is there flans apocalypse mod for 1.7.10?

**Comment by ChrisLane** [comment]
Could you post a crash log please?
There's no Flan's Mod Apocalypse for 1.7.10
Does the same crash occur for you in 1.12.2?

**Comment by khela9** [comment]
i dont play 1.12.2,ill reinstall mods and capture screenshot tomorrow.
sorry for the late reply
