### ISSUE TITLE
Not enough items recipes not displaying

### ISSUE THREAD

**Issue by Qmodo** [FlansMods/FlansMod#937]
Hey guys, I'm setting up some mods together, and i noticed about 95% of recipes from flans aren't displaying with just enough items.

I'm running:
Flan's Mod-1.12.2-552
jei_1,12,2-4.11.0.206.jar

Things like gun boxes, gun attatchments, and most of the parts tab work, aside from that guns, vehicles, and armor all don't work. 

I'm not sure if this is a mod issue, or a config issue. Maybe I've missed a step somewhere, I'm not sure. Hopefully you can lead me in the correct direction!

**Comment by christopher0936** [comment]
It appears that JEI doesn't know how to process recipes for the Flan's mod crafting blocks. I tried with JEI Integrations and it didn't help.

**Comment by ChrisLane** [comment]
Flan's mod doesn't integrate with NEI/JEI at all. I've made a feature request for this (#1045)
