### ISSUE TITLE
Even with the Apocalypse content pack disabled, some content remains.

### ISSUE THREAD

**Issue by christopher0936** [FlansMods/FlansMod#940]
I have removed the Apocalypse content pack from my game, however there still remains a now entirely useless sulfur item, sulfuric acid forge liquid, and several laboratory blocks with missing textures. Is there any way to remove these things from the game entirely?

**Comment by Joeburrell64** [comment]
What I did is go into the flans mod JAR file with winrar and delete the Apocalypse folder from the assets and com folders. Im sure that is not recommended but it seems to have removed the apocalypse dimension from the game (which is what I wanted). So it should work for you, but I would for sure back everything up first.

**Comment by christopher0936** [comment]
Did you just hack the jar or did you actually change the source and recompile?

**Comment by ChrisLane** [comment]
Those are items from the apocalypse world which is part of the mod. These won't be removed.
