### ISSUE TITLE
No showing Robots in Titan-Contant Pack (flans mod)

### ISSUE THREAD

**Issue by DearBassDragon** [FlansMods/FlansMod#942]
First i try the Flans mod 1.7.2 and the robots not showing and the second i try on Minecraft version 1.12.2 and it's same. :C Can you please help me? Thanks!

**Comment by ChrisLane** [comment]
It sounds like you probably don't have the correct content packs installed.
Do you have Parts Pack, Mecha Parts Pack and Titan pack installed?
Please let me know what is in your 'Flan' folder.
