### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by stretchymcstretchlegs** [FlansMods/FlansMod#943]
Can't open Minecraft without crashing instantly

**Comment by ChrisLane** [comment]
Can you please paste your crash log to pastebin.com and give a link to it here, otherwise we can't help.

**Comment by stretchymcstretchlegs** [comment]
im really really sorry i didnt respond because i dont use my mail alot,link will come shortly    On Wednesday, 29 August 2018, 4:26:23 PM GMT+4:30, Chris Lane <notifications@github.com> wrote:  
 
 
Can you please paste your crash log to pastebin.com and give a link to it here, otherwise we can't help.
