### ISSUE TITLE
The Modern Warfare Mod dosn't start.

### ISSUE THREAD

**Issue by Raptor1818** [FlansMods/FlansMod#944]
The mod Modern Warfare won't start in 1.12.2
I downloaded the jar for 1.12.2 but it's not in the game.
What do i do?

**Comment by Larkenus** [comment]
If you play with different versions of forge, you'll need to separate them into separate folders (i.e. 1.8 mods in one folder, 1.9 in another, and so on) so the game can use the right mods.

If what you are talking about is a content pack, check to see if it's in the Flan folder and that it's for the right version.

Does this answer your question?

**Comment by ChrisLane** [comment]
Like @Larkenus mentioned, Modern Warfare is a content pack that needs to be in the `Flan` folder as well as Flan's Mod being in the mods folder.

Directory structure should look like this:
```
.
├── Flan
│   ├── Modern Warfare-Content Pack-1.12.2-5.5.2.jar
└── mods
    └── Flan's Mod-1.12.2-5.5.2.jar
```
