### ISSUE TITLE
Really bad accuracy on some guns

### ISSUE THREAD

**Issue by HighwayStar54** [FlansMods/FlansMod#948]
https://youtu.be/6hZqXOf98P0

**Comment by HighwayStar54** [comment]
Oh and sorry about the awfuk quality, I had to spare some time and bandwidth

**Comment by HighwayStar54** [comment]
You could also reply to my issue instead of closing it one year after.

**Comment by HighwayStar54** [comment]
Replying to my issue instead of closing it one year after would also have been pretty neat.

**Comment by ChrisLane** [comment]
Please create a new issue or modify your existing one to include details of which guns have bad accuracy and why you think the accuracy should be improved.
Watching a YouTube video isn't a particularly good workflow for working on issues and I don't recall other people commenting on the accuracy of guns.
