### ISSUE TITLE
Flans mod doesnt let me drop bombs from my vehicles or shoot

### ISSUE THREAD

**Issue by CTmatey** [FlansMods/FlansMod#950]
the helicopters and the planes dont shoot or drop bombs why? i have the right ammo

**Comment by IvorAmlug** [comment]
is Massilis Doors installed ?

**Comment by IvorAmlug** [comment]
It has issues with flans

**Comment by solslinger55** [comment]
i have the same problem but only the planes dont work and i can drop bombs

**Comment by CTmatey** [comment]
i will check

**Comment by CTmatey** [comment]
no is it meant to be?

**Comment by IvorAmlug** [comment]
No its most time the case of the error any other massilis mod?

**Comment by CTmatey** [comment]
Ok thanks anyways

**Comment by ChrisLane** [comment]
Duplicate of #910
