### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Abadakor** [FlansMods/FlansMod#953]
Hi, I have installed the flan's mod on my server running with Sponge. The server start well without content pack but once I put a content pack, the server crash when restarting. 
Thanks

crash-report:
[crash-2018-09-20_12.11.32-server.txt](https://github.com/FlansMods/FlansMod/files/2400818/crash-2018-09-20_12.11.32-server.txt)

and logs: 
[latest.log](https://github.com/FlansMods/FlansMod/files/2400824/latest.log)

**Comment by ChrisLane** [comment]
"drzhark.customspawner" from the crash log points towards this being an issue with your "customspawner" mod.

Also, it seems you've not added all the required content packs for the modern weapons content pack. You'll need the Simple Parts Pack too.
