### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by SOLUPRED3** [FlansMods/FlansMod#954]
I can't run my minecraft (with flan's mod downloaded) without crashing instantly

here is my crash report :

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 9/21/18 5:27 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:541)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:492)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:227)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:541)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:492)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:227)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 333153392 bytes (317 MB) / 1778384896 bytes (1696 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_E1 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version                  | Source                                         | Signature                                |
	|:------ |:------------------ |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft          | 1.12.2                   | minecraft.jar                                  | None                                     |
	| UCHIJA | mcp                | 9.42                     | minecraft.jar                                  | None                                     |
	| UCHIJA | FML                | 8.0.99.99                | forge-1.12.2-14.23.4.2705.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge              | 14.23.4.2705             | forge-1.12.2-14.23.4.2705.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | baubles            | 1.5.2                    | Baubles-Mod-1.12.2.jar                         | None                                     |
	| UCHIJA | bibliocraft        | 2.4.5                    | BiblioCraft-Mod-1.12.2.jar                     | None                                     |
	| UCHIJA | carryon            | 1.9.3                    | Carry-On-Mod-1.12.2.jar                        | None                                     |
	| UCHIJA | cavern             | 2.1.8                    | Cavern_1.12.2-v2.1.8.jar                       | None                                     |
	| UCHIJA | ctm                | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                      | None                                     |
	| UCHIJA | chisel             | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31 (1).jar               | None                                     |
	| UCHIJA | chiselsandbits     | 14.8                     | Chisels-and-Bits-Mod-1.12.1.jar                | None                                     |
	| UCHIJA | ebwizardry         | 4.1.2                    | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2.jar | None                                     |
	| UCHIJA | flansmod           | 5.5.1                    | Flan's Mod-1.12.2-5.5.1.jar                    | None                                     |
	| UCHIJA | flansmodapocalypse | 1.0                      | Flan's Mod-1.12.2-5.5.1.jar                    | None                                     |
	| UCHIJA | furnaceoverhaul    | 1.0.5                    | furnaceoverhaul-1.12.2-1.0.5.jar               | None                                     |
	| UCHIJA | ichunutil          | 7.1.4                    | iChun-Util-Mod-1.12.2.jar                      | None                                     |
	| UCHIJA | hats               | 7.0.0                    | iChuns-Hats-Mod-1.12.2.jar                     | None                                     |
	| UCHIJA | inventorytweaks    | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironbackpacks      | 1.12.2-3.0.8-12          | Iron-Backpacks-Mod-1.12.2.jar                  | None                                     |
	| UCHIJA | ironchest          | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                | None                                     |
	| UCHIJA | jei                | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                       | None                                     |
	| UCHIJA | journeymap         | 1.12.2-5.5.2             | JourneyMap-Mod-1.12.2-Unlimited.jar            | None                                     |
	| UCHIJA | levelup2           | ${version}               | Level-Up-Mod-1.12.2.jar                        | None                                     |
	| UCHIJA | malisiscore        | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                   | None                                     |
	| UCHIJA | malisisdoors       | 1.12.2-7.3.0             | MalisisDoors-Mod-1.12.2.jar                    | None                                     |
	| UCHIJA | mantle             | 1.12-1.3.2.24            | Mantle-Mod-1.12.2.jar                          | None                                     |
	| UCHIJA | cfm                | 5.3.1                    | MrCrayfishs-Furniture-Mod-1.12.2.jar           | None                                     |
	| UCHIJA | mw                 | 1.11.7.7                 | mw-1.11.7.7_mc1.12.2.jar                       | None                                     |
	| UCHIJA | primitivemobs      | 1.1.4b                   | primitivemobs-1.1.4b_beta.jar                  | None                                     |
	| UCHIJA | tconstruct         | 1.12.2-2.9.0.55          | Tinkers-Construct-Mod-1.12.2.jar               | None                                     |
	| UCHIJA | waila              | 1.8.20                   | waila-1.12.jar                                 | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.32.0 355.11.10.10.40.102' Renderer: 'NVIDIA GeForce GT 755M OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 755M OpenGL Engine GL version 2.1 NVIDIA-10.32.0 355.11.10.10.40.102, NVIDIA Corporation
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 11
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 NVIDIA-10.32.0 355.11.10.10.40.102
	OpenGlRenderer: NVIDIA GeForce GT 755M OpenGL Engine
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by SOLUPRED3** [comment]
And when i delete all the other mods I have, it still crash
There is my crash report : 

---- Minecraft Crash Report ----
// Don't do that.

Time: 9/21/18 9:52 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:541)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:492)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:227)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:541)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:492)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:227)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3973746808 bytes (3789 MB) / 5066719232 bytes (4832 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version      | Source                        | Signature                                |
	|:------ |:------------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft          | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJA | mcp                | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJA | FML                | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge              | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | flansmod           | 5.5.1        | Flan's Mod-1.12.2-5.5.1.jar   | None                                     |
	| UCHIJA | flansmodapocalypse | 1.0          | Flan's Mod-1.12.2-5.5.1.jar   | None                                     |
	| UCHIJA | jei                | 4.8.5.159    | jei_1.12.2-4.8.5.159.jar      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.32.0 355.11.10.10.40.102' Renderer: 'NVIDIA GeForce GT 755M OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 755M OpenGL Engine GL version 2.1 NVIDIA-10.32.0 355.11.10.10.40.102, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz

**Comment by ChrisLane** [comment]
I've been unable to reproduce this crash and haven't seen it before.

Could you please try with a clean install of Forge and Flan's Mod? I noticed from your second crash log that you still had JEI installed, though I don't expect that to be an issue.
Could you also post the filenames from your Flan directory? Perhaps you have a broken content pack or duplicates.

**Comment by SOLUPRED3** [comment]
I had a broken content part, I didn,t see him, thank you for your help
