### ISSUE TITLE
invalid event annotation EventHandler

### ISSUE THREAD

**Issue by FrayFox** [FlansMods/FlansMod#955]
I am currently running

SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3455
Forge version: forge-1.12.2-14.23.4.2759
Java version: Version 8 update181
Operating System: Windows10
Plugins/Mods:
Plugins (14): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge, GriefPrevention, LangSwitch, Lottery, LuckPerms, MMCRestrict, Nucleus, ProjectCore, RankUpper, Total Economy, VillagerShops
Mods (47): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AppleSkin, Aroma1997's Dimensional World, Aroma1997Core, AromaBackup, AromaBackuprecovery, BiblioCraft, Biomes O' Plenty, ChickenChunks, CoFH Core, CoFH World, CodeChicken Lib, Construct's Armory, EnderStorage, Extra Utilities 2, Extreme Reactors, Flan's Mod, Flan's Mod: Apocalypse, Forestry, Industrial Foregoing, Inventory Tweaks, Iron Chest, Just Enough Items, Mantle, Morpheus, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Redstone Flux, Shadowfacts' Forgelin, Tesla Core Lib, Tesla Core Lib Registries, The Twilight Forest, Thermal Expansion, Thermal Foundation, Tinkers' Construct, UniDict, WanionLib, Zero CORE, mob_grinding_utils
Issue Description
All of the additions from Flan's Mod do not at all respect GriefPrevention protections, and after reading a bit i'm assuming that they do not fire events that GriefPrevention can handle. Looking through the server log i'm getting this:
[Server thread/ERROR] [FML]: The mod flansmod appears to have an invalid event annotation EventHandler. This annotation can only apply to methods with recognized event arguments - it will not be called

(If needed I can run again with only flans, and SpongeForge but i don't have a reason to believe another mod/plugin is causing this.

https://gist.github.com/FrayFox/136fde51514d877c73cb85210fe384da

**Comment by ChrisLane** [comment]
The EventHandler annotation is in relation to the loot tables event handler being incorrect in the mod and so is unrelated to this issue.

Could you tell me exactly what you expect to be protected against that isn't?

**Comment by FrayFox** [comment]
i'm using grief prevention, and when I prote3ct an area i.e. spawn, i dont want explosive, planes, etc from damaging any of the structures while still being able to destroy unclaimed areas, and that isnt possible because GriefPrevention or anything for that matter is able to get the events to prevent damage

**Comment by ChrisLane** [comment]
Hi, could you please test if this version fixes the issue?
*Note: Please do not run this on a production server. You will need to add this version to both client and server for server/client compatibility.

Download:
https://mega.nz/#!schXjZoS!3p3rYl1i3MFNAbVtuZ4n4RilOh98AU9FvRtn9j61jC8

**Comment by FrayFox** [comment]
> Hi, could you please test if this version fixes the issue?
> *Note: Please do not run this on a production server. You will need to add this version to both client and server for server/client compatibility.
> 
> Download:
> https://mega.nz/#!schXjZoS!3p3rYl1i3MFNAbVtuZ4n4RilOh98AU9FvRtn9j61jC8

Sorry it took me a while to reply, it is still broken, and the same error appeared during startup

**Comment by ChrisLane** [comment]
Please ignore the error for now. You're saying that grief prevention was not able to protect from Flan's Mod actions? What exactly did you test?

I ask because I just tested this myself and was unable to destroy any blocks in a protected region using mechs, guns, grenades etc.

**Comment by FrayFox** [comment]
I was using the minigun with explosive ammo. If i focus fire on a block for about a second, it breaks the block i was shooting at with missing texture particles (black and purple) coming from the destroyed block

**Comment by rvveber** [comment]
This was fixed in a sponge update. 3406 to be exact

**Comment by ChrisLane** [comment]
Thanks for letting me know.
