### ISSUE TITLE
"gradlew eclipse" does not work

### ISSUE THREAD

**Issue by DerScherenmann** [FlansMods/FlansMod#956]
I would like to edit some stuff but i cant make an eclipse workspace. What should I do?

**Comment by ChrisLane** [comment]
In what way does it "not work"? Any errors? Further details?
./gradlew eclipse works fine for me to produce eclipse project files though I personally use IntelliJ Idea

**Comment by DerScherenmann** [comment]
It doesnt create an "eclipse" folder and shows no errors, running on a windows machine

**Comment by ChrisLane** [comment]
Do you have an old version of eclipse?
I can confirm that an eclipse folder isn't created but the .project, .classpath files and .settings directory were sufficient to load the project in eclipse when I tried. On Windows, these will be hidden files I imagine.

**Comment by DerScherenmann** [comment]
Somehow it now worked, thanks
