### ISSUE TITLE
Crafting planes without all necessary parts consumes them anyway.

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#960]
**This only happens if a metal propeller is present.** Most notable with Tornado (Modern Weapons Pack).
Acquire an advanced metal cockpit and click "Craft" in the respective screen. Nothing will happen. Now acquire a metal propeller and try clicking "Craft" again. Both items will disappear from the inventory. For the record, it removes _all_ required recipe items it can find in the inventory up to the necessary amount. (It will only remove 8 out of 10 gray dyes, or 2 out of 7 wings, for example.)

**Comment by ChrisLane** [comment]
Thanks for reporting this, I can imagine it's claimed quite a few items from people!
