### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by simswars** [FlansMods/FlansMod#963]
It has a problem with this textures : 

in modern weapons content pack : 

- Leopard 2A6

in WW2 content pack : 

- STG 44
- FG 42
- Luger
- Panzerschreck
- SU-1-12

for all of that, it miss textures.

**Comment by ChrisLane** [comment]
Fixed these for the next version.
See: https://github.com/FlansMods/FlansMod/releases/tag/v5.6-beta.1
