### ISSUE TITLE
Modpack not Loading

### ISSUE THREAD

**Issue by jake4832** [FlansMods/FlansMod#964]
I have a modpack with around 60 mods and every time I try to add Flan's the pack crashes. It loads and plays just fine without Flan's. I want the mod in there and I'm guessing it's an issue with one of the other mods conflicting or something but I can't tell which. Here's the crash report

[crash-2018-10-26_16.11.24-client.txt](https://github.com/FlansMods/FlansMod/files/2520812/crash-2018-10-26_16.11.24-client.txt)

**Comment by ChrisLane** [comment]
Please try with the files in this beta version: https://github.com/FlansMods/FlansMod/releases/tag/v5.6-beta

**Comment by nilswinking** [comment]
#894

**Comment by nilswinking** [comment]
it's ap problem with mod like galacticraft just delete all files inside flans.jar that refer do apocalypse

**Comment by ChrisLane** [comment]
Assuming Galacticraft was the issue, I've tested and this is fixed in the version I gave.
