### ISSUE TITLE
The game crashes when I'm filling a plane with fuel (not instantly) 1.12.2

### ISSUE THREAD

**Issue by Migmag789** [FlansMods/FlansMod#967]
Hey ! I was about to fly, but before I had to fill my little big plane with oil. I did it. It was very slow, slower than the normal, and poof! It crashed. The game crashed. Can you help me please ? :D 

https://paste.dimdev.org/rotasugani.mccrash

**Comment by Migmag789** [comment]
Now, my world crashes instantly when I try to connect. 
https://paste.dimdev.org/akuvimodim.mccrash

**Comment by ChrisLane** [comment]
Please try the version here:
https://github.com/FlansMods/FlansMod/releases/tag/v5.6-beta

**Comment by Migmag789** [comment]
Thank you very much ! :D
