### ISSUE TITLE
[1.12] crash when clicking on certain vehicles in a vehicle bench

### ISSUE THREAD

**Issue by mensreaMC** [FlansMods/FlansMod#971]
https://paste.dimdev.org/ijiguyoxik.mccrash

I have several other vehicles in the pack and none of them do this, just the one.

**Comment by ChrisLane** [comment]
What content pack is it? Which vehicle?

**Comment by mensreaMC** [comment]
It's a custom pack, not one of flans default ones. I tried updating the greylight content pack to work on 1.12.

**Comment by ChrisLane** [comment]
I suspect you've made a mistake in the config for the vehicle that causes the crash. For me to debug this, it would be useful to have the files.

**Comment by ChrisLane** [comment]
I can fix the crash but the issue is caused by whatever vehicle you're trying to click not having a "Name" value (I think)

**Comment by mensreaMC** [comment]
https://pastebin.com/reV5ZSC7 this is the config for the vehicle in question.

**Comment by ChrisLane** [comment]
Could you try this version, please?
[test-version.zip](https://github.com/FlansMods/FlansMod/files/2600997/test-version.zip)

**Comment by mensreaMC** [comment]
It works, thanks. There's some weird graphical glitches for things in the background but only with the vehicle selected.
