### ISSUE TITLE
[1.12][suggestion] merge flans mod+ changes with 1.12 build

### ISSUE THREAD

**Issue by mensreaMC** [FlansMods/FlansMod#972]
Like the title says. The flans mod+ builds were basically third party modifications of flans that fixed a lot of features and added a lot more. I imagine a lot of it won't work, or won't work without basically rewriting it, but the flans mod+ builds have a lot of features and fixes that flans 1.12 is missing.

https://github.com/war-monger/Flan-s-Mod-Plus-War_Monger

https://github.com/Demitto/Flan-s-Mod-Plus

**Comment by ChrisLane** [comment]
They are free to open a pull request for anything they think should be changed in the mod but I'm not going to go through their 1.7.10 code myself to find useful parts.

Also, it should be noted that they are in fact breaking the license by not giving credit or including copyright information.
