### ISSUE TITLE
PLEASE FIX! 1.12.2 UNABLE TO RUN FLAN'S MOD 

### ISSUE THREAD

**Issue by UltiMultiGamer** [FlansMods/FlansMod#991]
The crash A LOT of users are experiencing is this:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Flan's Mod: Apocalypse (flansmodapocalypse)

On README.txt it says "You will need Minecraft 1.12.2 and Forge 2611 or later!", I have the later version, and it is not booting up under any ciricumstance, and throws me out. PLEASE FIX! DO NOT CLOSE THE DISCUSSION PLEASE!

**Comment by ChrisLane** [comment]
Crash report template not followed so not enough information provided. E.g. Forge version, full crash report, mod version etc.
