### ISSUE TITLE
Planes disappearing at high speeds in servers.

### ISSUE THREAD

**Issue by 247Tossing** [FlansMods/FlansMod#993]
**Describe the bug**
Any plane/vehicle disappears on server.

**To Reproduce**
1.  log into a server
2.  spawn a plane
3.  fly as fast as you can in one direction and eventually the plane disappears and you're unable to place another plane.
https://streamable.com/4eygd
(Our server is public and we would be more than happy to demonstrate it for you!)

**Expected behavior**
Planes don't randomly disappear.

**Screenshots**
its hard to take a screenshot of something that disappears.

**Versions (please complete the following information):**
 - Forge: 1.12.2-2768
 - Flan's Mod: 5.6 - jan 8th bug fix

**Additional context**
not much more to add. Like i said before we're happy to give you a first hand look on our server to see the issue for yourself. I searched the issue threads already and didn't see anything that matched my issue.

**Comment by ChrisLane** [comment]
@247Tossing 
When you log back in, is the plane still in the world? 
Do you log back in at the same location as when you were removed from the plane?

**Comment by 247Tossing** [comment]
No, the plane is completely gone. It's possible that I just couldnt find the entity because of how fast it is, but im pretty sure if you exit a plane it stop immediately, and yeah it logs it where the plane disappeared.

**Comment by ChrisLane** [comment]
In that case I need a bit more information.

Some server software will remove entities that travel above a set speed (this could even be a forge config option but can't check right now). 
1. What server software/version are you using?
2. Can you reproduce this on a clean forge server? (no build raft etc)
3. Can you reproduce this in single player?

**Comment by 247Tossing** [comment]
If by server software you mean like management panels were using AMP, but i dont think that's what you mean. We have SpongeForge installed with a couple plug-ins so I'll see if those are throwing errors, and I'll go test this on my test server to see if it happens on a clean forge server, and in so and report back.

**Comment by ChrisLane** [comment]
SpongeForge has a config option 'max-speed' that will remove entities going over the configured value.

Please read: https://docs.spongepowered.org/stable/en/server/getting-started/configuration/sponge-conf.html
