### ISSUE TITLE
[1.12.2] [bug] Can't get into apocalypse dimension.

### ISSUE THREAD

**Issue by Matusha** [FlansMods/FlansMod#995]
For some odd reason I can't get into apocalypse dimension after crafting the mech with an AI and putting it down. When I put it down it didn't start spinning as it should be. Also can't get in and use it.

 - Forge: 1.12.2-14.23.5.2768-universal
 - Flan's Mod: 5.6

**Comment by ChrisLane** [comment]
Please stick to the bug report template next time.

What other mods are installed? Does the issue still occur with only Flan's Mod installed?
Have you tried crafting a new mech with an AI chip?
Please provide a paste link to the client log.

I've been unable to reproduce the issue and so require this information to help.
