### ISSUE TITLE
Vehicle Weapons not functioning as they should

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#996]
There is an issue with drivers secondary weapons.
E.g of it, main armaments work (missiles, tank cannons etc) but guns like aircraft's main guns (e.g minigun on a-10, drivers guns on ww2 aircraft) DO NOT WORK. Also, guns that are controlled by another player for example the minigun on the huey cobra work FINE.

1. Get a vehicle such as A-10, spitfire, bf109 and much more and load the gun slots
2. Try to fire it
3. Doesn't work

The weapons are supposed to fire as normal, e.g minigun on a-10 should fire as a minigun.

 - Forge: 1.12.2 - 14.23.5.2768
 - Flan's Mod: Flans Mod-1.12.2-5.6

Any insight into this issue will be appreciated, thanks.

**Comment by ChrisLane** [comment]
Duplicate of #910
